In [6]:
import pandas as pd 
df=pd.read_csv('spain_rail_OD_flows.csv',sep=';')

In [7]:
df

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Madrid Puerta de Atocha,Barcelona Sants,Madrid,Barcelona,Comunidad de Madrid,Cataluña,10.439,Larga Distancia / AVE,Eurostat - Railway passenger transport statist...
1,2016,Madrid Puerta de Atocha,Málaga María Zambrano,Madrid,Málaga,Comunidad de Madrid,Andalucía,3.071,Larga Distancia / AVE,ADIF - Estadísticas de tráfico ferroviario por...
2,2016,Madrid Puerta de Atocha,Zaragoza Delicias,Madrid,Zaragoza,Comunidad de Madrid,Aragón,1.498,Larga Distancia / AVE,Renfe Viajeros - Informes de gestión (viajeros...
3,2016,Madrid Chamartín,Zaragoza Delicias,Madrid,Zaragoza,Comunidad de Madrid,Aragón,0.777,Larga Distancia / AVE,Renfe Viajeros - Informes de gestión (viajeros...
4,2016,Madrid Chamartín,Valladolid Campo Grande,Madrid,Valladolid,Comunidad de Madrid,Castilla y León,2.993,Larga Distancia / AVE,ADIF - Estadísticas de tráfico ferroviario por...
...,...,...,...,...,...,...,...,...,...,...
78,2024,Sevilla Santa Justa,Madrid Puerta de Atocha,Sevilla,Madrid,Andalucía,Comunidad de Madrid,4.196,Larga Distancia / AVE,Eurostat - Railway passenger transport statist...
79,2024,Sevilla Santa Justa,Barcelona Sants,Sevilla,Barcelona,Andalucía,Cataluña,2.122,Larga Distancia / AVE,Eurostat - Railway passenger transport statist...
80,2024,Zaragoza Delicias,Valencia Joaquín Sorolla,Zaragoza,Valencia,Aragón,Comunidad Valenciana,0.681,Larga Distancia / AVE,ADIF - Estadísticas de tráfico ferroviario por...
81,2024,Bilbao-Abando Indalecio Prieto,Madrid Chamartín,Bilbao,Madrid,País Vasco,Comunidad de Madrid,5.142,Larga Distancia,Eurostat - Railway passenger transport statist...
82,2024,Valladolid Campo Grande,Málaga María Zambrano,Valladolid,Málaga,Castilla y León,Andalucía,1.217,Larga Distancia,ADIF - Estadísticas de tráfico ferroviario por...

In [8]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type', 'source'],
      dtype='object')

In [9]:
df.shape

(83, 10)

In [10]:
df.isnull().sum()

year                        0
origin_station_name         0
destination_station_name    0
origin_city                 0
destination_city            0
origin_region               0
destination_region          0
Passengers_millions         0
Type                        0
source                      0
dtype: int64

In [11]:
df.isnull().mean()

year                        0.0
origin_station_name         0.0
destination_station_name    0.0
origin_city                 0.0
destination_city            0.0
origin_region               0.0
destination_region          0.0
Passengers_millions         0.0
Type                        0.0
source                      0.0
dtype: float64

In [12]:
df.dtypes

year                          int64
origin_station_name          object
destination_station_name     object
origin_city                  object
destination_city             object
origin_region                object
destination_region           object
Passengers_millions         float64
Type                         object
source                       object
dtype: object

In [15]:
df=df.drop(columns=['source'])

In [16]:
df

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type
0,2016,Madrid Puerta de Atocha,Barcelona Sants,Madrid,Barcelona,Comunidad de Madrid,Cataluña,10.439,Larga Distancia / AVE
1,2016,Madrid Puerta de Atocha,Málaga María Zambrano,Madrid,Málaga,Comunidad de Madrid,Andalucía,3.071,Larga Distancia / AVE
2,2016,Madrid Puerta de Atocha,Zaragoza Delicias,Madrid,Zaragoza,Comunidad de Madrid,Aragón,1.498,Larga Distancia / AVE
3,2016,Madrid Chamartín,Zaragoza Delicias,Madrid,Zaragoza,Comunidad de Madrid,Aragón,0.777,Larga Distancia / AVE
4,2016,Madrid Chamartín,Valladolid Campo Grande,Madrid,Valladolid,Comunidad de Madrid,Castilla y León,2.993,Larga Distancia / AVE
...,...,...,...,...,...,...,...,...,...
78,2024,Sevilla Santa Justa,Madrid Puerta de Atocha,Sevilla,Madrid,Andalucía,Comunidad de Madrid,4.196,Larga Distancia / AVE
79,2024,Sevilla Santa Justa,Barcelona Sants,Sevilla,Barcelona,Andalucía,Cataluña,2.122,Larga Distancia / AVE
80,2024,Zaragoza Delicias,Valencia Joaquín Sorolla,Zaragoza,Valencia,Aragón,Comunidad Valenciana,0.681,Larga Distancia / AVE
81,2024,Bilbao-Abando Indalecio Prieto,Madrid Chamartín,Bilbao,Madrid,País Vasco,Comunidad de Madrid,5.142,Larga Distancia
82,2024,Valladolid Campo Grande,Málaga María Zambrano,Valladolid,Málaga,Castilla y León,Andalucía,1.217,Larga Distancia

In [17]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type'],
      dtype='object')

In [18]:
df=pd.read_csv('germany_rail_OD_flows.csv',sep=';')

In [19]:
df

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Berlin Hbf,Frankfurt (Main) Hbf,Berlin,Frankfurt am Main,Berlin,Hessen,2.539,Fernverkehr,Eurostat - Railway passenger transport statist...
1,2016,Berlin Hbf,Hannover Hbf,Berlin,Hannover,Berlin,Niedersachsen,1.098,Fernverkehr,Deutsche Bahn - Facts & Figures (long-distance...
2,2016,Hamburg Hbf,Frankfurt (Main) Hbf,Hamburg,Frankfurt am Main,Hamburg,Hessen,2.493,Fernverkehr,Eurostat - Railway passenger transport statist...
3,2016,Hamburg Hbf,Köln Hbf,Hamburg,Köln,Hamburg,Nordrhein-Westfalen,0.848,Fernverkehr,VDV - Statistik zum SPNV in Deutschland (used ...
4,2016,Hamburg Hbf,Leipzig Hbf,Hamburg,Leipzig,Hamburg,Sachsen,1.139,Fernverkehr,Deutsche Bahn - Facts & Figures (long-distance...
...,...,...,...,...,...,...,...,...,...,...
105,2024,Köln Hbf,Frankfurt (Main) Hbf,Köln,Frankfurt am Main,Nordrhein-Westfalen,Hessen,12.912,Fernverkehr,Eurostat - Railway passenger transport statist...
106,2024,Düsseldorf Hbf,Hannover Hbf,Düsseldorf,Hannover,Nordrhein-Westfalen,Niedersachsen,0.898,Fernverkehr,Eurostat - Railway passenger transport statist...
107,2024,Leipzig Hbf,Berlin Hbf,Leipzig,Berlin,Sachsen,Berlin,1.893,Fernverkehr,VDV - Statistik zum SPNV in Deutschland (used ...
108,2024,Hannover Hbf,Köln Hbf,Hannover,Köln,Niedersachsen,Nordrhein-Westfalen,2.237,Fernverkehr,Deutsche Bahn - Facts & Figures (long-distance...
109,2024,Hannover Hbf,Düsseldorf Hbf,Hannover,Düsseldorf,Niedersachsen,Nordrhein-Westfalen,0.793,Fernverkehr,Deutsche Bahn - Facts & Figures (long-distance...

In [20]:
df=df.drop(columns=['source'])

In [21]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type'],
      dtype='object')

In [22]:
df=pd.read_csv('italy_rail_OD_flows.csv',sep=';')

In [23]:
df

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Milano Centrale,Napoli Centrale,Milano,Napoli,Lombardia,Campania,5.730,Alta Velocita,FS Research Centre - Methodological aspects fo...
1,2016,Milano Centrale,Torino Porta Nuova,Milano,Torino,Lombardia,Piemonte,9.118,Alta Velocita,Eurostat - Railway passenger transport statist...
2,2016,Milano Centrale,Venezia Santa Lucia,Milano,Venezia,Lombardia,Veneto,3.384,Alta Velocita,FS Italiane - Studi e ricerche sulla mobilità ...
3,2016,Napoli Centrale,Roma Termini,Napoli,Roma,Campania,Lazio,3.396,Alta Velocita,FS Research Centre - Methodological aspects fo...
4,2016,Torino Porta Nuova,Bari Centrale,Torino,Bari,Piemonte,Puglia,4.304,Intercity,FS Research Centre - Methodological aspects fo...
...,...,...,...,...,...,...,...,...,...,...
90,2024,Bologna Centrale,Roma Termini,Bologna,Roma,Emilia-Romagna,Lazio,4.484,Alta Velocita,FS Italiane - Studi e ricerche sulla mobilità ...
91,2024,Firenze S. M. Novella,Milano Centrale,Firenze,Milano,Toscana,Lombardia,3.657,Alta Velocita,FS Italiane - Studi e ricerche sulla mobilità ...
92,2024,Firenze S. M. Novella,Bologna Centrale,Firenze,Bologna,Toscana,Emilia-Romagna,2.543,Alta Velocita,Eurostat - Railway passenger transport statist...
93,2024,Bari Centrale,Venezia Santa Lucia,Bari,Venezia,Puglia,Veneto,3.690,Regionale,Eurostat - Railway passenger transport statist...
94,2024,Bari Centrale,Palermo Centrale,Bari,Palermo,Puglia,Sicilia,3.375,Regionale,FS Research Centre - Methodological aspects fo...

In [25]:
df=df.drop(columns=['source'])

In [26]:
df.shape

(95, 9)

In [27]:
df=pd.read_csv('switzerland_rail_OD_flows.csv',sep=';')

In [28]:
df

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Genève,Winterthur,Genève,Winterthur,Genève,Zürich,1.638,Long-distance,SBB - Passenger frequency by station (used to ...
1,2016,Genève,Fribourg/Freiburg,Genève,Fribourg,Genève,Fribourg,2.083,Long-distance,Eurostat - Railway passenger transport statist...
2,2016,Lausanne,Zürich HB,Lausanne,Zürich,Vaud,Zürich,1.444,Long-distance,SBB Facts & Figures - Passenger transport (int...
3,2016,Lausanne,Fribourg/Freiburg,Lausanne,Fribourg,Vaud,Fribourg,0.639,Long-distance,SBB Facts & Figures - Passenger transport (int...
4,2016,Luzern,Lugano,Luzern,Lugano,Luzern,Ticino,1.649,Long-distance,SBB - Passenger frequency by station (used to ...
...,...,...,...,...,...,...,...,...,...,...
83,2024,Winterthur,Luzern,Winterthur,Luzern,Zürich,Luzern,3.155,Regional,SBB - Passenger frequency by station (used to ...
84,2024,Fribourg/Freiburg,Winterthur,Fribourg,Winterthur,Fribourg,Zürich,3.597,Regional,SBB - Passenger frequency by station (used to ...
85,2024,Lugano,Basel SBB,Lugano,Basel,Ticino,Basel-Stadt,0.905,Long-distance,SBB - Passenger frequency by station (used to ...
86,2024,Lugano,St. Gallen,Lugano,St. Gallen,Ticino,St. Gallen,1.519,Long-distance,Eurostat - Railway passenger transport statist...
87,2024,Lugano,Fribourg/Freiburg,Lugano,Fribourg,Ticino,Fribourg,4.870,Long-distance,SBB Facts & Figures - Passenger transport (int...

In [29]:
df=df.drop(columns=['source'])

In [30]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type'],
      dtype='object')

In [31]:
df=pd.read_csv('cross_border_rail_OD_IT_DE_CH_ES.csv',sep=';')

In [32]:
df

,year,origin_country,origin_station_name,origin_city,origin_region,destination_country,destination_station_name,destination_city,destination_region,Passengers_millions,Type,source
0,2016,Italy,Roma Termini,Roma,Lazio,Germany,München Hbf,München,Bayern,0.730,Long-distance,Railway operators timetables and reports (Tren...
1,2016,Italy,Milano Centrale,Milano,Lombardia,Germany,Frankfurt (Main) Hbf,Frankfurt am Main,Hessen,0.971,Long-distance,EU Commission - Reports on cross-border rail p...
2,2016,Italy,Milano Centrale,Milano,Lombardia,Germany,Hamburg Hbf,Hamburg,Hamburg,2.723,Long-distance,Railway operators timetables and reports (Tren...
3,2016,Italy,Milano Centrale,Milano,Lombardia,Switzerland,Zürich HB,Zürich,Zürich,0.544,Long-distance,Eurostat - Railway passenger transport statist...
4,2016,Italy,Milano Centrale,Milano,Lombardia,Switzerland,Lugano,Lugano,Ticino,2.724,Long-distance,EU Commission - Reports on cross-border rail p...
...,...,...,...,...,...,...,...,...,...,...,...,...
139,2024,Germany,Berlin Hbf,Berlin,Berlin,Spain,Madrid Chamartín,Madrid,Comunidad de Madrid,0.891,Long-distance,Railway operators timetables and reports (Tren...
140,2024,Germany,Hamburg Hbf,Hamburg,Hamburg,Spain,Barcelona Sants,Barcelona,Cataluña,0.662,Long-distance,Railway operators timetables and reports (Tren...
141,2024,Germany,München Hbf,München,Bayern,Spain,Barcelona Sants,Barcelona,Cataluña,2.291,Long-distance,Railway operators timetables and reports (Tren...
142,2024,Switzerland,Zürich HB,Zürich,Zürich,Spain,Barcelona Sants,Barcelona,Cataluña,1.948,Long-distance,Railway operators timetables and reports (Tren...
143,2024,Switzerland,Genève,Genève,Genève,Spain,Barcelona Sants,Barcelona,Cataluña,2.775,Long-distance,EU Commission - Reports on cross-border rail p...

In [33]:
df.shape

(144, 12)

In [35]:
df=df.drop(columns=['source'])

In [36]:
df.columns

Index(['year', 'origin_country', 'origin_station_name', 'origin_city',
       'origin_region', 'destination_country', 'destination_station_name',
       'destination_city', 'destination_region', 'Passengers_millions',
       'Type'],
      dtype='object')

In [41]:
df=pd.read_csv('switzerland_rail_OD_flows.csv',sep=';')

In [42]:
df

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Genève,Winterthur,Genève,Winterthur,Genève,Zürich,1.638,Long-distance,SBB - Passenger frequency by station (used to ...
1,2016,Genève,Fribourg/Freiburg,Genève,Fribourg,Genève,Fribourg,2.083,Long-distance,Eurostat - Railway passenger transport statist...
2,2016,Lausanne,Zürich HB,Lausanne,Zürich,Vaud,Zürich,1.444,Long-distance,SBB Facts & Figures - Passenger transport (int...
3,2016,Lausanne,Fribourg/Freiburg,Lausanne,Fribourg,Vaud,Fribourg,0.639,Long-distance,SBB Facts & Figures - Passenger transport (int...
4,2016,Luzern,Lugano,Luzern,Lugano,Luzern,Ticino,1.649,Long-distance,SBB - Passenger frequency by station (used to ...
...,...,...,...,...,...,...,...,...,...,...
83,2024,Winterthur,Luzern,Winterthur,Luzern,Zürich,Luzern,3.155,Regional,SBB - Passenger frequency by station (used to ...
84,2024,Fribourg/Freiburg,Winterthur,Fribourg,Winterthur,Fribourg,Zürich,3.597,Regional,SBB - Passenger frequency by station (used to ...
85,2024,Lugano,Basel SBB,Lugano,Basel,Ticino,Basel-Stadt,0.905,Long-distance,SBB - Passenger frequency by station (used to ...
86,2024,Lugano,St. Gallen,Lugano,St. Gallen,Ticino,St. Gallen,1.519,Long-distance,Eurostat - Railway passenger transport statist...
87,2024,Lugano,Fribourg/Freiburg,Lugano,Fribourg,Ticino,Fribourg,4.870,Long-distance,SBB Facts & Figures - Passenger transport (int...

In [43]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type', 'source'],
      dtype='object')

In [44]:
df=df.drop(columns=['source'])

In [45]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type'],
      dtype='object')

In [46]:
df=pd.read_csv('france_rail_OD_flows.csv',sep=';')

In [47]:
df

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Paris Gare du Nord,Paris Gare de Lyon,Paris,Paris,Île-de-France,Île-de-France,1.05,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
1,2016,Paris Gare du Nord,Paris Saint-Lazare,Paris,Paris,Île-de-France,Île-de-France,1.13,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
2,2016,Paris Gare du Nord,Paris Montparnasse,Paris,Paris,Île-de-France,Île-de-France,0.88,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
3,2016,Paris Gare du Nord,Paris Est,Paris,Paris,Île-de-France,Île-de-France,0.93,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
4,2016,Paris Gare du Nord,Paris Austerlitz,Paris,Paris,Île-de-France,Île-de-France,0.89,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
...,...,...,...,...,...,...,...,...,...,...
2155,2024,Strasbourg,Lille Europe,Strasbourg,Lille,Grand Est,Hauts-de-France,0.92,TER/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
2156,2024,Strasbourg,Bordeaux Saint-Jean,Strasbourg,Bordeaux,Grand Est,Nouvelle-Aquitaine,1.17,TER/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
2157,2024,Strasbourg,Toulouse Matabiau,Strasbourg,Toulouse,Grand Est,Occitanie,0.98,TER/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
2158,2024,Strasbourg,Nantes,Strasbourg,Nantes,Grand Est,Pays de la Loire,1.24,TER/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
2159,2024,Strasbourg,Rennes,Strasbourg,Rennes,Grand Est,Bretagne,1.13,TER/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."

In [48]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type', 'source'],
      dtype='object')

In [49]:
df=df.drop(columns=['source'])

In [50]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type'],
      dtype='object')

In [62]:
import pandas as pd
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')

# ── Chemins (adapter si besoin) ──────────────────────────────────
DATA_DIR   = "."        # dossier contenant les CSV sources
OUTPUT_DIR = "./output" # dossier de sortie
os.makedirs(OUTPUT_DIR, exist_ok=True)

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 60)
print('✅ Prêt')

✅ Prêt

In [63]:
def load_csv(filename, sep=';'):
    """Charge un CSV et affiche un résumé rapide."""
    path = os.path.join(DATA_DIR, filename)
    df = pd.read_csv(path, sep=sep, encoding='utf-8-sig')
    print(f'📂  {filename:<50}  {df.shape[0]:>5} lignes | {df.shape[1]} colonnes')
    return df

print('Chargement des fichiers...\n')
df_co2        = load_csv('co2_comparaison_europe.csv')
df_france     = load_csv('france_rail_OD_flows.csv')
df_germany    = load_csv('germany_rail_OD_flows.csv')
df_italy      = load_csv('italy_rail_OD_flows.csv')
df_spain      = load_csv('spain_rail_OD_flows.csv')
df_switz      = load_csv('switzerland_rail_OD_flows.csv')
df_crossbord  = load_csv('cross_border_rail_OD_IT_DE_CH_ES.csv')
print('\n✅ Tous les fichiers chargés.')

Chargement des fichiers...

📂  co2_comparaison_europe.csv                              5 lignes | 7 colonnes
📂  france_rail_OD_flows.csv                             2160 lignes | 10 colonnes
📂  germany_rail_OD_flows.csv                             110 lignes | 10 colonnes
📂  italy_rail_OD_flows.csv                                95 lignes | 10 colonnes
📂  spain_rail_OD_flows.csv                                83 lignes | 10 colonnes
📂  switzerland_rail_OD_flows.csv                          88 lignes | 10 colonnes
📂  cross_border_rail_OD_IT_DE_CH_ES.csv                  144 lignes | 12 colonnes

✅ Tous les fichiers chargés.

In [64]:
print('=== CO2 ===')
display(df_co2)

print('\n=== Flux France (5 premières lignes) ===')
display(df_france.head())

print('\n=== Flux Allemagne (5 premières lignes) ===')
display(df_germany.head())

print('\n=== Flux cross-border (5 premières lignes) ===')
display(df_crossbord.head())

=== CO2 ===

,Pays,Emissions_Train_g_km,Emissions_Voiture_g_km,Emissions_Avion_g_km,CO2_evite_Train_vs_Voiture_g_km,CO2_evite_Train_vs_Avion_g_km,Reduction_Train_vs_Voiture_%
0,France,3.0,192,255,189.0,252.0,98.44
1,Suisse,1.5,180,255,178.5,253.5,99.17
2,Portugal,30.0,190,250,160.0,220.0,84.21
3,Allemagne,32.0,192,255,160.0,223.0,83.33
4,Italie,35.0,185,250,150.0,215.0,81.08

=== Flux France (5 premières lignes) ===

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Paris Gare du Nord,Paris Gare de Lyon,Paris,Paris,Île-de-France,Île-de-France,1.05,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF rapports a..."
1,2016,Paris Gare du Nord,Paris Saint-Lazare,Paris,Paris,Île-de-France,Île-de-France,1.13,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF rapports a..."
2,2016,Paris Gare du Nord,Paris Montparnasse,Paris,Paris,Île-de-France,Île-de-France,0.88,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF rapports a..."
3,2016,Paris Gare du Nord,Paris Est,Paris,Paris,Île-de-France,Île-de-France,0.93,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF rapports a..."
4,2016,Paris Gare du Nord,Paris Austerlitz,Paris,Paris,Île-de-France,Île-de-France,0.89,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF rapports a..."

=== Flux Allemagne (5 premières lignes) ===

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Berlin Hbf,Frankfurt (Main) Hbf,Berlin,Frankfurt am Main,Berlin,Hessen,2.539,Fernverkehr,Eurostat - Railway passenger transport statistics (used ...
1,2016,Berlin Hbf,Hannover Hbf,Berlin,Hannover,Berlin,Niedersachsen,1.098,Fernverkehr,Deutsche Bahn - Facts & Figures (long-distance and regio...
2,2016,Hamburg Hbf,Frankfurt (Main) Hbf,Hamburg,Frankfurt am Main,Hamburg,Hessen,2.493,Fernverkehr,Eurostat - Railway passenger transport statistics (used ...
3,2016,Hamburg Hbf,Köln Hbf,Hamburg,Köln,Hamburg,Nordrhein-Westfalen,0.848,Fernverkehr,VDV - Statistik zum SPNV in Deutschland (used for calibr...
4,2016,Hamburg Hbf,Leipzig Hbf,Hamburg,Leipzig,Hamburg,Sachsen,1.139,Fernverkehr,Deutsche Bahn - Facts & Figures (long-distance and regio...

=== Flux cross-border (5 premières lignes) ===

,year,origin_country,origin_station_name,origin_city,origin_region,destination_country,destination_station_name,destination_city,destination_region,Passengers_millions,Type,source
0,2016,Italy,Roma Termini,Roma,Lazio,Germany,München Hbf,München,Bayern,0.730,Long-distance,"Railway operators timetables and reports (Trenitalia, DB..."
1,2016,Italy,Milano Centrale,Milano,Lombardia,Germany,Frankfurt (Main) Hbf,Frankfurt am Main,Hessen,0.971,Long-distance,EU Commission - Reports on cross-border rail passenger s...
2,2016,Italy,Milano Centrale,Milano,Lombardia,Germany,Hamburg Hbf,Hamburg,Hamburg,2.723,Long-distance,"Railway operators timetables and reports (Trenitalia, DB..."
3,2016,Italy,Milano Centrale,Milano,Lombardia,Switzerland,Zürich HB,Zürich,Zürich,0.544,Long-distance,Eurostat - Railway passenger transport statistics (cross...
4,2016,Italy,Milano Centrale,Milano,Lombardia,Switzerland,Lugano,Lugano,Ticino,2.724,Long-distance,EU Commission - Reports on cross-border rail passenger s...

In [65]:
def transform_co2(df):
    df = df.copy()
    df.columns = [
        'country', 'emissions_train_g_km', 'emissions_car_g_km',
        'emissions_plane_g_km', 'co2_saved_vs_car_g_km',
        'co2_saved_vs_plane_g_km', 'reduction_vs_car_pct'
    ]
    df['country'] = df['country'].str.strip()
    num_cols = df.columns[1:]
    df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')
    print(f'✅ CO2 transformé : {df.shape}')
    return df

df_co2_clean = transform_co2(df_co2)
display(df_co2_clean)

✅ CO2 transformé : (5, 7)

,country,emissions_train_g_km,emissions_car_g_km,emissions_plane_g_km,co2_saved_vs_car_g_km,co2_saved_vs_plane_g_km,reduction_vs_car_pct
0,France,3.0,192,255,189.0,252.0,98.44
1,Suisse,1.5,180,255,178.5,253.5,99.17
2,Portugal,30.0,190,250,160.0,220.0,84.21
3,Allemagne,32.0,192,255,160.0,223.0,83.33
4,Italie,35.0,185,250,150.0,215.0,81.08

In [59]:
def transform_co2(df):
    df = df.copy()
    # Nettoyage des noms de colonnes
    df.columns = [
        'country', 'emissions_train_g_km', 'emissions_car_g_km',
        'emissions_plane_g_km', 'co2_saved_vs_car_g_km',
        'co2_saved_vs_plane_g_km', 'reduction_vs_car_pct'
    ]
    # Standardisation du nom de pays
    df['country'] = df['country'].str.strip()
    # S'assurer que les colonnes numériques sont bien float
    num_cols = df.columns[1:]
    df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')
    print(f'✅ CO2 transformé : {df.shape}')
    return df

df_co2_clean = transform_co2(df_co2)
display(df_co2_clean.head())

✅ CO2 transformé : (5, 7)

,country,emissions_train_g_km,emissions_car_g_km,emissions_plane_g_km,co2_saved_vs_car_g_km,co2_saved_vs_plane_g_km,reduction_vs_car_pct
0,France,3.0,192,255,189.0,252.0,98.44
1,Suisse,1.5,180,255,178.5,253.5,99.17
2,Portugal,30.0,190,250,160.0,220.0,84.21
3,Allemagne,32.0,192,255,160.0,223.0,83.33
4,Italie,35.0,185,250,150.0,215.0,81.08

In [66]:
# Mapping pays → (code ISO, label anglais, label CO2)
COUNTRY_MAP = {
    'france'      : ('FR', 'France',      'France'),
    'germany'     : ('DE', 'Germany',     'Allemagne'),
    'italy'       : ('IT', 'Italy',       'Italie'),
    'spain'       : ('ES', 'Spain',       'Espagne'),
    'switzerland' : ('CH', 'Switzerland', 'Suisse'),
}

# Colonnes standardisées communes aux 5 fichiers nationaux
NATIONAL_COLS = [
    'year', 'origin_station', 'destination_station',
    'origin_city', 'destination_city',
    'origin_region', 'destination_region',
    'passengers_millions', 'service_type', 'source'
]

def transform_od_national(df, country_key):
    """Nettoyage générique pour les flux OD nationaux."""
    df = df.copy()
    iso, label, _ = COUNTRY_MAP[country_key]

    df.columns = NATIONAL_COLS

    # Métadonnées pays
    df['country']     = label
    df['country_iso'] = iso
    df['flow_type']   = 'domestic'

    # Cast types
    df['year']               = pd.to_numeric(df['year'], errors='coerce').astype('Int64')
    df['passengers_millions'] = pd.to_numeric(df['passengers_millions'], errors='coerce')

    # Nettoyage textes
    text_cols = ['origin_station', 'destination_station',
                 'origin_city', 'destination_city',
                 'origin_region', 'destination_region']
    for col in text_cols:
        df[col] = df[col].str.strip()

    # Suppression doublons
    before = len(df)
    df.drop_duplicates(subset=['year', 'origin_station', 'destination_station'], inplace=True)
    removed = before - len(df)
    if removed:
        print(f'  ⚠️  {removed} doublon(s) supprimé(s) dans {label}')

    # Suppression lignes sans passagers
    df.dropna(subset=['passengers_millions'], inplace=True)

    print(f'✅ {label:<15} transformé : {df.shape[0]} lignes')
    return df

df_france_clean  = transform_od_national(df_france,  'france')
df_germany_clean = transform_od_national(df_germany, 'germany')
df_italy_clean   = transform_od_national(df_italy,   'italy')
df_spain_clean   = transform_od_national(df_spain,   'spain')
df_switz_clean   = transform_od_national(df_switz,   'switzerland')

✅ France          transformé : 2160 lignes
✅ Germany         transformé : 110 lignes
✅ Italy           transformé : 95 lignes
✅ Spain           transformé : 83 lignes
✅ Switzerland     transformé : 88 lignes

In [67]:
def transform_crossborder(df):
    df = df.copy()
    df.columns = [
        'year',
        'origin_country_iso', 'origin_station', 'origin_city', 'origin_region',
        'destination_country_iso', 'destination_station', 'destination_city', 'destination_region',
        'passengers_millions', 'service_type', 'source'
    ]
    df['flow_type'] = 'cross_border'

    df['year']                = pd.to_numeric(df['year'], errors='coerce').astype('Int64')
    df['passengers_millions'] = pd.to_numeric(df['passengers_millions'], errors='coerce')

    text_cols = ['origin_station', 'destination_station',
                 'origin_city', 'destination_city',
                 'origin_region', 'destination_region']
    for col in text_cols:
        df[col] = df[col].str.strip()

    # Normaliser les noms de pays ISO (ex: 'Italy' → 'IT')
    country_to_iso = {
        'France': 'FR', 'Germany': 'DE', 'Italy': 'IT',
        'Spain': 'ES', 'Switzerland': 'CH'
    }
    df['origin_country_iso']      = df['origin_country_iso'].map(country_to_iso).fillna(df['origin_country_iso'])
    df['destination_country_iso'] = df['destination_country_iso'].map(country_to_iso).fillna(df['destination_country_iso'])

    df.dropna(subset=['passengers_millions'], inplace=True)
    print(f'✅ Cross-border transformé : {df.shape[0]} lignes')
    return df

df_crossbord_clean = transform_crossborder(df_crossbord)
display(df_crossbord_clean.head())

✅ Cross-border transformé : 144 lignes

,year,origin_country_iso,origin_station,origin_city,origin_region,destination_country_iso,destination_station,destination_city,destination_region,passengers_millions,service_type,source,flow_type
0,2016,IT,Roma Termini,Roma,Lazio,DE,München Hbf,München,Bayern,0.730,Long-distance,"Railway operators timetables and reports (Trenitalia, DB...",cross_border
1,2016,IT,Milano Centrale,Milano,Lombardia,DE,Frankfurt (Main) Hbf,Frankfurt am Main,Hessen,0.971,Long-distance,EU Commission - Reports on cross-border rail passenger s...,cross_border
2,2016,IT,Milano Centrale,Milano,Lombardia,DE,Hamburg Hbf,Hamburg,Hamburg,2.723,Long-distance,"Railway operators timetables and reports (Trenitalia, DB...",cross_border
3,2016,IT,Milano Centrale,Milano,Lombardia,CH,Zürich HB,Zürich,Zürich,0.544,Long-distance,Eurostat - Railway passenger transport statistics (cross...,cross_border
4,2016,IT,Milano Centrale,Milano,Lombardia,CH,Lugano,Lugano,Ticino,2.724,Long-distance,EU Commission - Reports on cross-border rail passenger s...,cross_border

In [68]:
# Schéma commun minimal pour le concat
COMMON_COLS = [
    'year', 'origin_station', 'destination_station',
    'origin_city', 'destination_city',
    'origin_region', 'destination_region',
    'passengers_millions', 'service_type', 'flow_type', 'source'
]

# Flux nationaux : on ajoute origin/destination_country_iso identiques
national_frames = []
for df, iso in [
    (df_france_clean,  'FR'),
    (df_germany_clean, 'DE'),
    (df_italy_clean,   'IT'),
    (df_spain_clean,   'ES'),
    (df_switz_clean,   'CH'),
]:
    tmp = df[COMMON_COLS].copy()
    tmp['origin_country_iso']      = iso
    tmp['destination_country_iso'] = iso
    national_frames.append(tmp)

# Flux cross-border
cb = df_crossbord_clean[COMMON_COLS + ['origin_country_iso', 'destination_country_iso']].copy()

# Concatenation
df_all_od = pd.concat(national_frames + [cb], ignore_index=True)

print(f'✅ Table OD consolidée : {df_all_od.shape[0]:,} lignes | {df_all_od.shape[1]} colonnes')
display(df_all_od.sample(5, random_state=42))

✅ Table OD consolidée : 2,680 lignes | 13 colonnes

,year,origin_station,destination_station,origin_city,destination_city,origin_region,destination_region,passengers_millions,service_type,flow_type,source,origin_country_iso,destination_country_iso
1064,2020,Lyon Part-Dieu,Strasbourg,Lyon,Strasbourg,Auvergne-Rhône-Alpes,Grand Est,0.43,TER/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR
1674,2022,Strasbourg,Lille Flandres,Strasbourg,Lille,Grand Est,Hauts-de-France,0.95,TER/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR
2021,2024,Lyon Part-Dieu,Toulouse Matabiau,Lyon,Toulouse,Auvergne-Rhône-Alpes,Occitanie,1.15,TER/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR
759,2019,Paris Saint-Lazare,Lille Europe,Paris,Lille,Île-de-France,Hauts-de-France,6.79,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR
211,2016,Rennes,Paris Gare de Lyon,Rennes,Paris,Bretagne,Île-de-France,4.20,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR

In [69]:
# Mapping ISO → nom dans la table CO2 (noms en français)
ISO_TO_CO2_COUNTRY = {
    'FR': 'France',
    'DE': 'Allemagne',
    'IT': 'Italie',
    'ES': 'Espagne',
    'CH': 'Suisse',
}

df_all_od['co2_country_key'] = df_all_od['origin_country_iso'].map(ISO_TO_CO2_COUNTRY)

df_enriched = df_all_od.merge(
    df_co2_clean[['country', 'emissions_train_g_km', 'emissions_car_g_km',
                  'co2_saved_vs_car_g_km', 'reduction_vs_car_pct']],
    left_on='co2_country_key',
    right_on='country',
    how='left'
).drop(columns=['country', 'co2_country_key'])

print(f'✅ Table enrichie : {df_enriched.shape}')
print(f"   Taux de match CO2 : {df_enriched['emissions_train_g_km'].notna().mean():.1%}")
display(df_enriched.head())

✅ Table enrichie : (2680, 17)
   Taux de match CO2 : 96.9%

,year,origin_station,destination_station,origin_city,destination_city,origin_region,destination_region,passengers_millions,service_type,flow_type,source,origin_country_iso,destination_country_iso,emissions_train_g_km,emissions_car_g_km,co2_saved_vs_car_g_km,reduction_vs_car_pct
0,2016,Paris Gare du Nord,Paris Gare de Lyon,Paris,Paris,Île-de-France,Île-de-France,1.05,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR,3.0,192.0,189.0,98.44
1,2016,Paris Gare du Nord,Paris Saint-Lazare,Paris,Paris,Île-de-France,Île-de-France,1.13,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR,3.0,192.0,189.0,98.44
2,2016,Paris Gare du Nord,Paris Montparnasse,Paris,Paris,Île-de-France,Île-de-France,0.88,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR,3.0,192.0,189.0,98.44
3,2016,Paris Gare du Nord,Paris Est,Paris,Paris,Île-de-France,Île-de-France,0.93,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR,3.0,192.0,189.0,98.44
4,2016,Paris Gare du Nord,Paris Austerlitz,Paris,Paris,Île-de-France,Île-de-France,0.89,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR,3.0,192.0,189.0,98.44

In [70]:
print('=== Répartition par pays et type de flux ===')
display(
    df_enriched.groupby(['origin_country_iso', 'flow_type'])
               .agg(
                   nb_routes          = ('passengers_millions', 'count'),
                   total_passengers_M = ('passengers_millions', 'sum'),
               )
               .round(2)
               .reset_index()
               .sort_values('total_passengers_M', ascending=False)
)

=== Répartition par pays et type de flux ===

  origin_country_iso     flow_type  nb_routes  total_passengers_M
5                 FR      domestic       2160             6764.81
3                 DE      domestic        110              291.97
7                 IT      domestic         95              288.42
4                 ES      domestic         83              259.88
1                 CH      domestic         88              252.48
6                 IT  cross_border         72              115.82
2                 DE  cross_border         54               95.74
0                 CH  cross_border         18               31.31

In [71]:
print('=== Top 10 des routes les plus fréquentées ===')
top10 = (
    df_enriched
    .groupby(['origin_country_iso', 'origin_city', 'destination_city'])
    ['passengers_millions'].sum()
    .reset_index()
    .sort_values('passengers_millions', ascending=False)
    .head(10)
)
display(top10)

=== Top 10 des routes les plus fréquentées ===

    origin_country_iso origin_city destination_city  passengers_millions
204                 FR        Lyon            Paris               813.68
226                 FR       Paris             Lyon               805.06
225                 FR       Paris            Lille               708.41
195                 FR       Lille            Paris               704.18
227                 FR       Paris        Marseille               308.16
212                 FR   Marseille            Paris               306.82
224                 FR       Paris         Bordeaux               254.82
229                 FR       Paris            Paris               251.49
186                 FR    Bordeaux            Paris               249.36
230                 FR       Paris           Rennes               203.24

In [72]:
print('=== Évolution totale par année ===')
display(
    df_enriched.groupby('year')
               .agg(
                   nb_routes          = ('passengers_millions', 'count'),
                   total_passengers_M = ('passengers_millions', 'sum'),
               )
               .round(2)
)

=== Évolution totale par année ===

      nb_routes  total_passengers_M
year
2016        308              982.45
2017        299              935.11
2018        299              969.79
2019        295              962.78
2020        290              449.97
2021        303              755.12
2022        283              940.80
2023        300             1039.52
2024        303             1064.88

In [73]:
print('=== Comparatif CO₂ par pays (train vs voiture) ===')
display(df_co2_clean[['country', 'emissions_train_g_km', 'emissions_car_g_km',
                       'reduction_vs_car_pct']].sort_values('emissions_train_g_km'))

=== Comparatif CO₂ par pays (train vs voiture) ===

     country  emissions_train_g_km  emissions_car_g_km  reduction_vs_car_pct
1     Suisse                   1.5                 180                 99.17
0     France                   3.0                 192                 98.44
2   Portugal                  30.0                 190                 84.21
3  Allemagne                  32.0                 192                 83.33
4     Italie                  35.0                 185                 81.08

In [74]:
# ── Table 1 : flux OD enrichis (table principale) ────────────────
out_od = os.path.join(OUTPUT_DIR, 'od_flows_enriched.csv')
df_enriched.to_csv(out_od, index=False, sep=';', encoding='utf-8-sig')
print(f'💾 od_flows_enriched.csv     → {len(df_enriched):,} lignes')

# ── Table 2 : CO2 nettoyé ─────────────────────────────────────────
out_co2 = os.path.join(OUTPUT_DIR, 'co2_clean.csv')
df_co2_clean.to_csv(out_co2, index=False, sep=';', encoding='utf-8-sig')
print(f'💾 co2_clean.csv             → {len(df_co2_clean):,} lignes')

# ── Table 3 : agrégat par pays/année/type ─────────────────────────
df_agg = (
    df_enriched
    .groupby(['year', 'origin_country_iso', 'flow_type'])
    .agg(
        nb_routes          = ('passengers_millions', 'count'),
        total_passengers_M = ('passengers_millions', 'sum'),
        avg_passengers_M   = ('passengers_millions', 'mean'),
        max_route_M        = ('passengers_millions', 'max'),
    )
    .round(3)
    .reset_index()
)
out_agg = os.path.join(OUTPUT_DIR, 'od_aggregated.csv')
df_agg.to_csv(out_agg, index=False, sep=';', encoding='utf-8-sig')
print(f'💾 od_aggregated.csv         → {len(df_agg):,} lignes')

print(f'\n✅ Export terminé — dossier : {os.path.abspath(OUTPUT_DIR)}')

💾 od_flows_enriched.csv     → 2,680 lignes
💾 co2_clean.csv             → 5 lignes
💾 od_aggregated.csv         → 72 lignes

✅ Export terminé — dossier : c:\Users\scott\Desktop\epsi\github\MsprDS\csv\output

In [75]:
import pandas as pd
import sqlite3
import os

# ── Chemins (adapter si besoin) ──────────────────────────────────
OUTPUT_DIR = "./output"                        # dossier des CSV produits par l'ETL
DB_PATH    = "./rail_europe.db"                # fichier SQLite à créer

print(f'📁 Dossier CSV  : {os.path.abspath(OUTPUT_DIR)}')
print(f'🗄️  Base SQLite  : {os.path.abspath(DB_PATH)}')
print('✅ Prêt')

📁 Dossier CSV  : c:\Users\scott\Desktop\epsi\github\MsprDS\csv\output
🗄️  Base SQLite  : c:\Users\scott\Desktop\epsi\github\MsprDS\csv\rail_europe.db
✅ Prêt

In [76]:
def read_csv(filename):
    path = os.path.join(OUTPUT_DIR, filename)
    df = pd.read_csv(path, sep=';', encoding='utf-8-sig')
    print(f'📂  {filename:<35}  {df.shape[0]:>5} lignes | {df.shape[1]} colonnes')
    return df

df_od  = read_csv('od_flows_enriched.csv')
df_co2 = read_csv('co2_clean.csv')
df_agg = read_csv('od_aggregated.csv')
print('\n✅ CSV chargés en mémoire.')

📂  od_flows_enriched.csv                 2680 lignes | 17 colonnes
📂  co2_clean.csv                            5 lignes | 7 colonnes
📂  od_aggregated.csv                       72 lignes | 7 colonnes

✅ CSV chargés en mémoire.

In [77]:
# Connexion (crée le fichier s'il n'existe pas)
con = sqlite3.connect(DB_PATH)
print(f'🔌 Connexion ouverte → {DB_PATH}')

# ── Schémas DDL explicites ────────────────────────────────────────
DDL = """
-- Table principale : flux OD enrichis
CREATE TABLE IF NOT EXISTS od_flows_enriched (
    id                       INTEGER PRIMARY KEY AUTOINCREMENT,
    year                     INTEGER,
    origin_station           TEXT,
    destination_station      TEXT,
    origin_city              TEXT,
    destination_city         TEXT,
    origin_region            TEXT,
    destination_region       TEXT,
    passengers_millions      REAL,
    service_type             TEXT,
    flow_type                TEXT,
    source                   TEXT,
    origin_country_iso       TEXT,
    destination_country_iso  TEXT,
    emissions_train_g_km     REAL,
    emissions_car_g_km       REAL,
    co2_saved_vs_car_g_km    REAL,
    reduction_vs_car_pct     REAL
);

-- Table CO2 par pays
CREATE TABLE IF NOT EXISTS co2_clean (
    id                       INTEGER PRIMARY KEY AUTOINCREMENT,
    country                  TEXT,
    emissions_train_g_km     REAL,
    emissions_car_g_km       REAL,
    emissions_plane_g_km     REAL,
    co2_saved_vs_car_g_km    REAL,
    co2_saved_vs_plane_g_km  REAL,
    reduction_vs_car_pct     REAL
);

-- Table agrégat par pays/année/type
CREATE TABLE IF NOT EXISTS od_aggregated (
    id                     INTEGER PRIMARY KEY AUTOINCREMENT,
    year                   INTEGER,
    origin_country_iso     TEXT,
    flow_type              TEXT,
    nb_routes              INTEGER,
    total_passengers_M     REAL,
    avg_passengers_M       REAL,
    max_route_M            REAL
);
"""

con.executescript(DDL)
con.commit()
print('✅ Tables créées (ou déjà existantes).')

🔌 Connexion ouverte → ./rail_europe.db
✅ Tables créées (ou déjà existantes).

In [78]:
# ── Insertion des données ─────────────────────────────────────────
# if_exists='replace' : vide et recrée la table à chaque exécution
# Utiliser 'append' si tu veux cumuler des runs

tables = {
    'od_flows_enriched' : df_od,
    'co2_clean'         : df_co2,
    'od_aggregated'     : df_agg,
}

for table_name, df in tables.items():
    df.to_sql(table_name, con, if_exists='replace', index=False)
    # Vérification du nombre de lignes insérées
    count = con.execute(f'SELECT COUNT(*) FROM {table_name}').fetchone()[0]
    print(f'✅ {table_name:<25} → {count:>5} lignes insérées')

con.commit()
print('\n💾 Toutes les tables sont chargées.')

✅ od_flows_enriched         →  2680 lignes insérées
✅ co2_clean                 →     5 lignes insérées
✅ od_aggregated             →    72 lignes insérées

💾 Toutes les tables sont chargées.

In [79]:
INDEXES = """
CREATE INDEX IF NOT EXISTS idx_od_country_year
    ON od_flows_enriched (origin_country_iso, year);

CREATE INDEX IF NOT EXISTS idx_od_flow_type
    ON od_flows_enriched (flow_type);

CREATE INDEX IF NOT EXISTS idx_od_cities
    ON od_flows_enriched (origin_city, destination_city);

CREATE INDEX IF NOT EXISTS idx_agg_country_year
    ON od_aggregated (origin_country_iso, year);
"""

con.executescript(INDEXES)
con.commit()
print('✅ Index créés.')

✅ Index créés.

In [80]:
# Vue d'ensemble de la base
tables_in_db = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", con)
print('Tables dans la base :', tables_in_db['name'].tolist())

print('\n=== Taille du fichier SQLite ===')
size_kb = os.path.getsize(DB_PATH) / 1024
print(f'📦 {DB_PATH} : {size_kb:.1f} Ko')

Tables dans la base : ['sqlite_sequence', 'od_flows_enriched', 'co2_clean', 'od_aggregated']

=== Taille du fichier SQLite ===
📦 ./rail_europe.db : 876.0 Ko

In [81]:
# Requête 1 : Top 10 routes les plus fréquentées
q1 = """
SELECT
    origin_country_iso,
    origin_city,
    destination_city,
    ROUND(SUM(passengers_millions), 2) AS total_pax_M
FROM od_flows_enriched
GROUP BY origin_country_iso, origin_city, destination_city
ORDER BY total_pax_M DESC
LIMIT 10;
"""
print('=== Top 10 routes ===')
display(pd.read_sql(q1, con))

=== Top 10 routes ===

  origin_country_iso origin_city destination_city  total_pax_M
0                 FR        Lyon            Paris       813.68
1                 FR       Paris             Lyon       805.06
2                 FR       Paris            Lille       708.41
3                 FR       Lille            Paris       704.18
4                 FR       Paris        Marseille       308.16
5                 FR   Marseille            Paris       306.82
6                 FR       Paris         Bordeaux       254.82
7                 FR       Paris            Paris       251.49
8                 FR    Bordeaux            Paris       249.36
9                 FR       Paris           Rennes       203.24

In [82]:
# Requête 2 : Passagers totaux par pays et type de flux
q2 = """
SELECT
    origin_country_iso AS pays,
    flow_type,
    COUNT(*)                              AS nb_routes,
    ROUND(SUM(passengers_millions), 2)    AS total_pax_M
FROM od_flows_enriched
GROUP BY pays, flow_type
ORDER BY total_pax_M DESC;
"""
print('=== Passagers par pays / type ===')
display(pd.read_sql(q2, con))

=== Passagers par pays / type ===

  pays     flow_type  nb_routes  total_pax_M
0   FR      domestic       2160      6764.81
1   DE      domestic        110       291.97
2   IT      domestic         95       288.42
3   ES      domestic         83       259.88
4   CH      domestic         88       252.48
5   IT  cross_border         72       115.82
6   DE  cross_border         54        95.74
7   CH  cross_border         18        31.31

In [83]:
# Requête 3 : Émissions CO2 et économies par pays
q3 = """
SELECT
    country,
    emissions_train_g_km,
    emissions_car_g_km,
    co2_saved_vs_car_g_km,
    reduction_vs_car_pct
FROM co2_clean
ORDER BY emissions_train_g_km ASC;
"""
print('=== CO₂ — train vs voiture ===')
display(pd.read_sql(q3, con))

=== CO₂ — train vs voiture ===

,country,emissions_train_g_km,emissions_car_g_km,co2_saved_vs_car_g_km,reduction_vs_car_pct
0,Suisse,1.5,180,178.5,99.17
1,France,3.0,192,189.0,98.44
2,Portugal,30.0,190,160.0,84.21
3,Allemagne,32.0,192,160.0,83.33
4,Italie,35.0,185,150.0,81.08

In [84]:
# Requête 4 : Évolution annuelle (jointure od_flows + co2)
q4 = """
SELECT
    o.year,
    o.origin_country_iso AS pays,
    ROUND(SUM(o.passengers_millions), 2)          AS total_pax_M,
    MAX(o.emissions_train_g_km)                   AS co2_train_g_km,
    ROUND(SUM(o.passengers_millions)
          * MAX(o.co2_saved_vs_car_g_km), 0)       AS co2_economise_total_g
FROM od_flows_enriched o
WHERE o.flow_type = 'domestic'
GROUP BY o.year, o.origin_country_iso
ORDER BY o.year, pays;
"""
print('=== Évolution annuelle + CO₂ économisé (domestic) ===')
display(pd.read_sql(q4, con))

=== Évolution annuelle + CO₂ économisé (domestic) ===

    year pays  total_pax_M  co2_train_g_km  co2_economise_total_g
0   2016   CH        19.87             1.5                 3547.0
1   2016   DE        47.62            32.0                 7619.0
2   2016   ES        36.74             NaN                    NaN
3   2016   FR       815.19             3.0               154071.0
4   2016   IT        40.04            35.0                 6006.0
5   2017   CH        32.04             1.5                 5719.0
6   2017   DE        22.47            32.0                 3595.0
7   2017   ES        22.63             NaN                    NaN
8   2017   FR       805.27             3.0               152196.0
9   2017   IT        28.69            35.0                 4303.0
10  2018   CH        33.26             1.5                 5938.0
11  2018   DE        24.24            32.0                 3878.0
12  2018   ES        33.53             NaN                    NaN
13  2018   FR       821.04             3.0               155177.0
14  2018   IT        29.59            35.0                 4439.0
15  2019   CH        34.67             1.5                 6189.0
16  2019   DE        26.50            32.0                 4241.0
17  2019   ES        21.73             NaN                    NaN
18  2019   FR       820.54             3.0               155082.0
19  2019   IT        32.69            35.0                 4904.0
20  2020   CH        18.27             1.5                 3262.0
21  2020   DE        30.15            32.0                 4823.0
22  2020   ES        11.61             NaN                    NaN
23  2020   FR       334.51             3.0                63222.0
24  2020   IT        28.72            35.0                 4308.0
25  2021   CH        32.77             1.5                 5849.0
26  2021   DE        38.43            32.0                 6149.0
27  2021   ES        29.55             NaN                    NaN
28  2021   FR       590.72             3.0               111646.0
29  2021   IT        43.40            35.0                 6510.0
30  2022   CH        12.57             1.5                 2245.0
31  2022   DE        11.83            32.0                 1893.0
32  2022   ES        17.29             NaN                    NaN
33  2022   FR       847.76             3.0               160227.0
34  2022   IT        20.30            35.0                 3046.0
35  2023   CH        22.82             1.5                 4074.0
36  2023   DE        47.18            32.0                 7548.0
37  2023   ES        35.42             NaN                    NaN
38  2023   FR       863.17             3.0               163139.0
39  2023   IT        38.03            35.0                 5704.0
40  2024   CH        46.20             1.5                 8246.0
41  2024   DE        43.56            32.0                 6969.0
42  2024   ES        51.39             NaN                    NaN
43  2024   FR       866.61             3.0               163789.0
44  2024   IT        26.95            35.0                 4043.0

In [85]:
con.close()
print(f'🔒 Connexion fermée.')
print(f'\n✅ Base de données prête : {os.path.abspath(DB_PATH)}')
print('   → Ouvrir avec DB Browser for SQLite, DBeaver, ou tout autre client SQLite.')

🔒 Connexion fermée.

✅ Base de données prête : c:\Users\scott\Desktop\epsi\github\MsprDS\csv\rail_europe.db
   → Ouvrir avec DB Browser for SQLite, DBeaver, ou tout autre client SQLite.