In [6]:
import pandas as pd 
df=pd.read_csv('spain_rail_OD_flows.csv',sep=';')

In [7]:
df

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Madrid Puerta de Atocha,Barcelona Sants,Madrid,Barcelona,Comunidad de Madrid,Cataluña,10.439,Larga Distancia / AVE,Eurostat - Railway passenger transport statist...
1,2016,Madrid Puerta de Atocha,Málaga María Zambrano,Madrid,Málaga,Comunidad de Madrid,Andalucía,3.071,Larga Distancia / AVE,ADIF - Estadísticas de tráfico ferroviario por...
2,2016,Madrid Puerta de Atocha,Zaragoza Delicias,Madrid,Zaragoza,Comunidad de Madrid,Aragón,1.498,Larga Distancia / AVE,Renfe Viajeros - Informes de gestión (viajeros...
3,2016,Madrid Chamartín,Zaragoza Delicias,Madrid,Zaragoza,Comunidad de Madrid,Aragón,0.777,Larga Distancia / AVE,Renfe Viajeros - Informes de gestión (viajeros...
4,2016,Madrid Chamartín,Valladolid Campo Grande,Madrid,Valladolid,Comunidad de Madrid,Castilla y León,2.993,Larga Distancia / AVE,ADIF - Estadísticas de tráfico ferroviario por...
...,...,...,...,...,...,...,...,...,...,...
78,2024,Sevilla Santa Justa,Madrid Puerta de Atocha,Sevilla,Madrid,Andalucía,Comunidad de Madrid,4.196,Larga Distancia / AVE,Eurostat - Railway passenger transport statist...
79,2024,Sevilla Santa Justa,Barcelona Sants,Sevilla,Barcelona,Andalucía,Cataluña,2.122,Larga Distancia / AVE,Eurostat - Railway passenger transport statist...
80,2024,Zaragoza Delicias,Valencia Joaquín Sorolla,Zaragoza,Valencia,Aragón,Comunidad Valenciana,0.681,Larga Distancia / AVE,ADIF - Estadísticas de tráfico ferroviario por...
81,2024,Bilbao-Abando Indalecio Prieto,Madrid Chamartín,Bilbao,Madrid,País Vasco,Comunidad de Madrid,5.142,Larga Distancia,Eurostat - Railway passenger transport statist...
82,2024,Valladolid Campo Grande,Málaga María Zambrano,Valladolid,Málaga,Castilla y León,Andalucía,1.217,Larga Distancia,ADIF - Estadísticas de tráfico ferroviario por...

In [8]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type', 'source'],
      dtype='object')

In [9]:
df.shape

(83, 10)

In [10]:
df.isnull().sum()

year                        0
origin_station_name         0
destination_station_name    0
origin_city                 0
destination_city            0
origin_region               0
destination_region          0
Passengers_millions         0
Type                        0
source                      0
dtype: int64

In [11]:
df.isnull().mean()

year                        0.0
origin_station_name         0.0
destination_station_name    0.0
origin_city                 0.0
destination_city            0.0
origin_region               0.0
destination_region          0.0
Passengers_millions         0.0
Type                        0.0
source                      0.0
dtype: float64

In [12]:
df.dtypes

year                          int64
origin_station_name          object
destination_station_name     object
origin_city                  object
destination_city             object
origin_region                object
destination_region           object
Passengers_millions         float64
Type                         object
source                       object
dtype: object

In [15]:
df=df.drop(columns=['source'])

In [16]:
df

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type
0,2016,Madrid Puerta de Atocha,Barcelona Sants,Madrid,Barcelona,Comunidad de Madrid,Cataluña,10.439,Larga Distancia / AVE
1,2016,Madrid Puerta de Atocha,Málaga María Zambrano,Madrid,Málaga,Comunidad de Madrid,Andalucía,3.071,Larga Distancia / AVE
2,2016,Madrid Puerta de Atocha,Zaragoza Delicias,Madrid,Zaragoza,Comunidad de Madrid,Aragón,1.498,Larga Distancia / AVE
3,2016,Madrid Chamartín,Zaragoza Delicias,Madrid,Zaragoza,Comunidad de Madrid,Aragón,0.777,Larga Distancia / AVE
4,2016,Madrid Chamartín,Valladolid Campo Grande,Madrid,Valladolid,Comunidad de Madrid,Castilla y León,2.993,Larga Distancia / AVE
...,...,...,...,...,...,...,...,...,...
78,2024,Sevilla Santa Justa,Madrid Puerta de Atocha,Sevilla,Madrid,Andalucía,Comunidad de Madrid,4.196,Larga Distancia / AVE
79,2024,Sevilla Santa Justa,Barcelona Sants,Sevilla,Barcelona,Andalucía,Cataluña,2.122,Larga Distancia / AVE
80,2024,Zaragoza Delicias,Valencia Joaquín Sorolla,Zaragoza,Valencia,Aragón,Comunidad Valenciana,0.681,Larga Distancia / AVE
81,2024,Bilbao-Abando Indalecio Prieto,Madrid Chamartín,Bilbao,Madrid,País Vasco,Comunidad de Madrid,5.142,Larga Distancia
82,2024,Valladolid Campo Grande,Málaga María Zambrano,Valladolid,Málaga,Castilla y León,Andalucía,1.217,Larga Distancia

In [17]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type'],
      dtype='object')

In [18]:
df=pd.read_csv('germany_rail_OD_flows.csv',sep=';')

In [19]:
df

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Berlin Hbf,Frankfurt (Main) Hbf,Berlin,Frankfurt am Main,Berlin,Hessen,2.539,Fernverkehr,Eurostat - Railway passenger transport statist...
1,2016,Berlin Hbf,Hannover Hbf,Berlin,Hannover,Berlin,Niedersachsen,1.098,Fernverkehr,Deutsche Bahn - Facts & Figures (long-distance...
2,2016,Hamburg Hbf,Frankfurt (Main) Hbf,Hamburg,Frankfurt am Main,Hamburg,Hessen,2.493,Fernverkehr,Eurostat - Railway passenger transport statist...
3,2016,Hamburg Hbf,Köln Hbf,Hamburg,Köln,Hamburg,Nordrhein-Westfalen,0.848,Fernverkehr,VDV - Statistik zum SPNV in Deutschland (used ...
4,2016,Hamburg Hbf,Leipzig Hbf,Hamburg,Leipzig,Hamburg,Sachsen,1.139,Fernverkehr,Deutsche Bahn - Facts & Figures (long-distance...
...,...,...,...,...,...,...,...,...,...,...
105,2024,Köln Hbf,Frankfurt (Main) Hbf,Köln,Frankfurt am Main,Nordrhein-Westfalen,Hessen,12.912,Fernverkehr,Eurostat - Railway passenger transport statist...
106,2024,Düsseldorf Hbf,Hannover Hbf,Düsseldorf,Hannover,Nordrhein-Westfalen,Niedersachsen,0.898,Fernverkehr,Eurostat - Railway passenger transport statist...
107,2024,Leipzig Hbf,Berlin Hbf,Leipzig,Berlin,Sachsen,Berlin,1.893,Fernverkehr,VDV - Statistik zum SPNV in Deutschland (used ...
108,2024,Hannover Hbf,Köln Hbf,Hannover,Köln,Niedersachsen,Nordrhein-Westfalen,2.237,Fernverkehr,Deutsche Bahn - Facts & Figures (long-distance...
109,2024,Hannover Hbf,Düsseldorf Hbf,Hannover,Düsseldorf,Niedersachsen,Nordrhein-Westfalen,0.793,Fernverkehr,Deutsche Bahn - Facts & Figures (long-distance...

In [20]:
df=df.drop(columns=['source'])

In [21]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type'],
      dtype='object')

In [22]:
df=pd.read_csv('italy_rail_OD_flows.csv',sep=';')

In [23]:
df

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Milano Centrale,Napoli Centrale,Milano,Napoli,Lombardia,Campania,5.730,Alta Velocita,FS Research Centre - Methodological aspects fo...
1,2016,Milano Centrale,Torino Porta Nuova,Milano,Torino,Lombardia,Piemonte,9.118,Alta Velocita,Eurostat - Railway passenger transport statist...
2,2016,Milano Centrale,Venezia Santa Lucia,Milano,Venezia,Lombardia,Veneto,3.384,Alta Velocita,FS Italiane - Studi e ricerche sulla mobilità ...
3,2016,Napoli Centrale,Roma Termini,Napoli,Roma,Campania,Lazio,3.396,Alta Velocita,FS Research Centre - Methodological aspects fo...
4,2016,Torino Porta Nuova,Bari Centrale,Torino,Bari,Piemonte,Puglia,4.304,Intercity,FS Research Centre - Methodological aspects fo...
...,...,...,...,...,...,...,...,...,...,...
90,2024,Bologna Centrale,Roma Termini,Bologna,Roma,Emilia-Romagna,Lazio,4.484,Alta Velocita,FS Italiane - Studi e ricerche sulla mobilità ...
91,2024,Firenze S. M. Novella,Milano Centrale,Firenze,Milano,Toscana,Lombardia,3.657,Alta Velocita,FS Italiane - Studi e ricerche sulla mobilità ...
92,2024,Firenze S. M. Novella,Bologna Centrale,Firenze,Bologna,Toscana,Emilia-Romagna,2.543,Alta Velocita,Eurostat - Railway passenger transport statist...
93,2024,Bari Centrale,Venezia Santa Lucia,Bari,Venezia,Puglia,Veneto,3.690,Regionale,Eurostat - Railway passenger transport statist...
94,2024,Bari Centrale,Palermo Centrale,Bari,Palermo,Puglia,Sicilia,3.375,Regionale,FS Research Centre - Methodological aspects fo...

In [25]:
df=df.drop(columns=['source'])

In [26]:
df.shape

(95, 9)

In [27]:
df=pd.read_csv('switzerland_rail_OD_flows.csv',sep=';')

In [28]:
df

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Genève,Winterthur,Genève,Winterthur,Genève,Zürich,1.638,Long-distance,SBB - Passenger frequency by station (used to ...
1,2016,Genève,Fribourg/Freiburg,Genève,Fribourg,Genève,Fribourg,2.083,Long-distance,Eurostat - Railway passenger transport statist...
2,2016,Lausanne,Zürich HB,Lausanne,Zürich,Vaud,Zürich,1.444,Long-distance,SBB Facts & Figures - Passenger transport (int...
3,2016,Lausanne,Fribourg/Freiburg,Lausanne,Fribourg,Vaud,Fribourg,0.639,Long-distance,SBB Facts & Figures - Passenger transport (int...
4,2016,Luzern,Lugano,Luzern,Lugano,Luzern,Ticino,1.649,Long-distance,SBB - Passenger frequency by station (used to ...
...,...,...,...,...,...,...,...,...,...,...
83,2024,Winterthur,Luzern,Winterthur,Luzern,Zürich,Luzern,3.155,Regional,SBB - Passenger frequency by station (used to ...
84,2024,Fribourg/Freiburg,Winterthur,Fribourg,Winterthur,Fribourg,Zürich,3.597,Regional,SBB - Passenger frequency by station (used to ...
85,2024,Lugano,Basel SBB,Lugano,Basel,Ticino,Basel-Stadt,0.905,Long-distance,SBB - Passenger frequency by station (used to ...
86,2024,Lugano,St. Gallen,Lugano,St. Gallen,Ticino,St. Gallen,1.519,Long-distance,Eurostat - Railway passenger transport statist...
87,2024,Lugano,Fribourg/Freiburg,Lugano,Fribourg,Ticino,Fribourg,4.870,Long-distance,SBB Facts & Figures - Passenger transport (int...

In [29]:
df=df.drop(columns=['source'])

In [30]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type'],
      dtype='object')

In [31]:
df=pd.read_csv('cross_border_rail_OD_IT_DE_CH_ES.csv',sep=';')

In [32]:
df

,year,origin_country,origin_station_name,origin_city,origin_region,destination_country,destination_station_name,destination_city,destination_region,Passengers_millions,Type,source
0,2016,Italy,Roma Termini,Roma,Lazio,Germany,München Hbf,München,Bayern,0.730,Long-distance,Railway operators timetables and reports (Tren...
1,2016,Italy,Milano Centrale,Milano,Lombardia,Germany,Frankfurt (Main) Hbf,Frankfurt am Main,Hessen,0.971,Long-distance,EU Commission - Reports on cross-border rail p...
2,2016,Italy,Milano Centrale,Milano,Lombardia,Germany,Hamburg Hbf,Hamburg,Hamburg,2.723,Long-distance,Railway operators timetables and reports (Tren...
3,2016,Italy,Milano Centrale,Milano,Lombardia,Switzerland,Zürich HB,Zürich,Zürich,0.544,Long-distance,Eurostat - Railway passenger transport statist...
4,2016,Italy,Milano Centrale,Milano,Lombardia,Switzerland,Lugano,Lugano,Ticino,2.724,Long-distance,EU Commission - Reports on cross-border rail p...
...,...,...,...,...,...,...,...,...,...,...,...,...
139,2024,Germany,Berlin Hbf,Berlin,Berlin,Spain,Madrid Chamartín,Madrid,Comunidad de Madrid,0.891,Long-distance,Railway operators timetables and reports (Tren...
140,2024,Germany,Hamburg Hbf,Hamburg,Hamburg,Spain,Barcelona Sants,Barcelona,Cataluña,0.662,Long-distance,Railway operators timetables and reports (Tren...
141,2024,Germany,München Hbf,München,Bayern,Spain,Barcelona Sants,Barcelona,Cataluña,2.291,Long-distance,Railway operators timetables and reports (Tren...
142,2024,Switzerland,Zürich HB,Zürich,Zürich,Spain,Barcelona Sants,Barcelona,Cataluña,1.948,Long-distance,Railway operators timetables and reports (Tren...
143,2024,Switzerland,Genève,Genève,Genève,Spain,Barcelona Sants,Barcelona,Cataluña,2.775,Long-distance,EU Commission - Reports on cross-border rail p...

In [33]:
df.shape

(144, 12)

In [35]:
df=df.drop(columns=['source'])

In [36]:
df.columns

Index(['year', 'origin_country', 'origin_station_name', 'origin_city',
       'origin_region', 'destination_country', 'destination_station_name',
       'destination_city', 'destination_region', 'Passengers_millions',
       'Type'],
      dtype='object')

In [41]:
df=pd.read_csv('switzerland_rail_OD_flows.csv',sep=';')

In [42]:
df

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Genève,Winterthur,Genève,Winterthur,Genève,Zürich,1.638,Long-distance,SBB - Passenger frequency by station (used to ...
1,2016,Genève,Fribourg/Freiburg,Genève,Fribourg,Genève,Fribourg,2.083,Long-distance,Eurostat - Railway passenger transport statist...
2,2016,Lausanne,Zürich HB,Lausanne,Zürich,Vaud,Zürich,1.444,Long-distance,SBB Facts & Figures - Passenger transport (int...
3,2016,Lausanne,Fribourg/Freiburg,Lausanne,Fribourg,Vaud,Fribourg,0.639,Long-distance,SBB Facts & Figures - Passenger transport (int...
4,2016,Luzern,Lugano,Luzern,Lugano,Luzern,Ticino,1.649,Long-distance,SBB - Passenger frequency by station (used to ...
...,...,...,...,...,...,...,...,...,...,...
83,2024,Winterthur,Luzern,Winterthur,Luzern,Zürich,Luzern,3.155,Regional,SBB - Passenger frequency by station (used to ...
84,2024,Fribourg/Freiburg,Winterthur,Fribourg,Winterthur,Fribourg,Zürich,3.597,Regional,SBB - Passenger frequency by station (used to ...
85,2024,Lugano,Basel SBB,Lugano,Basel,Ticino,Basel-Stadt,0.905,Long-distance,SBB - Passenger frequency by station (used to ...
86,2024,Lugano,St. Gallen,Lugano,St. Gallen,Ticino,St. Gallen,1.519,Long-distance,Eurostat - Railway passenger transport statist...
87,2024,Lugano,Fribourg/Freiburg,Lugano,Fribourg,Ticino,Fribourg,4.870,Long-distance,SBB Facts & Figures - Passenger transport (int...

In [43]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type', 'source'],
      dtype='object')

In [44]:
df=df.drop(columns=['source'])

In [45]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type'],
      dtype='object')

In [46]:
df=pd.read_csv('france_rail_OD_flows.csv',sep=';')

In [47]:
df

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Paris Gare du Nord,Paris Gare de Lyon,Paris,Paris,Île-de-France,Île-de-France,1.05,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
1,2016,Paris Gare du Nord,Paris Saint-Lazare,Paris,Paris,Île-de-France,Île-de-France,1.13,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
2,2016,Paris Gare du Nord,Paris Montparnasse,Paris,Paris,Île-de-France,Île-de-France,0.88,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
3,2016,Paris Gare du Nord,Paris Est,Paris,Paris,Île-de-France,Île-de-France,0.93,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
4,2016,Paris Gare du Nord,Paris Austerlitz,Paris,Paris,Île-de-France,Île-de-France,0.89,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
...,...,...,...,...,...,...,...,...,...,...
2155,2024,Strasbourg,Lille Europe,Strasbourg,Lille,Grand Est,Hauts-de-France,0.92,TER/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
2156,2024,Strasbourg,Bordeaux Saint-Jean,Strasbourg,Bordeaux,Grand Est,Nouvelle-Aquitaine,1.17,TER/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
2157,2024,Strasbourg,Toulouse Matabiau,Strasbourg,Toulouse,Grand Est,Occitanie,0.98,TER/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
2158,2024,Strasbourg,Nantes,Strasbourg,Nantes,Grand Est,Pays de la Loire,1.24,TER/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."
2159,2024,Strasbourg,Rennes,Strasbourg,Rennes,Grand Est,Bretagne,1.13,TER/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF ..."

In [48]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type', 'source'],
      dtype='object')

In [49]:
df=df.drop(columns=['source'])

In [50]:
df.columns

Index(['year', 'origin_station_name', 'destination_station_name',
       'origin_city', 'destination_city', 'origin_region',
       'destination_region', 'Passengers_millions', 'Type'],
      dtype='object')

In [62]:
import pandas as pd
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')

# ── Chemins (adapter si besoin) ──────────────────────────────────
DATA_DIR   = "."        # dossier contenant les CSV sources
OUTPUT_DIR = "./output" # dossier de sortie
os.makedirs(OUTPUT_DIR, exist_ok=True)

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 60)
print('✅ Prêt')

✅ Prêt

In [63]:
def load_csv(filename, sep=';'):
    """Charge un CSV et affiche un résumé rapide."""
    path = os.path.join(DATA_DIR, filename)
    df = pd.read_csv(path, sep=sep, encoding='utf-8-sig')
    print(f'📂  {filename:<50}  {df.shape[0]:>5} lignes | {df.shape[1]} colonnes')
    return df

print('Chargement des fichiers...\n')
df_co2        = load_csv('co2_comparaison_europe.csv')
df_france     = load_csv('france_rail_OD_flows.csv')
df_germany    = load_csv('germany_rail_OD_flows.csv')
df_italy      = load_csv('italy_rail_OD_flows.csv')
df_spain      = load_csv('spain_rail_OD_flows.csv')
df_switz      = load_csv('switzerland_rail_OD_flows.csv')
df_crossbord  = load_csv('cross_border_rail_OD_IT_DE_CH_ES.csv')
print('\n✅ Tous les fichiers chargés.')

Chargement des fichiers...

📂  co2_comparaison_europe.csv                              5 lignes | 7 colonnes
📂  france_rail_OD_flows.csv                             2160 lignes | 10 colonnes
📂  germany_rail_OD_flows.csv                             110 lignes | 10 colonnes
📂  italy_rail_OD_flows.csv                                95 lignes | 10 colonnes
📂  spain_rail_OD_flows.csv                                83 lignes | 10 colonnes
📂  switzerland_rail_OD_flows.csv                          88 lignes | 10 colonnes
📂  cross_border_rail_OD_IT_DE_CH_ES.csv                  144 lignes | 12 colonnes

✅ Tous les fichiers chargés.

In [64]:
print('=== CO2 ===')
display(df_co2)

print('\n=== Flux France (5 premières lignes) ===')
display(df_france.head())

print('\n=== Flux Allemagne (5 premières lignes) ===')
display(df_germany.head())

print('\n=== Flux cross-border (5 premières lignes) ===')
display(df_crossbord.head())

=== CO2 ===

,Pays,Emissions_Train_g_km,Emissions_Voiture_g_km,Emissions_Avion_g_km,CO2_evite_Train_vs_Voiture_g_km,CO2_evite_Train_vs_Avion_g_km,Reduction_Train_vs_Voiture_%
0,France,3.0,192,255,189.0,252.0,98.44
1,Suisse,1.5,180,255,178.5,253.5,99.17
2,Portugal,30.0,190,250,160.0,220.0,84.21
3,Allemagne,32.0,192,255,160.0,223.0,83.33
4,Italie,35.0,185,250,150.0,215.0,81.08

=== Flux France (5 premières lignes) ===

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Paris Gare du Nord,Paris Gare de Lyon,Paris,Paris,Île-de-France,Île-de-France,1.05,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF rapports a..."
1,2016,Paris Gare du Nord,Paris Saint-Lazare,Paris,Paris,Île-de-France,Île-de-France,1.13,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF rapports a..."
2,2016,Paris Gare du Nord,Paris Montparnasse,Paris,Paris,Île-de-France,Île-de-France,0.88,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF rapports a..."
3,2016,Paris Gare du Nord,Paris Est,Paris,Paris,Île-de-France,Île-de-France,0.93,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF rapports a..."
4,2016,Paris Gare du Nord,Paris Austerlitz,Paris,Paris,Île-de-France,Île-de-France,0.89,TGV/Intercités,"SNCF Open Data - Fréquentation en gares, SNCF rapports a..."

=== Flux Allemagne (5 premières lignes) ===

,year,origin_station_name,destination_station_name,origin_city,destination_city,origin_region,destination_region,Passengers_millions,Type,source
0,2016,Berlin Hbf,Frankfurt (Main) Hbf,Berlin,Frankfurt am Main,Berlin,Hessen,2.539,Fernverkehr,Eurostat - Railway passenger transport statistics (used ...
1,2016,Berlin Hbf,Hannover Hbf,Berlin,Hannover,Berlin,Niedersachsen,1.098,Fernverkehr,Deutsche Bahn - Facts & Figures (long-distance and regio...
2,2016,Hamburg Hbf,Frankfurt (Main) Hbf,Hamburg,Frankfurt am Main,Hamburg,Hessen,2.493,Fernverkehr,Eurostat - Railway passenger transport statistics (used ...
3,2016,Hamburg Hbf,Köln Hbf,Hamburg,Köln,Hamburg,Nordrhein-Westfalen,0.848,Fernverkehr,VDV - Statistik zum SPNV in Deutschland (used for calibr...
4,2016,Hamburg Hbf,Leipzig Hbf,Hamburg,Leipzig,Hamburg,Sachsen,1.139,Fernverkehr,Deutsche Bahn - Facts & Figures (long-distance and regio...

=== Flux cross-border (5 premières lignes) ===

,year,origin_country,origin_station_name,origin_city,origin_region,destination_country,destination_station_name,destination_city,destination_region,Passengers_millions,Type,source
0,2016,Italy,Roma Termini,Roma,Lazio,Germany,München Hbf,München,Bayern,0.730,Long-distance,"Railway operators timetables and reports (Trenitalia, DB..."
1,2016,Italy,Milano Centrale,Milano,Lombardia,Germany,Frankfurt (Main) Hbf,Frankfurt am Main,Hessen,0.971,Long-distance,EU Commission - Reports on cross-border rail passenger s...
2,2016,Italy,Milano Centrale,Milano,Lombardia,Germany,Hamburg Hbf,Hamburg,Hamburg,2.723,Long-distance,"Railway operators timetables and reports (Trenitalia, DB..."
3,2016,Italy,Milano Centrale,Milano,Lombardia,Switzerland,Zürich HB,Zürich,Zürich,0.544,Long-distance,Eurostat - Railway passenger transport statistics (cross...
4,2016,Italy,Milano Centrale,Milano,Lombardia,Switzerland,Lugano,Lugano,Ticino,2.724,Long-distance,EU Commission - Reports on cross-border rail passenger s...

In [65]:
def transform_co2(df):
    df = df.copy()
    df.columns = [
        'country', 'emissions_train_g_km', 'emissions_car_g_km',
        'emissions_plane_g_km', 'co2_saved_vs_car_g_km',
        'co2_saved_vs_plane_g_km', 'reduction_vs_car_pct'
    ]
    df['country'] = df['country'].str.strip()
    num_cols = df.columns[1:]
    df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')
    print(f'✅ CO2 transformé : {df.shape}')
    return df

df_co2_clean = transform_co2(df_co2)
display(df_co2_clean)

✅ CO2 transformé : (5, 7)

,country,emissions_train_g_km,emissions_car_g_km,emissions_plane_g_km,co2_saved_vs_car_g_km,co2_saved_vs_plane_g_km,reduction_vs_car_pct
0,France,3.0,192,255,189.0,252.0,98.44
1,Suisse,1.5,180,255,178.5,253.5,99.17
2,Portugal,30.0,190,250,160.0,220.0,84.21
3,Allemagne,32.0,192,255,160.0,223.0,83.33
4,Italie,35.0,185,250,150.0,215.0,81.08

In [59]:
def transform_co2(df):
    df = df.copy()
    # Nettoyage des noms de colonnes
    df.columns = [
        'country', 'emissions_train_g_km', 'emissions_car_g_km',
        'emissions_plane_g_km', 'co2_saved_vs_car_g_km',
        'co2_saved_vs_plane_g_km', 'reduction_vs_car_pct'
    ]
    # Standardisation du nom de pays
    df['country'] = df['country'].str.strip()
    # S'assurer que les colonnes numériques sont bien float
    num_cols = df.columns[1:]
    df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')
    print(f'✅ CO2 transformé : {df.shape}')
    return df

df_co2_clean = transform_co2(df_co2)
display(df_co2_clean.head())

✅ CO2 transformé : (5, 7)

,country,emissions_train_g_km,emissions_car_g_km,emissions_plane_g_km,co2_saved_vs_car_g_km,co2_saved_vs_plane_g_km,reduction_vs_car_pct
0,France,3.0,192,255,189.0,252.0,98.44
1,Suisse,1.5,180,255,178.5,253.5,99.17
2,Portugal,30.0,190,250,160.0,220.0,84.21
3,Allemagne,32.0,192,255,160.0,223.0,83.33
4,Italie,35.0,185,250,150.0,215.0,81.08

In [66]:
# Mapping pays → (code ISO, label anglais, label CO2)
COUNTRY_MAP = {
    'france'      : ('FR', 'France',      'France'),
    'germany'     : ('DE', 'Germany',     'Allemagne'),
    'italy'       : ('IT', 'Italy',       'Italie'),
    'spain'       : ('ES', 'Spain',       'Espagne'),
    'switzerland' : ('CH', 'Switzerland', 'Suisse'),
}

# Colonnes standardisées communes aux 5 fichiers nationaux
NATIONAL_COLS = [
    'year', 'origin_station', 'destination_station',
    'origin_city', 'destination_city',
    'origin_region', 'destination_region',
    'passengers_millions', 'service_type', 'source'
]

def transform_od_national(df, country_key):
    """Nettoyage générique pour les flux OD nationaux."""
    df = df.copy()
    iso, label, _ = COUNTRY_MAP[country_key]

    df.columns = NATIONAL_COLS

    # Métadonnées pays
    df['country']     = label
    df['country_iso'] = iso
    df['flow_type']   = 'domestic'

    # Cast types
    df['year']               = pd.to_numeric(df['year'], errors='coerce').astype('Int64')
    df['passengers_millions'] = pd.to_numeric(df['passengers_millions'], errors='coerce')

    # Nettoyage textes
    text_cols = ['origin_station', 'destination_station',
                 'origin_city', 'destination_city',
                 'origin_region', 'destination_region']
    for col in text_cols:
        df[col] = df[col].str.strip()

    # Suppression doublons
    before = len(df)
    df.drop_duplicates(subset=['year', 'origin_station', 'destination_station'], inplace=True)
    removed = before - len(df)
    if removed:
        print(f'  ⚠️  {removed} doublon(s) supprimé(s) dans {label}')

    # Suppression lignes sans passagers
    df.dropna(subset=['passengers_millions'], inplace=True)

    print(f'✅ {label:<15} transformé : {df.shape[0]} lignes')
    return df

df_france_clean  = transform_od_national(df_france,  'france')
df_germany_clean = transform_od_national(df_germany, 'germany')
df_italy_clean   = transform_od_national(df_italy,   'italy')
df_spain_clean   = transform_od_national(df_spain,   'spain')
df_switz_clean   = transform_od_national(df_switz,   'switzerland')

✅ France          transformé : 2160 lignes
✅ Germany         transformé : 110 lignes
✅ Italy           transformé : 95 lignes
✅ Spain           transformé : 83 lignes
✅ Switzerland     transformé : 88 lignes

In [67]:
def transform_crossborder(df):
    df = df.copy()
    df.columns = [
        'year',
        'origin_country_iso', 'origin_station', 'origin_city', 'origin_region',
        'destination_country_iso', 'destination_station', 'destination_city', 'destination_region',
        'passengers_millions', 'service_type', 'source'
    ]
    df['flow_type'] = 'cross_border'

    df['year']                = pd.to_numeric(df['year'], errors='coerce').astype('Int64')
    df['passengers_millions'] = pd.to_numeric(df['passengers_millions'], errors='coerce')

    text_cols = ['origin_station', 'destination_station',
                 'origin_city', 'destination_city',
                 'origin_region', 'destination_region']
    for col in text_cols:
        df[col] = df[col].str.strip()

    # Normaliser les noms de pays ISO (ex: 'Italy' → 'IT')
    country_to_iso = {
        'France': 'FR', 'Germany': 'DE', 'Italy': 'IT',
        'Spain': 'ES', 'Switzerland': 'CH'
    }
    df['origin_country_iso']      = df['origin_country_iso'].map(country_to_iso).fillna(df['origin_country_iso'])
    df['destination_country_iso'] = df['destination_country_iso'].map(country_to_iso).fillna(df['destination_country_iso'])

    df.dropna(subset=['passengers_millions'], inplace=True)
    print(f'✅ Cross-border transformé : {df.shape[0]} lignes')
    return df

df_crossbord_clean = transform_crossborder(df_crossbord)
display(df_crossbord_clean.head())

✅ Cross-border transformé : 144 lignes

,year,origin_country_iso,origin_station,origin_city,origin_region,destination_country_iso,destination_station,destination_city,destination_region,passengers_millions,service_type,source,flow_type
0,2016,IT,Roma Termini,Roma,Lazio,DE,München Hbf,München,Bayern,0.730,Long-distance,"Railway operators timetables and reports (Trenitalia, DB...",cross_border
1,2016,IT,Milano Centrale,Milano,Lombardia,DE,Frankfurt (Main) Hbf,Frankfurt am Main,Hessen,0.971,Long-distance,EU Commission - Reports on cross-border rail passenger s...,cross_border
2,2016,IT,Milano Centrale,Milano,Lombardia,DE,Hamburg Hbf,Hamburg,Hamburg,2.723,Long-distance,"Railway operators timetables and reports (Trenitalia, DB...",cross_border
3,2016,IT,Milano Centrale,Milano,Lombardia,CH,Zürich HB,Zürich,Zürich,0.544,Long-distance,Eurostat - Railway passenger transport statistics (cross...,cross_border
4,2016,IT,Milano Centrale,Milano,Lombardia,CH,Lugano,Lugano,Ticino,2.724,Long-distance,EU Commission - Reports on cross-border rail passenger s...,cross_border

In [68]:
# Schéma commun minimal pour le concat
COMMON_COLS = [
    'year', 'origin_station', 'destination_station',
    'origin_city', 'destination_city',
    'origin_region', 'destination_region',
    'passengers_millions', 'service_type', 'flow_type', 'source'
]

# Flux nationaux : on ajoute origin/destination_country_iso identiques
national_frames = []
for df, iso in [
    (df_france_clean,  'FR'),
    (df_germany_clean, 'DE'),
    (df_italy_clean,   'IT'),
    (df_spain_clean,   'ES'),
    (df_switz_clean,   'CH'),
]:
    tmp = df[COMMON_COLS].copy()
    tmp['origin_country_iso']      = iso
    tmp['destination_country_iso'] = iso
    national_frames.append(tmp)

# Flux cross-border
cb = df_crossbord_clean[COMMON_COLS + ['origin_country_iso', 'destination_country_iso']].copy()

# Concatenation
df_all_od = pd.concat(national_frames + [cb], ignore_index=True)

print(f'✅ Table OD consolidée : {df_all_od.shape[0]:,} lignes | {df_all_od.shape[1]} colonnes')
display(df_all_od.sample(5, random_state=42))

✅ Table OD consolidée : 2,680 lignes | 13 colonnes

,year,origin_station,destination_station,origin_city,destination_city,origin_region,destination_region,passengers_millions,service_type,flow_type,source,origin_country_iso,destination_country_iso
1064,2020,Lyon Part-Dieu,Strasbourg,Lyon,Strasbourg,Auvergne-Rhône-Alpes,Grand Est,0.43,TER/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR
1674,2022,Strasbourg,Lille Flandres,Strasbourg,Lille,Grand Est,Hauts-de-France,0.95,TER/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR
2021,2024,Lyon Part-Dieu,Toulouse Matabiau,Lyon,Toulouse,Auvergne-Rhône-Alpes,Occitanie,1.15,TER/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR
759,2019,Paris Saint-Lazare,Lille Europe,Paris,Lille,Île-de-France,Hauts-de-France,6.79,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR
211,2016,Rennes,Paris Gare de Lyon,Rennes,Paris,Bretagne,Île-de-France,4.20,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR

In [69]:
# Mapping ISO → nom dans la table CO2 (noms en français)
ISO_TO_CO2_COUNTRY = {
    'FR': 'France',
    'DE': 'Allemagne',
    'IT': 'Italie',
    'ES': 'Espagne',
    'CH': 'Suisse',
}

df_all_od['co2_country_key'] = df_all_od['origin_country_iso'].map(ISO_TO_CO2_COUNTRY)

df_enriched = df_all_od.merge(
    df_co2_clean[['country', 'emissions_train_g_km', 'emissions_car_g_km',
                  'co2_saved_vs_car_g_km', 'reduction_vs_car_pct']],
    left_on='co2_country_key',
    right_on='country',
    how='left'
).drop(columns=['country', 'co2_country_key'])

print(f'✅ Table enrichie : {df_enriched.shape}')
print(f"   Taux de match CO2 : {df_enriched['emissions_train_g_km'].notna().mean():.1%}")
display(df_enriched.head())

✅ Table enrichie : (2680, 17)
   Taux de match CO2 : 96.9%

,year,origin_station,destination_station,origin_city,destination_city,origin_region,destination_region,passengers_millions,service_type,flow_type,source,origin_country_iso,destination_country_iso,emissions_train_g_km,emissions_car_g_km,co2_saved_vs_car_g_km,reduction_vs_car_pct
0,2016,Paris Gare du Nord,Paris Gare de Lyon,Paris,Paris,Île-de-France,Île-de-France,1.05,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR,3.0,192.0,189.0,98.44
1,2016,Paris Gare du Nord,Paris Saint-Lazare,Paris,Paris,Île-de-France,Île-de-France,1.13,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR,3.0,192.0,189.0,98.44
2,2016,Paris Gare du Nord,Paris Montparnasse,Paris,Paris,Île-de-France,Île-de-France,0.88,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR,3.0,192.0,189.0,98.44
3,2016,Paris Gare du Nord,Paris Est,Paris,Paris,Île-de-France,Île-de-France,0.93,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR,3.0,192.0,189.0,98.44
4,2016,Paris Gare du Nord,Paris Austerlitz,Paris,Paris,Île-de-France,Île-de-France,0.89,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF rapports a...",FR,FR,3.0,192.0,189.0,98.44

In [70]:
print('=== Répartition par pays et type de flux ===')
display(
    df_enriched.groupby(['origin_country_iso', 'flow_type'])
               .agg(
                   nb_routes          = ('passengers_millions', 'count'),
                   total_passengers_M = ('passengers_millions', 'sum'),
               )
               .round(2)
               .reset_index()
               .sort_values('total_passengers_M', ascending=False)
)

=== Répartition par pays et type de flux ===

  origin_country_iso     flow_type  nb_routes  total_passengers_M
5                 FR      domestic       2160             6764.81
3                 DE      domestic        110              291.97
7                 IT      domestic         95              288.42
4                 ES      domestic         83              259.88
1                 CH      domestic         88              252.48
6                 IT  cross_border         72              115.82
2                 DE  cross_border         54               95.74
0                 CH  cross_border         18               31.31

In [71]:
print('=== Top 10 des routes les plus fréquentées ===')
top10 = (
    df_enriched
    .groupby(['origin_country_iso', 'origin_city', 'destination_city'])
    ['passengers_millions'].sum()
    .reset_index()
    .sort_values('passengers_millions', ascending=False)
    .head(10)
)
display(top10)

=== Top 10 des routes les plus fréquentées ===

    origin_country_iso origin_city destination_city  passengers_millions
204                 FR        Lyon            Paris               813.68
226                 FR       Paris             Lyon               805.06
225                 FR       Paris            Lille               708.41
195                 FR       Lille            Paris               704.18
227                 FR       Paris        Marseille               308.16
212                 FR   Marseille            Paris               306.82
224                 FR       Paris         Bordeaux               254.82
229                 FR       Paris            Paris               251.49
186                 FR    Bordeaux            Paris               249.36
230                 FR       Paris           Rennes               203.24

In [72]:
print('=== Évolution totale par année ===')
display(
    df_enriched.groupby('year')
               .agg(
                   nb_routes          = ('passengers_millions', 'count'),
                   total_passengers_M = ('passengers_millions', 'sum'),
               )
               .round(2)
)

=== Évolution totale par année ===

      nb_routes  total_passengers_M
year
2016        308              982.45
2017        299              935.11
2018        299              969.79
2019        295              962.78
2020        290              449.97
2021        303              755.12
2022        283              940.80
2023        300             1039.52
2024        303             1064.88

In [73]:
print('=== Comparatif CO₂ par pays (train vs voiture) ===')
display(df_co2_clean[['country', 'emissions_train_g_km', 'emissions_car_g_km',
                       'reduction_vs_car_pct']].sort_values('emissions_train_g_km'))

=== Comparatif CO₂ par pays (train vs voiture) ===

     country  emissions_train_g_km  emissions_car_g_km  reduction_vs_car_pct
1     Suisse                   1.5                 180                 99.17
0     France                   3.0                 192                 98.44
2   Portugal                  30.0                 190                 84.21
3  Allemagne                  32.0                 192                 83.33
4     Italie                  35.0                 185                 81.08

In [74]:
# ── Table 1 : flux OD enrichis (table principale) ────────────────
out_od = os.path.join(OUTPUT_DIR, 'od_flows_enriched.csv')
df_enriched.to_csv(out_od, index=False, sep=';', encoding='utf-8-sig')
print(f'💾 od_flows_enriched.csv     → {len(df_enriched):,} lignes')

# ── Table 2 : CO2 nettoyé ─────────────────────────────────────────
out_co2 = os.path.join(OUTPUT_DIR, 'co2_clean.csv')
df_co2_clean.to_csv(out_co2, index=False, sep=';', encoding='utf-8-sig')
print(f'💾 co2_clean.csv             → {len(df_co2_clean):,} lignes')

# ── Table 3 : agrégat par pays/année/type ─────────────────────────
df_agg = (
    df_enriched
    .groupby(['year', 'origin_country_iso', 'flow_type'])
    .agg(
        nb_routes          = ('passengers_millions', 'count'),
        total_passengers_M = ('passengers_millions', 'sum'),
        avg_passengers_M   = ('passengers_millions', 'mean'),
        max_route_M        = ('passengers_millions', 'max'),
    )
    .round(3)
    .reset_index()
)
out_agg = os.path.join(OUTPUT_DIR, 'od_aggregated.csv')
df_agg.to_csv(out_agg, index=False, sep=';', encoding='utf-8-sig')
print(f'💾 od_aggregated.csv         → {len(df_agg):,} lignes')

print(f'\n✅ Export terminé — dossier : {os.path.abspath(OUTPUT_DIR)}')

💾 od_flows_enriched.csv     → 2,680 lignes
💾 co2_clean.csv             → 5 lignes
💾 od_aggregated.csv         → 72 lignes

✅ Export terminé — dossier : c:\Users\scott\Desktop\epsi\github\MsprDS\csv\output

In [75]:
import pandas as pd
import sqlite3
import os

# ── Chemins (adapter si besoin) ──────────────────────────────────
OUTPUT_DIR = "./output"                        # dossier des CSV produits par l'ETL
DB_PATH    = "./rail_europe.db"                # fichier SQLite à créer

print(f'📁 Dossier CSV  : {os.path.abspath(OUTPUT_DIR)}')
print(f'🗄️  Base SQLite  : {os.path.abspath(DB_PATH)}')
print('✅ Prêt')

📁 Dossier CSV  : c:\Users\scott\Desktop\epsi\github\MsprDS\csv\output
🗄️  Base SQLite  : c:\Users\scott\Desktop\epsi\github\MsprDS\csv\rail_europe.db
✅ Prêt

In [76]:
def read_csv(filename):
    path = os.path.join(OUTPUT_DIR, filename)
    df = pd.read_csv(path, sep=';', encoding='utf-8-sig')
    print(f'📂  {filename:<35}  {df.shape[0]:>5} lignes | {df.shape[1]} colonnes')
    return df

df_od  = read_csv('od_flows_enriched.csv')
df_co2 = read_csv('co2_clean.csv')
df_agg = read_csv('od_aggregated.csv')
print('\n✅ CSV chargés en mémoire.')

📂  od_flows_enriched.csv                 2680 lignes | 17 colonnes
📂  co2_clean.csv                            5 lignes | 7 colonnes
📂  od_aggregated.csv                       72 lignes | 7 colonnes

✅ CSV chargés en mémoire.

In [77]:
# Connexion (crée le fichier s'il n'existe pas)
con = sqlite3.connect(DB_PATH)
print(f'🔌 Connexion ouverte → {DB_PATH}')

# ── Schémas DDL explicites ────────────────────────────────────────
DDL = """
-- Table principale : flux OD enrichis
CREATE TABLE IF NOT EXISTS od_flows_enriched (
    id                       INTEGER PRIMARY KEY AUTOINCREMENT,
    year                     INTEGER,
    origin_station           TEXT,
    destination_station      TEXT,
    origin_city              TEXT,
    destination_city         TEXT,
    origin_region            TEXT,
    destination_region       TEXT,
    passengers_millions      REAL,
    service_type             TEXT,
    flow_type                TEXT,
    source                   TEXT,
    origin_country_iso       TEXT,
    destination_country_iso  TEXT,
    emissions_train_g_km     REAL,
    emissions_car_g_km       REAL,
    co2_saved_vs_car_g_km    REAL,
    reduction_vs_car_pct     REAL
);

-- Table CO2 par pays
CREATE TABLE IF NOT EXISTS co2_clean (
    id                       INTEGER PRIMARY KEY AUTOINCREMENT,
    country                  TEXT,
    emissions_train_g_km     REAL,
    emissions_car_g_km       REAL,
    emissions_plane_g_km     REAL,
    co2_saved_vs_car_g_km    REAL,
    co2_saved_vs_plane_g_km  REAL,
    reduction_vs_car_pct     REAL
);

-- Table agrégat par pays/année/type
CREATE TABLE IF NOT EXISTS od_aggregated (
    id                     INTEGER PRIMARY KEY AUTOINCREMENT,
    year                   INTEGER,
    origin_country_iso     TEXT,
    flow_type              TEXT,
    nb_routes              INTEGER,
    total_passengers_M     REAL,
    avg_passengers_M       REAL,
    max_route_M            REAL
);
"""

con.executescript(DDL)
con.commit()
print('✅ Tables créées (ou déjà existantes).')

🔌 Connexion ouverte → ./rail_europe.db
✅ Tables créées (ou déjà existantes).

In [78]:
# ── Insertion des données ─────────────────────────────────────────
# if_exists='replace' : vide et recrée la table à chaque exécution
# Utiliser 'append' si tu veux cumuler des runs

tables = {
    'od_flows_enriched' : df_od,
    'co2_clean'         : df_co2,
    'od_aggregated'     : df_agg,
}

for table_name, df in tables.items():
    df.to_sql(table_name, con, if_exists='replace', index=False)
    # Vérification du nombre de lignes insérées
    count = con.execute(f'SELECT COUNT(*) FROM {table_name}').fetchone()[0]
    print(f'✅ {table_name:<25} → {count:>5} lignes insérées')

con.commit()
print('\n💾 Toutes les tables sont chargées.')

✅ od_flows_enriched         →  2680 lignes insérées
✅ co2_clean                 →     5 lignes insérées
✅ od_aggregated             →    72 lignes insérées

💾 Toutes les tables sont chargées.

In [79]:
INDEXES = """
CREATE INDEX IF NOT EXISTS idx_od_country_year
    ON od_flows_enriched (origin_country_iso, year);

CREATE INDEX IF NOT EXISTS idx_od_flow_type
    ON od_flows_enriched (flow_type);

CREATE INDEX IF NOT EXISTS idx_od_cities
    ON od_flows_enriched (origin_city, destination_city);

CREATE INDEX IF NOT EXISTS idx_agg_country_year
    ON od_aggregated (origin_country_iso, year);
"""

con.executescript(INDEXES)
con.commit()
print('✅ Index créés.')

✅ Index créés.

In [80]:
# Vue d'ensemble de la base
tables_in_db = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", con)
print('Tables dans la base :', tables_in_db['name'].tolist())

print('\n=== Taille du fichier SQLite ===')
size_kb = os.path.getsize(DB_PATH) / 1024
print(f'📦 {DB_PATH} : {size_kb:.1f} Ko')

Tables dans la base : ['sqlite_sequence', 'od_flows_enriched', 'co2_clean', 'od_aggregated']

=== Taille du fichier SQLite ===
📦 ./rail_europe.db : 876.0 Ko

In [81]:
# Requête 1 : Top 10 routes les plus fréquentées
q1 = """
SELECT
    origin_country_iso,
    origin_city,
    destination_city,
    ROUND(SUM(passengers_millions), 2) AS total_pax_M
FROM od_flows_enriched
GROUP BY origin_country_iso, origin_city, destination_city
ORDER BY total_pax_M DESC
LIMIT 10;
"""
print('=== Top 10 routes ===')
display(pd.read_sql(q1, con))

=== Top 10 routes ===

  origin_country_iso origin_city destination_city  total_pax_M
0                 FR        Lyon            Paris       813.68
1                 FR       Paris             Lyon       805.06
2                 FR       Paris            Lille       708.41
3                 FR       Lille            Paris       704.18
4                 FR       Paris        Marseille       308.16
5                 FR   Marseille            Paris       306.82
6                 FR       Paris         Bordeaux       254.82
7                 FR       Paris            Paris       251.49
8                 FR    Bordeaux            Paris       249.36
9                 FR       Paris           Rennes       203.24

In [82]:
# Requête 2 : Passagers totaux par pays et type de flux
q2 = """
SELECT
    origin_country_iso AS pays,
    flow_type,
    COUNT(*)                              AS nb_routes,
    ROUND(SUM(passengers_millions), 2)    AS total_pax_M
FROM od_flows_enriched
GROUP BY pays, flow_type
ORDER BY total_pax_M DESC;
"""
print('=== Passagers par pays / type ===')
display(pd.read_sql(q2, con))

=== Passagers par pays / type ===

  pays     flow_type  nb_routes  total_pax_M
0   FR      domestic       2160      6764.81
1   DE      domestic        110       291.97
2   IT      domestic         95       288.42
3   ES      domestic         83       259.88
4   CH      domestic         88       252.48
5   IT  cross_border         72       115.82
6   DE  cross_border         54        95.74
7   CH  cross_border         18        31.31

In [83]:
# Requête 3 : Émissions CO2 et économies par pays
q3 = """
SELECT
    country,
    emissions_train_g_km,
    emissions_car_g_km,
    co2_saved_vs_car_g_km,
    reduction_vs_car_pct
FROM co2_clean
ORDER BY emissions_train_g_km ASC;
"""
print('=== CO₂ — train vs voiture ===')
display(pd.read_sql(q3, con))

=== CO₂ — train vs voiture ===

,country,emissions_train_g_km,emissions_car_g_km,co2_saved_vs_car_g_km,reduction_vs_car_pct
0,Suisse,1.5,180,178.5,99.17
1,France,3.0,192,189.0,98.44
2,Portugal,30.0,190,160.0,84.21
3,Allemagne,32.0,192,160.0,83.33
4,Italie,35.0,185,150.0,81.08

In [84]:
# Requête 4 : Évolution annuelle (jointure od_flows + co2)
q4 = """
SELECT
    o.year,
    o.origin_country_iso AS pays,
    ROUND(SUM(o.passengers_millions), 2)          AS total_pax_M,
    MAX(o.emissions_train_g_km)                   AS co2_train_g_km,
    ROUND(SUM(o.passengers_millions)
          * MAX(o.co2_saved_vs_car_g_km), 0)       AS co2_economise_total_g
FROM od_flows_enriched o
WHERE o.flow_type = 'domestic'
GROUP BY o.year, o.origin_country_iso
ORDER BY o.year, pays;
"""
print('=== Évolution annuelle + CO₂ économisé (domestic) ===')
display(pd.read_sql(q4, con))

=== Évolution annuelle + CO₂ économisé (domestic) ===

    year pays  total_pax_M  co2_train_g_km  co2_economise_total_g
0   2016   CH        19.87             1.5                 3547.0
1   2016   DE        47.62            32.0                 7619.0
2   2016   ES        36.74             NaN                    NaN
3   2016   FR       815.19             3.0               154071.0
4   2016   IT        40.04            35.0                 6006.0
5   2017   CH        32.04             1.5                 5719.0
6   2017   DE        22.47            32.0                 3595.0
7   2017   ES        22.63             NaN                    NaN
8   2017   FR       805.27             3.0               152196.0
9   2017   IT        28.69            35.0                 4303.0
10  2018   CH        33.26             1.5                 5938.0
11  2018   DE        24.24            32.0                 3878.0
12  2018   ES        33.53             NaN                    NaN
13  2018   FR       821.04             3.0               155177.0
14  2018   IT        29.59            35.0                 4439.0
15  2019   CH        34.67             1.5                 6189.0
16  2019   DE        26.50            32.0                 4241.0
17  2019   ES        21.73             NaN                    NaN
18  2019   FR       820.54             3.0               155082.0
19  2019   IT        32.69            35.0                 4904.0
20  2020   CH        18.27             1.5                 3262.0
21  2020   DE        30.15            32.0                 4823.0
22  2020   ES        11.61             NaN                    NaN
23  2020   FR       334.51             3.0                63222.0
24  2020   IT        28.72            35.0                 4308.0
25  2021   CH        32.77             1.5                 5849.0
26  2021   DE        38.43            32.0                 6149.0
27  2021   ES        29.55             NaN                    NaN
28  2021   FR       590.72             3.0               111646.0
29  2021   IT        43.40            35.0                 6510.0
30  2022   CH        12.57             1.5                 2245.0
31  2022   DE        11.83            32.0                 1893.0
32  2022   ES        17.29             NaN                    NaN
33  2022   FR       847.76             3.0               160227.0
34  2022   IT        20.30            35.0                 3046.0
35  2023   CH        22.82             1.5                 4074.0
36  2023   DE        47.18            32.0                 7548.0
37  2023   ES        35.42             NaN                    NaN
38  2023   FR       863.17             3.0               163139.0
39  2023   IT        38.03            35.0                 5704.0
40  2024   CH        46.20             1.5                 8246.0
41  2024   DE        43.56            32.0                 6969.0
42  2024   ES        51.39             NaN                    NaN
43  2024   FR       866.61             3.0               163789.0
44  2024   IT        26.95            35.0                 4043.0

In [85]:
con.close()
print(f'🔒 Connexion fermée.')
print(f'\n✅ Base de données prête : {os.path.abspath(DB_PATH)}')
print('   → Ouvrir avec DB Browser for SQLite, DBeaver, ou tout autre client SQLite.')

🔒 Connexion fermée.

✅ Base de données prête : c:\Users\scott\Desktop\epsi\github\MsprDS\csv\rail_europe.db
   → Ouvrir avec DB Browser for SQLite, DBeaver, ou tout autre client SQLite.

In [ ]:
! pip install JSON

In [2]:
import pandas as pd


df=pd.read_json("agencies.json")
df.to_csv("agencies.csv", index=False)

In [3]:
df

,ATC,BDŽ,ČD,CFM,CFR,CS,ES,FS,GA,GWR,...,SNCF,ST,TCDD,UEX,UZ,VR,VY,ŽPCG,ŽS,ZSSK
agency_id,ATC,BDŽ,ČD,CFM,CFR,CS,ES,FS,GA,GWR,...,SNCF,ST,TCDD,UEX,UZ,VR,VY,ŽPCG,ŽS,ZSSK
agency_name,Astra Trans Carpatic SRL,БДЖ - Пътнически превози ЕООД,České dráhy a.s.,Calea Ferată din Moldova,C.F.R. Călători S.A.,Caledonian Sleeper Ltd.,European Sleeper Cooperatïe,Trenitalia S.p.A,Go-Ahead Norge AS,First Greater Western Ltd.,...,SNCF Voyageurs SA,Merresor AB,TCDD Taşımacılık A.Ş.,Train4you Vertriebs GmbH,Укрзалізниця,VR-Yhtymä Oy,Vygruppen AS,Željeznički prevoz Crne Gore AD,Железнице Србије ад,Železničná spoločnosť Slovensko a.s.
agency_url,https://astratranscarpatic.ro,https://www.bdz.bg,https://www.cd.cz,http://railway.md,https://www.cfrcalatori.ro,https://www.sleeper.scot,https://www.europeansleeper.eu,https://www.trenitalia.com,https://go-aheadnordic.com,https://www.gwr.com,...,https://www.sncf.com,https://www.snalltaget.se,https://www.tcddtasimacilik.gov.tr/,https://buchung.urlaubs-express.de/,https://www.uz.gov.ua/,https://www.vr.fi,https://www.vy.no,https://www.zcg-prevoz.me,https://srbijavoz.rs,https://www.zssk.sk
agency_timezone,EET,EET,CET,EET,EET,WET,CET,CET,CET,WET,...,CET,CET,Europe/Istanbul,CET,EET,EET,CET,CET,CET,CET
agency_lang,ro,bg,cs,ro,ro,en,nl,en,nb,en,...,fr,sv,tr,de,uk,fi,nb,cnr,sr,sk
agency_phone,,,,,,,,,,,...,,,,,,,,,,
agency_fare_url,,,https://www.cd.cz/en/nase-vlaky/nocni-vlaky/-2...,,,,,,,,...,https://www.sncf-connect.com/en-en/,,,https://buchung.urlaubs-express.de/,https://booking.uz.gov.ua/,,,,https://w3.srbvoz.rs,
agency_email,,,,,,,,,,,...,,,,,,,,,,
agency_name_romanized,,Balgarski darzhavni zheleznitsi,,,,,,,,,...,,,,,Ukrzaliznytsia,,,,Železnice Srbije,
agency_name_brand,,,,,,Caledonian Sleeper,,,Go-Ahead Nordic,Great Western,...,SNCF,Snälltåget,,Urlaubs-Express,,,,,,
agency_state,RO,BG,CZ,MD,RO,UK,NL,IT,UK,UK,...,FR,DE,TR,DE,UA,FI,NO,ME,RS,SK
agency_logo_url,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...
agency_conditions_groups,,,,,,,,,,,...,,,,,,,,"CITY STAR: 1st passenger pays the full fare, 2...",,
agency_conditions_children,,,,,,,,,,,...,,,,,,,,"0-6 free, 7-14 50%",,
,,,,,,,,,,,...,,,,,,,,,,

In [4]:
df=pd.read_json("calendar.json")
df.to_csv("calendrier.csv",index=False)

In [5]:
df

,-- 2024 --,Daily,0-2 days/week (May-Oct),"2024/03/31-2024/11/03: Mon, Tue, Wed, Thu, Fri, Sun","2024: Mon, Tue, Wed, Thu, Fri","2024: Mon, Tue, Wed, Thu, Sun",2024: Daily except Sat,"2024: 1-5,7","Mon, Wed, Fri","2024/07/08-2024/09/22: Mon, Wed, Sat",...,2026/06/11-09/06: Daily,Unknown,2026/06/27-2026/08/31: Daily,2026/06/26-2026/08/30: Daily,"2026: Tue, Thu","2026: Mon, Wed, Thu, Fri, Sat","2026: Mon, Wed, Fri, Sat, Son","2026: Thu, Sat",2026: Sat,2026: Tue
service_id,-- 2024 --,Daily,0-2 days/week (May-Oct),"2024/03/31-2024/11/03: Mon, Tue, Wed, Thu, Fri...","2024: Mon, Tue, Wed, Thu, Fri","2024: Mon, Tue, Wed, Thu, Sun",2024: Daily except Sat,"2024: 1-5,7","Mon, Wed, Fri","2024/07/08-2024/09/22: Mon, Wed, Sat",...,2026/06/11-09/06: Daily,Unknown,2026/06/27-2026/08/31: Daily,2026/06/26-2026/08/30: Daily,"2026: Tue, Thu","2026: Mon, Wed, Thu, Fri, Sat","2026: Mon, Wed, Fri, Sat, Son","2026: Thu, Sat",2026: Sat,2026: Tue
monday,,1,0,1,1,1,1,1,1,0,...,1,,1,1,0,1,1,0,0,0
tuesday,,1,0,1,1,1,1,1,0,1,...,1,,1,1,1,0,0,0,0,1
wednesday,,1,0,1,1,1,1,1,1,0,...,1,,1,1,0,1,1,0,0,0
thursday,,1,0,1,1,1,1,1,0,0,...,1,,1,1,1,1,0,1,0,0
friday,,1,0,1,1,0,1,1,1,1,...,1,,1,1,0,1,1,0,0,0
saturday,,1,0,0,0,0,0,0,0,0,...,1,,1,1,0,1,1,1,1,0
sunday,,1,0,1,0,1,1,1,0,1,...,1,,1,1,0,0,1,0,0,0
start_date,,2023-12-10T00:00:00.000Z,20240518,2024-03-31T00:00:00.000Z,2023-12-10T00:00:00.000Z,2023-12-10T00:00:00.000Z,2023-12-10T00:00:00.000Z,2023-12-10T00:00:00.000Z,2023-12-10T00:00:00.000Z,2024-06-08T00:00:00.000Z,...,20260611,,2026-06-28T00:00:00.000Z,2026-06-27T00:00:00.000Z,2025-12-14T00:00:00.000Z,2025-12-14T00:00:00.000Z,2025-12-14T00:00:00.000Z,2025-12-14T00:00:00.000Z,20251214,20251214
end_date,,2024-12-14T00:00:00.000Z,20241019,2024-11-03T00:00:00.000Z,2024-12-14T00:00:00.000Z,2024-12-14T00:00:00.000Z,2024-12-14T00:00:00.000Z,2024-12-14T00:00:00.000Z,2024-12-14T00:00:00.000Z,2024-09-22T00:00:00.000Z,...,20260906,,2026-08-31T00:00:00.000Z,2026-08-30T00:00:00.000Z,2026-12-13T00:00:00.000Z,2026-12-13T00:00:00.000Z,2026-12-13T00:00:00.000Z,2026-12-13T00:00:00.000Z,20261213,20261213

In [8]:
df=pd.read_json("calendar_dates.json")
df.to_csv("calendrier_dates.csv",index=False)

In [7]:
df

,1,2,3,4,5,6,7,8,9,10,...,50,51,52,53,54,55,56,57,58,59
UID,1,2,3,4,5,6,7,8,9,10,...,50,51,52,53,54,55,56,57,58,59
train_id,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,...,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,PKP/ČD EN 40416,PKP/ČD EN 40417,PKP/ČD EN 406,PKP/ČD EN 407
service_id,,,,,,,,,,,...,"2024/05/03-2024/10/02: Wed, Fri, Sun","2024/05/03-2024/10/02: Wed, Fri, Sun","2024/05/03-2024/10/02: Wed, Fri, Sun","2024/05/03-2024/10/02: Wed, Fri, Sun","2024/05/03-2024/10/02: Wed, Fri, Sun","2024/05/03-2024/10/02: Wed, Fri, Sun",2026: Daily,2026: Daily,2026: Daily,2026: Daily
date,2023-09-09T00:00:00.000Z,2023-09-28T00:00:00.000Z,2023-10-12T00:00:00.000Z,2023-10-14T00:00:00.000Z,2023-10-23T00:00:00.000Z,2023-10-28T00:00:00.000Z,2023-11-10T00:00:00.000Z,2023-11-16T00:00:00.000Z,,2023-12-09T00:00:00.000Z,...,2024-06-07T00:00:00.000Z,2024-06-09T00:00:00.000Z,2024-06-21T00:00:00.000Z,2024-06-23T00:00:00.000Z,2024-09-20T00:00:00.000Z,2024-09-22T00:00:00.000Z,,,,
date_from,,,,,,,,,2023-12-02T00:00:00.000Z,,...,,,,,,,2026-02-02T00:00:00.000Z,2026-02-02T00:00:00.000Z,2026-02-02T00:00:00.000Z,2026-02-02T00:00:00.000Z
date_until,,,,,,,,,2023-12-04T00:00:00.000Z,,...,,,,,,,2026-02-06T00:00:00.000Z,2026-02-06T00:00:00.000Z,2026-02-06T00:00:00.000Z,2026-02-06T00:00:00.000Z
exception_type,2,2,2,2,2,2,2,2,,2,...,2,2,2,2,2,2,2,2,2,2

In [10]:
df=pd.read_json("classes.json")
df.to_csv("classes.csv",index=False)

In [11]:
df

,seat (reclinig),seat (compartment),seat,couchette (4-berth),couchette (6-berth),capsule (seat/bed),capsule (bed),Sleeper (2-berth) with shower & WC,Sleeper (double) with shower & WC,Sleeper (3-berth) with shower & WC,Sleeper (2-berth),Sleeper (3-berth)
class_id,seat (reclinig),seat (compartment),seat,couchette (4-berth),couchette (6-berth),capsule (seat/bed),capsule (bed),Sleeper (2-berth) with shower & WC,Sleeper (double) with shower & WC,Sleeper (3-berth) with shower & WC,Sleeper (2-berth),Sleeper (3-berth)
class_main,Seat,Seat,Seat,Couchette,Couchette,Capsule,Capsule,Sleeper,Sleeper,Sleeper,Sleeper,Sleeper

In [12]:
df=pd.read_json("routes.json")
df.to_csv("routes.csv",index=False)

C:\Users\scott\AppData\Local\Temp\ipykernel_32680\4261082.py:1: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df=pd.read_json("routes.json")

In [13]:
df

,1970-01-01 00:00:01,1970-01-01 00:00:02,1970-01-01 00:00:03,1970-01-01 00:00:04,1970-01-01 00:00:05,1970-01-01 00:00:06,1970-01-01 00:00:07,1970-01-01 00:00:08,1970-01-01 00:00:09,1970-01-01 00:00:10,...,1970-01-01 00:04:16,1970-01-01 00:04:17,1970-01-01 00:04:18,1970-01-01 00:04:20,1970-01-01 00:04:21,1970-01-01 00:04:22,1970-01-01 00:04:24,1970-01-01 00:04:25,1970-01-01 00:04:26,NaT
route_id,1,2,3,4,5,6,7,8,9,10,...,256,257,258,260,261,262,264,265,266,
agency_id,ÖBB,ÖBB,HŽPP,ČD,ÖBB,ZSSK,RJ,PKP/ČD,PKP/ČD,PKP,...,UEX,UEX,UZ,ÖBB,RJ,SNCF,SNCF,PKP/ČD,PKP/ČD,
agency_1,ÖBB,ÖBB,HŽPP,ČD,ÖBB,ZSSK,RJ,PKP,PKP,PKP,...,UEX,UEX,UZ,ÖBB,RJ,SNCF,SNCF,PKP,PKP,
agency_2,,,,,,,,ČD,ČD,,...,,,,,,,,ČD,ČD,
agency_3,,,,,,,,,,,...,,,,,,,,,,
route_short_name,NJ 40425 = NJ 40468,NJ 408 = NJ 409,1820 = 1821,EN 40476 = EN 40457,NJ 470 = NJ 471,EN 442 = EN 443,1020 = 1021,=,EN 443 / IC 406 = IC 407 / EN 442,TLK 35190/50191 = TLK 55190/53190,...,332/1372 = 333/1373,334/1374 = 335/1375,069 = 070,NJ 40424 = NJ 40469,1038 = 1039,IC Nuit 3789 = IC Nuit 3790,IC Nuit 3750 = IC Nuit 3751,TLK 403/50171 = TLK 55170/402,TLK 403 = TLK 402,
route_long_name,,,,Metropol,,Slovakia,,Carpathia,Chopin,Rozewie,...,,,,,,,,Wydmy,Wydmy,
route_desc,NJ 40425: Bruxelles Midi / Brussel Zuid - Brux...,NJ 408: Berlin Hbf - Berlin Südkreuz - Luthers...,1820: Split - Knin - Karlovac - Zagreb Gl. K. ...,EN 40476: Budapest-Nyugati - Vac - Štúrovo - N...,NJ 470: Zürich HB - Basel SBB - Basel Bad Bf -...,EN 442: Humenné - Strážske - Michalovce - Báno...,1020: Chop - Košice - Poprad Tatry - Pardubice...,: - - // : - -,EN 443 / IC 406: Praha hl.n. - Pardubice hl.n....,TLK 35190/50191: Kraków Gł. - Trzebinia - Gdań...,...,332/1372: Innsbruck Hbf - Jenbach - München Os...,334/1374: Villach Hbf - Salzburg Hbf - München...,069: Przemyśl Gł. - Lviv - Ternopil - Khmelnyt...,NJ 40424: Berlin Ostbahnhof - Berlin Hbf - Göt...,1038: Przemyśl Gł. - Kraków Gł. - Olomouc hl.n...,IC Nuit 3789: Paris Austerlitz - St-Denis-lès-...,IC Nuit 3750: Toulouse Matabiau - Montauban Vi...,TLK 403/50171: Bohumín - non-stop - Hel // TLK...,TLK 403: Bohumín - - Łeba // TLK 402: Łeba - ...,
route_type,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,
version,,,,,,,,,,,...,,,,2024,,,2024,,,
is_active,Y,Y,Y,Y,Y,Y,Y,Y,Y,N,...,Y,Y,Y,N,Y,Y,Y,Y,Y,
origin_trip_0,Bruxelles / Brussel,Berlin,Split,,Zürich,Humenné,Chop,#N/A,Praha,Kraków,...,Innsbruck,Villach,Przemyśl,Berlin,Przemyśl,Paris,Toulouse,Bohumín,Bohumín,
destination_trip_0,Wien,Zürich,Zagreb,Berlin,Hamburg,Praha,Praha,#N/A,Warszawa,Hel,...,Düsseldorf,Düsseldorf,Kremenchuk,Paris,Praha,Aurillac,Paris,Hel,Łeba,
distance,,,424,608,1011,745,672,,,,...,,,935,1168,740,602,714,,,
emissions,,,11.6,10.5,18,12.6,11.8,,,,...,,,17.88806,12.8,20.6,3.9,2.2,,,
classes,"seat, couchette, sleeper","seat, couchette, sleeper","seat, couchette, sleeper",sleeper,"seat, couchette, sleeper","seat, couchette, sleeper","seat, couchette, sleeper",,"seat, couchette, sleeper","seat, couchette, sleeper",...,"couchette, sleeper","couchette, sleeper",sleeper,"seat, couchette, sleeper","seat, couchette, sleeper","seat, couchette","seat, couchette",,,
countries,"BE, DE, AT","DE, CH",HR,"HU, CZ","DE, CH","SK, CZ","SK, CZ","CZ, PL","CZ, PL",PL,...,DE,DE,"PL, UA","DE, FR","PL, CZ",FR,FR,"CZ, PL","CZ, PL",
source,https://www.nightjet.com/,https://www.nightjet.com/,https://www.hzpp.hr/en/#,https://www.cd.cz/en/spojeni-a-jizdenka/,https://www.nightjet.com/,https://www.zssk.sk/en/night-trains/,https://regiojet.de/,https://www.intercity.pl/en/,https://www.intercity.pl/en/,https://www.intercity.pl/en/,...,https://buchung.urlaubs-express.de/,https://buchung.urlaubs-express.de/,https://booking.uz.gov.ua/en/,https://www.nightjet.com/,https://regiojet.de/,https://www.sncf-connect.com/en-en/,https://www.sncf-connect.com/en-en/,https://www.intercity.pl/en/,https://www.intercity.pl/en/,
source_interrail,,,,,,,,,,,...,,,,,,https://www.raileurope.com/,https://www.raileurope.com/,,,
picture,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,,,https://back-on-track.eu/wp-content/uploads/20...,,,,,,...,,,,https://back-on-track.eu/wp-content/uploads/20...,,,,,,
emissions_relation,,,,1:23,,,,,,,...,,,,,,,,,,

In [14]:
df=pd.read_json("stops.json")
df.to_csv("stops.csv",index=False)

In [15]:
df

,Baqël,Bishqem,Budull,Durrës,Elbasan,Fushë-Krujë,Golem,Han i Hotit,Ishëm,Kashar,...,Shëngjergj,Siperant,Sllatinë e lbrit,Soqanicë,Stagonë,Ujmirë,Vallaq,Vërrin,Vushtrri,Xërxë
stop_id,Baqël,Bishqem,Budull,Durrës,Elbasan,Fushë-Krujë,Golem,Han i Hotit,Ishëm,Kashar,...,Shëngjergj,Siperant,Sllatinë e lbrit,Soqanicë,Stagonë,Ujmirë,Vallaq,Vërrin,Vushtrri,Xërxë
stop_name,Baqël,Bishqem,Budull,Durrës,Elbasan,Fushë-Krujë,Golem,Han i Hotit,Ishëm,Kashar,...,Shëngjergj,Siperant,Sllatinë e lbrit,Soqanicë,Stagonë,Ujmirë,Vallaq,Vërrin,Vushtrri,Xërxë
stop_country,AL,AL,AL,AL,AL,AL,AL,AL,AL,AL,...,XK,XK,XK,XK,XK,XK,XK,XK,XK,XK
stop_timezone,CET,CET,CET,CET,CET,CET,CET,CET,CET,CET,...,CET,CET,CET,CET,CET,CET,CET,CET,CET,CET
stop_lat,41.894638,41.061859,41.453395,41.317826,41.111384,41.477588,41.257065,42.337282,41.53321,41.358356,...,42.602636,42.602636,42.847647,43.057619,42.602636,42.614526,42.946038,42.602636,42.826703,42.07911
stop_lon,19.647564,19.866112,19.666907,19.454608,20.082263,19.720476,19.526782,19.434463,19.610367,19.741205,...,20.902977,20.902977,20.963617,20.811097,20.902977,20.694908,20.831853,20.902977,20.970349,20.683937
location_type,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
stop_name_romanized,,,,,,,,,,,...,,,,,,,,,,
stop_name_alt,,,,,,,,,,,...,,,,,,,,,,
stop_cityname,,,,,,,,,,,...,,,,,,,,,,
stop_cityname_romanized,,,,,,,,,,,...,,,,,,,,,,
stop_cityname_alt,,,,,,,,,,,...,,,,,,,,,,
stop_tariffname,,,,,,,,,,,...,Station,Halt stat.,Station,Halt stat.,Halt stat.,Halt stat.,Station,Halt stat.,Station,Station
stop_charge,,,,,,,,,,,...,,,,,,,,,,
stop_uic_code,,,,,,,,,,,...,,,,,,,,,,
stop_code,,,,,,,,,,,...,,,,,,,,,,
stop_region,,,,,,,,,,,...,,,,,,,,,,

In [16]:
df=pd.read_json("translations.json")
df.to_csv("translations.csv",index=False)
er=pd.read_json("trip_stop.json")
er.to_csv("trip_stop.csv",index=False)
de=pd.read_json("trips.json")
de.to_csv("trips.csv",index=False)
rf=pd.read_json("view_ontd_cities.json")
rf.to_csv("view_ontd_cities.csv",index=False)
gy=pd.read_csv("view_ontd_details.json")
gy.to_csv("view_ontd_details.csv",index=False)
ui=pd.read_json("view_ontd_list.json")
ui.to_csv("view_ontd_list.csv",index=False)
jx=pd.read_json("view_ontd_map.json")
jx.to_csv("view_ontd_map.csv",index=False)

C:\Users\scott\AppData\Local\Temp\ipykernel_32680\3879518752.py:11: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  ui=pd.read_json("view_ontd_list.json")
C:\Users\scott\AppData\Local\Temp\ipykernel_32680\3879518752.py:11: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  ui=pd.read_json("view_ontd_list.json")
C:\Users\scott\AppData\Local\Temp\ipykernel_32680\3879518752.py:11: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  ui=pd.read_json("view_ontd_list.json")

In [20]:
import pandas as pd
import sqlite3
import json
import os

json_dir = r"c:\Users\scott\Desktop\epsi\github\MsprDS\csv\nuit\night-train-data\data\latest"
db_path = r"c:\Users\scott\Documents\MSPR1\MsprDS\bdd\trajetsFerroviairesBDD.db"


conn = sqlite3.connect(db_path)

for file in os.listdir(json_dir):
    if file.endswith(".json"):
        json_path = os.path.join(json_dir, file)
        table_name = os.path.splitext(file)[0]

        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        df = pd.json_normalize(data)
        df.to_sql(table_name, conn, if_exists="replace", index=False)
        print(f"✓ {file} → table '{table_name}' ({len(df)} lignes)")

conn.close()
print("Terminé !")

✓ agencies.json → table 'agencies' (1 lignes)
✓ calendar.json → table 'calendar' (1 lignes)
✓ calendar_dates.json → table 'calendar_dates' (1 lignes)

JSONDecodeError: Extra data: line 1 column 2 (char 1)

In [21]:
import pandas as pd
import sqlite3
import os

json_dir = r"c:\Users\scott\Desktop\epsi\github\MsprDS\csv\nuit\night-train-data\data\latest"
db_path = r"c:\Users\scott\Documents\MSPR1\MsprDS\bdd\trajetsFerroviairesBDD.db"

conn = sqlite3.connect(db_path)

for file in os.listdir(json_dir):
    if file.endswith(".json"):
        json_path = os.path.join(json_dir, file)
        table_name = os.path.splitext(file)[0]

        try:
            # Les JSON sont transposés : les clés sont les colonnes
            df = pd.read_json(json_path).T
            df.to_sql(table_name, conn, if_exists="replace", index=True, index_label="id")
            print(f"✓ {file} → table '{table_name}' ({len(df)} lignes)")
        except Exception as e:
            print(f"✗ {file} → Erreur : {e}")

conn.close()
print("Terminé !")

✗ agencies.json → Erreur : Empty table or column name specified
✓ calendar.json → table 'calendar' (110 lignes)
✓ calendar_dates.json → table 'calendar_dates' (59 lignes)
✗ calendrier_dates.json → Erreur : Trailing data
✓ classes.json → table 'classes' (12 lignes)
✓ routes.json → table 'routes' (207 lignes)
Terminé !

C:\Users\scott\AppData\Local\Temp\ipykernel_32680\681867399.py:17: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df = pd.read_json(json_path).T

In [22]:
import pandas as pd
import sqlite3

db_path = r"c:\Users\scott\Documents\MSPR1\MsprDS\bdd\trajetsFerroviairesBDD.db"
json_dir = r"c:\Users\scott\Desktop\epsi\github\MsprDS\csv\nuit\night-train-data\data\latest"

conn = sqlite3.connect(db_path)

# 1) agencies.json — supprimer la colonne vide
df_agencies = pd.read_json(f"{json_dir}/agencies.json").T
df_agencies = df_agencies.loc[:, df_agencies.columns != ""]  # supprime la colonne vide
df_agencies.to_sql("agencies", conn, if_exists="replace", index=True, index_label="id")
print(f"✓ agencies → {len(df_agencies)} lignes")

# 2) calendrier_dates — c'est un CSV, pas un JSON
df_cal = pd.read_csv(f"{json_dir}/calendrier_dates.json", header=None)
df_cal.columns = ["UID", "train_id", "service_id", "date", "date_from", "date_until", "exception_type"]
df_cal.to_sql("calendrier_dates", conn, if_exists="replace", index=False)
print(f"✓ calendrier_dates → {len(df_cal)} lignes")

conn.close()
print("Terminé !")

✓ agencies → 30 lignes

ValueError: Length mismatch: Expected axis has 59 elements, new values have 7 elements

In [23]:
import sqlite3
import pandas as pd
import os

# Modifier ce chemin selon votre environnement
DOSSIER = "."  # Dossier contenant les CSV et la BD
DB_PATH = os.path.join(DOSSIER, "rail_europe.db")

# Mapping fichier CSV -> nom de table
FICHIERS_CSV = {
    "agencies.csv":          "agencies",
    "calendrier.csv":        "calendrier",
    "calendrier_dates.csv":  "calendrier_dates",
    "classes.csv":           "classes",
    "routes.csv":            "routes",
    "stops.csv":             "stops",
    "translations.csv":      "translations",
    "trip_stop.csv":         "trip_stop",
    "trips.csv":             "trips",
    "view_ontd_cities.csv":  "view_ontd_cities",
    "view_ontd_details.csv": "view_ontd_details",
    "view_ontd_list.csv":    "view_ontd_list",
    "view_ontd_map.csv":     "view_ontd_map",
}

print(f"Base de données : {os.path.abspath(DB_PATH)}")
print(f"Dossier source  : {os.path.abspath(DOSSIER)}")
print(f"Fichiers à importer : {len(FICHIERS_CSV)}")

Base de données : c:\Users\scott\Desktop\epsi\github\MsprDS\csv\nuit\night-train-data\data\latest\rail_europe.db
Dossier source  : c:\Users\scott\Desktop\epsi\github\MsprDS\csv\nuit\night-train-data\data\latest
Fichiers à importer : 13

In [24]:
# Vérifier que tous les fichiers sont présents
for fichier in FICHIERS_CSV:
    chemin = os.path.join(DOSSIER, fichier)
    if os.path.exists(chemin):
        taille = os.path.getsize(chemin)
        print(f"  ✓ {fichier:30s} ({taille:>10,} octets)")
    else:
        print(f"  ✗ {fichier:30s} INTROUVABLE")

# Vérifier la BD
if os.path.exists(DB_PATH):
    print(f"\n  ✓ Base de données trouvée ({os.path.getsize(DB_PATH):,} octets)")
else:
    print(f"\n  ℹ Base de données sera créée : {DB_PATH}")

  ✓ agencies.csv                   (     4,751 octets)
  ✓ calendrier.csv                 (    11,141 octets)
  ✓ calendrier_dates.csv           (     4,730 octets)
  ✓ classes.csv                    (       602 octets)
  ✓ routes.csv                     (    84,784 octets)
  ✓ stops.csv                      ( 3,033,498 octets)
  ✓ translations.csv               (       113 octets)
  ✓ trip_stop.csv                  (   308,255 octets)
  ✓ trips.csv                      (   246,296 octets)
  ✓ view_ontd_cities.csv           (    37,595 octets)
  ✓ view_ontd_details.csv          (   332,489 octets)
  ✓ view_ontd_list.csv             (    66,285 octets)
  ✓ view_ontd_map.csv              (    67,054 octets)

  ✓ Base de données trouvée (897,024 octets)

In [25]:
# Aperçu rapide de chaque fichier
for fichier, table in FICHIERS_CSV.items():
    chemin = os.path.join(DOSSIER, fichier)
    if not os.path.exists(chemin):
        continue
    df = pd.read_csv(chemin, nrows=3, encoding="utf-8")
    print(f"\n{'='*60}")
    print(f"{fichier} → table '{table}' | {len(df.columns)} colonnes")
    print(f"Colonnes : {list(df.columns)}")
    display(df.head(3))

============================================================
agencies.csv → table 'agencies' | 30 colonnes
Colonnes : ['ATC', 'BDŽ', 'ČD', 'CFM', 'CFR', 'CS', 'ES', 'FS', 'GA', 'GWR', 'HŽPP', 'MÁV', 'MT', 'ÖBB', 'OTE', 'PKP', 'RDC', 'RJ', 'SJ', 'SJN', 'SNCF', 'ST', 'TCDD', 'UEX', 'UZ', 'VR', 'VY', 'ŽPCG', 'ŽS', 'ZSSK']

,ATC,BDŽ,ČD,CFM,CFR,CS,ES,FS,GA,GWR,...,SNCF,ST,TCDD,UEX,UZ,VR,VY,ŽPCG,ŽS,ZSSK
0,ATC,BDŽ,ČD,CFM,CFR,CS,ES,FS,GA,GWR,...,SNCF,ST,TCDD,UEX,UZ,VR,VY,ŽPCG,ŽS,ZSSK
1,Astra Trans Carpatic SRL,БДЖ - Пътнически превози ЕООД,České dráhy a.s.,Calea Ferată din Moldova,C.F.R. Călători S.A.,Caledonian Sleeper Ltd.,European Sleeper Cooperatïe,Trenitalia S.p.A,Go-Ahead Norge AS,First Greater Western Ltd.,...,SNCF Voyageurs SA,Merresor AB,TCDD Taşımacılık A.Ş.,Train4you Vertriebs GmbH,Укрзалізниця,VR-Yhtymä Oy,Vygruppen AS,Željeznički prevoz Crne Gore AD,Железнице Србије ад,Železničná spoločnosť Slovensko a.s.
2,https://astratranscarpatic.ro,https://www.bdz.bg,https://www.cd.cz,http://railway.md,https://www.cfrcalatori.ro,https://www.sleeper.scot,https://www.europeansleeper.eu,https://www.trenitalia.com,https://go-aheadnordic.com,https://www.gwr.com,...,https://www.sncf.com,https://www.snalltaget.se,https://www.tcddtasimacilik.gov.tr/,https://buchung.urlaubs-express.de/,https://www.uz.gov.ua/,https://www.vr.fi,https://www.vy.no,https://www.zcg-prevoz.me,https://srbijavoz.rs,https://www.zssk.sk

============================================================
calendrier.csv → table 'calendrier' | 110 colonnes
Colonnes : ['-- 2024 -- ', 'Daily', '0-2 days/week (May-Oct)', '2024/03/31-2024/11/03: Mon, Tue, Wed, Thu, Fri, Sun', '2024: Mon, Tue, Wed, Thu, Fri', '2024: Mon, Tue, Wed, Thu, Sun', '2024: Daily except Sat', '2024: 1-5,7', 'Mon, Wed, Fri', '2024/07/08-2024/09/22: Mon, Wed, Sat', '2024: Tue, Thu', '2024: Tue, Sun', 'Tue, Wed, Fri', 'Tue, Thu, Sat', 'Tue, Thu, Sun', '2024/07/07-2024/09/21: Tue, Fri, Sun', 'Thu, Sat', '2023/12/22-2024/03/28: Fri', 'Fri, Sat', '2023/12/30- 2024/03/30: Sat', '2024: Tue, Thu, Sat, Sun', '2024: 3-4 times per week', '2024: every 2nd day', 'Sat, Sun', 'Fri, Sun (daily in holidays in région C)', 'Sun (Oct-Jun)', 'Fri (May-Oct)', 'Fri (Sep-Jun)', 'Daily (Jul-Aug)', 'Daily (May-Sep)', '2023/12/16-2024/04/27: Wed, Sat', 'Wed, Fri, Sat', 'Thu, Sat, Sun', '2023/12/17-2024/04/27: Thu, Sun', 'Wed, Sat', 'Mon, Thu, Sat', 'Wed, Fri, Sun', '2024: Wed, Sat, Sun (every 2nd week)', '2024: Mon, Wed, Thu (every 2nd week)', 'Fri', 'Fri, Sun', '2023/12/23-2024/03/29: Sat', 'Sun', '2024/06/05-2024/10/05: Daily', '2024/06/14-2024/09/07: Daily', '2024/06/15-2024/09/08: Daily', '2024/06/22-2024/09/01: Daily', '2024/06/29-2024/09/07: Daily', '2024/05/03-2024/10/02: Wed, Fri, Sun', '2024/05/04-2024/10/03: Mon, Thu, Sat', '-- 2025 --', '2025: Daily', '2025: Mon, Wed, Thu', '2025: Mon, Wed, Fri', '2025: Mon, Thu, Sat', '2025: Tue, Thu, Sat', '2025: Tue, Thu, Sun', '2025: Wed, Fri, Sat', '2025: Wed, Fri, Sun', '2025: Wed, Sat', '2025: Wed, Sat, Sun', '2025: Thu, Sat, Sun', '2025: Thu, Sun', '2025: Fri', '2025: Fri, Sat', '2025: Fri, Sun', '2025: Sat, Sun', '2025: Sun', '2025/05-09: Daily', '2024/10-2025/06: Fri', '2024/10-2025/06: Sun', '2025/06/25-09/27: Wed, Sat', '2025/06/26-09/28: Thu, Sun', '2025/05/05-2025/10/04: Mon, Thu, Sat', '2025/05/07-2025/10/05: Wed, Fri, Sun', '-- 2026 -- ', '2026: Daily', '2026: Daily, except Saturday', '2026: Mon, Wed, Thu', '2026: Mon, Wed, Fri', '2026: Mon, Thu, Sat', '2026: Tue, Thu, Sat', '2026: Tue, Thu, Sun', '2026: Wed, Fri, Sat', '2026: Wed, Fri, Sun', '2026: Wed, Sat', '2026: Wed, Sat, Sun', '2026: Thu, Sat, Sun', '2026: Thu, Sun', '2026: Fri', '2026: Fri, Sat', '2026: Fri, Sun', '2026: Sat, Sun', '2026: Sun', '2026: Every 2nd day', '2026/05-09: Daily', '2026/06-2026/10: Fri', '2026/06-2026/10: Sun', '2026/06/25-09/27: Wed, Sat', '2026/06/26-09/28: Thu, Sun', '2026/06/11-09/06: Daily', 'Unknown', '2026/06/27-2026/08/31: Daily', '2026/06/26-2026/08/30: Daily', '2026: Tue, Thu', '2026: Mon, Wed, Thu, Fri, Sat', '2026: Mon, Wed, Fri, Sat, Son', '2026: Thu, Sat', '2026: Sat', '2026: Tue']

,-- 2024 --,Daily,0-2 days/week (May-Oct),"2024/03/31-2024/11/03: Mon, Tue, Wed, Thu, Fri, Sun","2024: Mon, Tue, Wed, Thu, Fri","2024: Mon, Tue, Wed, Thu, Sun",2024: Daily except Sat,"2024: 1-5,7","Mon, Wed, Fri","2024/07/08-2024/09/22: Mon, Wed, Sat",...,2026/06/11-09/06: Daily,Unknown,2026/06/27-2026/08/31: Daily,2026/06/26-2026/08/30: Daily,"2026: Tue, Thu","2026: Mon, Wed, Thu, Fri, Sat","2026: Mon, Wed, Fri, Sat, Son","2026: Thu, Sat",2026: Sat,2026: Tue
0,-- 2024 --,Daily,0-2 days/week (May-Oct),"2024/03/31-2024/11/03: Mon, Tue, Wed, Thu, Fri...","2024: Mon, Tue, Wed, Thu, Fri","2024: Mon, Tue, Wed, Thu, Sun",2024: Daily except Sat,"2024: 1-5,7","Mon, Wed, Fri","2024/07/08-2024/09/22: Mon, Wed, Sat",...,2026/06/11-09/06: Daily,Unknown,2026/06/27-2026/08/31: Daily,2026/06/26-2026/08/30: Daily,"2026: Tue, Thu","2026: Mon, Wed, Thu, Fri, Sat","2026: Mon, Wed, Fri, Sat, Son","2026: Thu, Sat",2026: Sat,2026: Tue
1,NaN,1,0,1,1,1,1,1,1,0,...,1,NaN,1,1,0,1,1,0,0,0
2,NaN,1,0,1,1,1,1,1,0,1,...,1,NaN,1,1,1,0,0,0,0,1

============================================================
calendrier_dates.csv → table 'calendrier_dates' | 59 colonnes
Colonnes : ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59']

,1,2,3,4,5,6,7,8,9,10,...,50,51,52,53,54,55,56,57,58,59
0,1,2,3,4,5,6,7,8,9,10,...,50,51,52,53,54,55,56,57,58,59
1,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,...,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,PKP/ČD EN 40416,PKP/ČD EN 40417,PKP/ČD EN 406,PKP/ČD EN 407
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"2024/05/03-2024/10/02: Wed, Fri, Sun","2024/05/03-2024/10/02: Wed, Fri, Sun","2024/05/03-2024/10/02: Wed, Fri, Sun","2024/05/03-2024/10/02: Wed, Fri, Sun","2024/05/03-2024/10/02: Wed, Fri, Sun","2024/05/03-2024/10/02: Wed, Fri, Sun",2026: Daily,2026: Daily,2026: Daily,2026: Daily

============================================================
classes.csv → table 'classes' | 12 colonnes
Colonnes : ['seat (reclinig)', 'seat (compartment)', 'seat ', 'couchette (4-berth)', 'couchette (6-berth)', 'capsule (seat/bed)', 'capsule (bed)', 'Sleeper (2-berth) with shower & WC', 'Sleeper (double) with shower & WC', 'Sleeper (3-berth) with shower & WC', 'Sleeper (2-berth)', 'Sleeper (3-berth)']

,seat (reclinig),seat (compartment),seat,couchette (4-berth),couchette (6-berth),capsule (seat/bed),capsule (bed),Sleeper (2-berth) with shower & WC,Sleeper (double) with shower & WC,Sleeper (3-berth) with shower & WC,Sleeper (2-berth),Sleeper (3-berth)
0,seat (reclinig),seat (compartment),seat,couchette (4-berth),couchette (6-berth),capsule (seat/bed),capsule (bed),Sleeper (2-berth) with shower & WC,Sleeper (double) with shower & WC,Sleeper (3-berth) with shower & WC,Sleeper (2-berth),Sleeper (3-berth)
1,Seat,Seat,Seat,Couchette,Couchette,Capsule,Capsule,Sleeper,Sleeper,Sleeper,Sleeper,Sleeper

============================================================
routes.csv → table 'routes' | 207 colonnes
Colonnes : ['1970-01-01 00:00:01', '1970-01-01 00:00:02', '1970-01-01 00:00:03', '1970-01-01 00:00:04', '1970-01-01 00:00:05', '1970-01-01 00:00:06', '1970-01-01 00:00:07', '1970-01-01 00:00:08', '1970-01-01 00:00:09', '1970-01-01 00:00:10', '1970-01-01 00:00:11', '1970-01-01 00:00:12', '1970-01-01 00:00:13', '1970-01-01 00:00:14', '1970-01-01 00:00:15', '1970-01-01 00:00:17', '1970-01-01 00:00:18', '1970-01-01 00:00:19', '1970-01-01 00:00:20', '1970-01-01 00:00:21', '1970-01-01 00:00:22', '1970-01-01 00:00:23', '1970-01-01 00:00:24', '1970-01-01 00:00:25', '1970-01-01 00:00:26', '1970-01-01 00:00:27', '1970-01-01 00:00:28', '1970-01-01 00:00:30', '1970-01-01 00:00:31', '1970-01-01 00:00:37', '1970-01-01 00:00:38', '1970-01-01 00:00:39', '1970-01-01 00:00:40', '1970-01-01 00:00:41', '1970-01-01 00:00:42', '1970-01-01 00:00:44', '1970-01-01 00:00:45', '1970-01-01 00:00:46', '1970-01-01 00:00:47', '1970-01-01 00:00:48', '1970-01-01 00:00:49', '1970-01-01 00:00:50', '1970-01-01 00:00:53', '1970-01-01 00:00:54', '1970-01-01 00:00:57', '1970-01-01 00:00:58', '1970-01-01 00:00:59', '1970-01-01 00:01:00', '1970-01-01 00:01:01', '1970-01-01 00:01:02', '1970-01-01 00:01:03', '1970-01-01 00:01:05', '1970-01-01 00:01:06', '1970-01-01 00:01:07', '1970-01-01 00:01:08', '1970-01-01 00:01:09', '1970-01-01 00:01:10', '1970-01-01 00:01:11', '1970-01-01 00:01:12', '1970-01-01 00:01:13', '1970-01-01 00:01:14', '1970-01-01 00:01:16', '1970-01-01 00:01:17', '1970-01-01 00:01:18', '1970-01-01 00:01:19', '1970-01-01 00:01:20', '1970-01-01 00:01:21', '1970-01-01 00:01:23', '1970-01-01 00:01:24', '1970-01-01 00:01:25', '1970-01-01 00:01:26', '1970-01-01 00:01:28', '1970-01-01 00:01:30', '1970-01-01 00:01:31', '1970-01-01 00:01:36', '1970-01-01 00:01:37', '1970-01-01 00:01:38', '1970-01-01 00:01:39', '1970-01-01 00:01:40', '1970-01-01 00:01:41', '1970-01-01 00:01:42', '1970-01-01 00:01:43', '1970-01-01 00:01:44', '1970-01-01 00:01:45', '1970-01-01 00:01:46', '1970-01-01 00:01:47', '1970-01-01 00:01:48', '1970-01-01 00:01:49', '1970-01-01 00:01:50', '1970-01-01 00:01:51', '1970-01-01 00:01:52', '1970-01-01 00:01:54', '1970-01-01 00:01:55', '1970-01-01 00:01:56', '1970-01-01 00:01:57', '1970-01-01 00:01:58', '1970-01-01 00:01:59', '1970-01-01 00:02:00', '1970-01-01 00:02:01', '1970-01-01 00:02:02', '1970-01-01 00:02:03', '1970-01-01 00:02:04', '1970-01-01 00:02:05', '1970-01-01 00:02:06', '1970-01-01 00:02:07', '1970-01-01 00:02:08', '1970-01-01 00:02:09', '1970-01-01 00:02:10', '1970-01-01 00:02:11', '1970-01-01 00:02:12', '1970-01-01 00:02:13', '1970-01-01 00:02:14', '1970-01-01 00:02:15', '1970-01-01 00:02:16', '1970-01-01 00:02:17', '1970-01-01 00:02:18', '1970-01-01 00:02:19', '1970-01-01 00:02:20', '1970-01-01 00:02:21', '1970-01-01 00:02:22', '1970-01-01 00:02:27', '1970-01-01 00:02:29', '1970-01-01 00:02:30', '1970-01-01 00:02:31', '1970-01-01 00:02:32', '1970-01-01 00:02:33', '1970-01-01 00:02:34', '1970-01-01 00:02:35', '1970-01-01 00:02:36', '1970-01-01 00:02:37', '1970-01-01 00:02:38', '1970-01-01 00:02:41', '1970-01-01 00:02:42', '1970-01-01 00:02:44', '1970-01-01 00:02:46', '1970-01-01 00:02:47', '1970-01-01 00:02:48', '1970-01-01 00:02:50', '1970-01-01 00:02:52', '1970-01-01 00:02:53', '1970-01-01 00:02:54', '1970-01-01 00:02:55', '1970-01-01 00:02:57', '1970-01-01 00:02:58', '1970-01-01 00:03:00', '1970-01-01 00:03:01', '1970-01-01 00:03:02', '1970-01-01 00:03:03', '1970-01-01 00:03:05', '1970-01-01 00:03:06', '1970-01-01 00:03:09', '1970-01-01 00:03:10', '1970-01-01 00:03:11', '1970-01-01 00:03:15', '1970-01-01 00:03:16', '1970-01-01 00:03:17', '1970-01-01 00:03:18', '1970-01-01 00:03:19', '1970-01-01 00:03:20', '1970-01-01 00:03:21', '1970-01-01 00:03:23', '1970-01-01 00:03:27', '1970-01-01 00:03:28', '1970-01-01 00:03:29', '1970-01-01 00:03:30', '1970-01-01 00:03:31', '1970-01-01 00:03:32', '1970-01-01 00:03:33', '1970-01-01 00:03:38', '1970-01-01 00:03:39', '1970-01-01 00:03:40', '1970-01-01 00:03:41', '1970-01-01 00:03:42', '1970-01-01 00:03:43', '1970-01-01 00:03:44', '1970-01-01 00:03:45', '1970-01-01 00:03:47', '1970-01-01 00:03:49', '1970-01-01 00:03:52', '1970-01-01 00:03:53', '1970-01-01 00:03:55', '1970-01-01 00:03:57', '1970-01-01 00:03:58', '1970-01-01 00:03:59', '1970-01-01 00:04:00', '1970-01-01 00:04:03', '1970-01-01 00:04:05', '1970-01-01 00:04:06', '1970-01-01 00:04:07', '1970-01-01 00:04:08', '1970-01-01 00:04:09', '1970-01-01 00:04:10', '1970-01-01 00:04:11', '1970-01-01 00:04:12', '1970-01-01 00:04:13', '1970-01-01 00:04:14', '1970-01-01 00:04:15', '1970-01-01 00:04:16', '1970-01-01 00:04:17', '1970-01-01 00:04:18', '1970-01-01 00:04:20', '1970-01-01 00:04:21', '1970-01-01 00:04:22', '1970-01-01 00:04:24', '1970-01-01 00:04:25', '1970-01-01 00:04:26', 'Unnamed: 206']

,1970-01-01 00:00:01,1970-01-01 00:00:02,1970-01-01 00:00:03,1970-01-01 00:00:04,1970-01-01 00:00:05,1970-01-01 00:00:06,1970-01-01 00:00:07,1970-01-01 00:00:08,1970-01-01 00:00:09,1970-01-01 00:00:10,...,1970-01-01 00:04:16,1970-01-01 00:04:17,1970-01-01 00:04:18,1970-01-01 00:04:20,1970-01-01 00:04:21,1970-01-01 00:04:22,1970-01-01 00:04:24,1970-01-01 00:04:25,1970-01-01 00:04:26,Unnamed: 206
0,1,2,3,4,5,6,7,8,9,10,...,256,257,258,260,261,262,264,265,266,NaN
1,ÖBB,ÖBB,HŽPP,ČD,ÖBB,ZSSK,RJ,PKP/ČD,PKP/ČD,PKP,...,UEX,UEX,UZ,ÖBB,RJ,SNCF,SNCF,PKP/ČD,PKP/ČD,NaN
2,ÖBB,ÖBB,HŽPP,ČD,ÖBB,ZSSK,RJ,PKP,PKP,PKP,...,UEX,UEX,UZ,ÖBB,RJ,SNCF,SNCF,PKP,PKP,NaN

============================================================
stops.csv → table 'stops' | 28771 colonnes

,Baqël,Bishqem,Budull,Durrës,Elbasan,Fushë-Krujë,Golem,Han i Hotit,Ishëm,Kashar,...,Shëngjergj,Siperant,Sllatinë e lbrit,Soqanicë,Stagonë,Ujmirë,Vallaq,Vërrin,Vushtrri,Xërxë
0,Baqël,Bishqem,Budull,Durrës,Elbasan,Fushë-Krujë,Golem,Han i Hotit,Ishëm,Kashar,...,Shëngjergj,Siperant,Sllatinë e lbrit,Soqanicë,Stagonë,Ujmirë,Vallaq,Vërrin,Vushtrri,Xërxë
1,Baqël,Bishqem,Budull,Durrës,Elbasan,Fushë-Krujë,Golem,Han i Hotit,Ishëm,Kashar,...,Shëngjergj,Siperant,Sllatinë e lbrit,Soqanicë,Stagonë,Ujmirë,Vallaq,Vërrin,Vushtrri,Xërxë
2,AL,AL,AL,AL,AL,AL,AL,AL,AL,AL,...,XK,XK,XK,XK,XK,XK,XK,XK,XK,XK

============================================================
translations.csv → table 'translations' | 2 colonnes
Colonnes : ['agency', 'stops']

        agency          stops
0       agency          stops
1  agency_name  stop_cityname
2           en             fr

============================================================
trip_stop.csv → table 'trip_stop' | 3440 colonnes

,ATC IR 11500:0,ATC IR 11500:1,ATC IR 11500:2,ATC IR 11500:3,ATC IR 11500:4,ATC IR 11500:5,ATC IR 11500:6,ATC IR 11500:7,ATC IR 11500:99,Unnamed: 9,...,ZSSK EN 1153:1,ZSSK EN 1153:2,ZSSK EN 1153:3,ZSSK EN 1153:4,ZSSK EN 1153:5,ZSSK EN 1153:6,ZSSK EN 1153:7,ZSSK EN 1153:8,ZSSK EN 1153:9,ZSSK EN 1153:99
0,ATC IR 11500:0,ATC IR 11500:1,ATC IR 11500:2,ATC IR 11500:3,ATC IR 11500:4,ATC IR 11500:5,ATC IR 11500:6,ATC IR 11500:7,ATC IR 11500:99,NaN,...,ZSSK EN 1153:1,ZSSK EN 1153:2,ZSSK EN 1153:3,ZSSK EN 1153:4,ZSSK EN 1153:5,ZSSK EN 1153:6,ZSSK EN 1153:7,ZSSK EN 1153:8,ZSSK EN 1153:9,ZSSK EN 1153:99
1,ATC IR 11500,ATC IR 11500,ATC IR 11500,ATC IR 11500,ATC IR 11500,ATC IR 11500,ATC IR 11500,ATC IR 11500,ATC IR 11500,NaN,...,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153
2,0,1,2,3,4,5,6,7,99,NaN,...,1,2,3,4,5,6,7,8,9,99

============================================================
trips.csv → table 'trips' | 410 colonnes
Colonnes : ['ATC IR 11501', 'ATC IR 11500', 'BDŽ 2626', 'BDŽ 2627', 'BDŽ 2636', 'BDŽ 2637', 'BDŽ 3636', 'BDŽ 3637', 'BDŽ 3686', 'BDŽ 3687', 'BDŽ 8626', 'BDŽ 8627', 'BDŽ 8656', 'BDŽ 8657', 'BDŽ 9646', 'BDŽ 9647', 'ČD EC 458', 'ČD EN 40459', 'ČD EN 40476', 'ČD EN 40457', 'CFR/MÁV IRN / IC 78', 'CFR/MÁV IRN / IC 79', 'CFR/MÁV IC 406', 'CFR/MÁV IC 407', 'CFR/MÁV/ÖBB D 346', 'CFR/MÁV/ÖBB D 347', 'CFR IC 472', 'CFR IC 473', 'CFR R 4116', 'CFR 1641/R 4112', 'CFR R-E 4007/1642', 'CFR 1641/R-E 4008', 'CFR 1641 (CN)', 'CFR 1642 (CN)', 'CFR 1641 (SM)', 'CFR 1642 (SM)', 'CFR 1653', 'CFR 1654', 'CFR 1667', 'CFR 1668', 'CFR 78/1743', 'CFR 1744/79', 'CFR 1763', 'CFR 1765', 'CFR 1821', 'CFR 1822', 'CFR 1837', 'CFR 1838', 'CFR 1920', 'CFR 1922', 'CFR 1941', 'CFR 1942/R 8810', 'CFR 1952', 'CFR 1954', 'CFM/CFR 401', 'CFM/CFR 402', 'CS 1001 (A)', 'CS 1002 (A)', 'CS 1001 (FW)', 'CS 1002 (FW)', 'CS 1001 (I)', 'CS 1002 (I)', 'CS 1003 (G)', 'CS 1004 (G)', 'CS 1003 (E)', 'CS 1004 (E)', 'ES 452', 'ES 453', 'ES 496', 'ES 497', 'ES 454', 'ES 455', 'ES 456', 'ES 457', 'FS IC Notte 1954', 'FS IC Notte 1955 (P)', 'FS IC Notte 1958', 'FS IC Notte 1959 (P)', 'FS IC Notte 1955 (S)', 'FS IC Notte 1956', 'FS IC Notte 1959 (S)', 'FS IC Notte 1960', 'FS IC Notte 1962', 'FS IC Notte 1963', 'FS IC Notte 1964', 'FS IC Notte 1967', 'FS IC Notte 752', 'FS IC Notte 755', 'FS IC Notte 754', 'FS IC Notte 757', 'FS IC Notte 758', 'FS IC Notte 765', 'FS IC Notte 763', 'FS IC Notte 764', 'FS IC Notte 770', 'FS IC Notte 774', 'FS IC Notte 788', 'FS IC Notte 789', 'FS IC Notte 794', 'FS IC Notte 795', 'FS IC Notte 796', 'FS IC Notte 1515', 'FS IC Notte 797', 'FS IC Notte 798', 'GA F5 725', 'GA F5 726', 'GWR Sleeper (Penzance)', 'GWR Sleeper (London)', 'HŽPP 1820', 'HŽPP 1821', 'HŽPP 1840', 'HŽPP 1841', 'HŽPP 1880', 'HŽPP 1881', 'HŽPP/ÖBB EN 414', 'HŽPP/ÖBB EN 40237', 'HŽPP/ÖBB EN 40414', 'HŽPP/ÖBB EN 40465', 'MÁV EN 40457', 'MÁV EN 40476', 'MÁV 1246 / 1605', 'MÁV 1604 / 1247', 'MÁV 1246 / 1605 / 481', 'MÁV 480 / 1604 / 1247', 'MÁV IC 1204', 'MÁV IC 1205', 'MÁV/ÖBB EN 40462', 'MÁV/ÖBB EN 40467', 'MÁV/ÖBB EN 50237', 'MÁV/ÖBB EN 50462', 'MÁV/PKP IC 407 / EN 477', 'MÁV/PKP EN 476', 'ÖBB NJ 236', 'ÖBB NJ 237', 'ÖBB NJ 294', 'ÖBB NJ 295', 'ÖBB NJ 402', 'ÖBB NJ 403', 'ÖBB NJ 40233', 'ÖBB NJ 40294', 'ÖBB NJ 40236', 'ÖBB NJ 40466', 'ÖBB NJ 40420', 'ÖBB NJ 40491', 'ÖBB NJ 40421', 'ÖBB NJ 40490', 'ÖBB NJ 40424', 'ÖBB NJ 40469', 'ÖBB NJ 408', 'ÖBB NJ 409', 'ÖBB NJ 420', 'ÖBB NJ 421', 'ÖBB NJ 40425', 'ÖBB NJ 40468', 'ÖBB NJ 446', 'ÖBB NJ 447', 'ÖBB NJ 456', 'ÖBB NJ 457', 'ÖBB NJ 464', 'ÖBB NJ 465', 'ÖBB NJ 470', 'ÖBB NJ 471', 'ÖBB NJ 490', 'ÖBB NJ 491', 'OTE 141', 'OTE 154', 'PKP IC 440', 'PKP IC 82170', 'PKP EN 430 / IC 440', 'PKP IC 82170 / EC 431', 'PKP IC 38172', 'PKP IC 83172', 'PKP TLK 35190', 'PKP TLK 53190', 'PKP/ČD EN 443 / IC 406', 'PKP/ČD IC 407 / EN 442', 'PKP TLK 48190', 'PKP TLK 84190', 'PKP IC 16170', 'PKP IC 61170', 'PKP TLK 35170', 'PKP TLK 53170', 'PKP TLK 35190/50191', 'PKP TLK 55190/53190', 'PKP TLK 38170', 'PKP TLK 83170', 'PKP TLK 48190/38194', 'PKP TLK 83194/84190', 'PKP/ČD EN 40416', 'PKP/ČD EN 40417', 'PKP/ČD EC 460', 'PKP/ČD EC 461', 'PKP/ČD EN 406', 'PKP/ČD EN 407', 'PKP/ČD TLK 403/50171', 'PKP/ČD TLK 55170/402', 'PKP/ČD TLK 403', 'PKP/ČD TLK 402', 'RJ 1020', 'RJ 1021', 'RJ 1038', 'RJ 1039', 'SJ 1', 'SJ 2', 'SJ EN 345', 'SJ EN 346', 'SJ 70 (D)', 'SJ 71 (S)', 'SJ 70 (U)', 'SJ 77 (S)', 'SJ Nattåg 91', 'SJ Nattåg 92', 'SJ Nattåg 93 (L)', 'SJ Nattåg 94 (L)', 'SJ Nattåg 93 (N)', 'SJ Nattåg 94 (N)', 'SJN 405', 'SJN 406', 'SJN 475', 'SJN 476', 'SNCF IC Nuit 3750', 'SNCF IC Nuit 3751', 'SNCF IC Nuit 3731', 'SNCF IC Nuit 3740', 'SNCF IC Nuit 3754', 'SNCF IC Nuit 3755', 'SNCF IC Nuit 3754 (Sun)', 'SNCF IC Nuit 3755 (Sun)', 'SNCF IC Nuit 3789', 'SNCF IC Nuit 3790', 'SNCF IC Nuit 3970', 'SNCF IC Nuit 3971', 'SNCF IC Nuit 5737', 'SNCF IC Nuit 5738', 'SNCF IC Nuit 5781', 'SNCF IC Nuit 5772', 'SNCF IC Nuit 5787', 'SNCF IC Nuit 5792', 'ST 300', 'ST 301', 'ST 304', 'ST 305', 'ST 3920', 'ST 3921', 'ST 3904', 'ST 3905', 'TCDD/BDŽ 12503/492', 'TCDD/BDŽ 493/12504', 'TCDD/BDŽ/CFR 12503/460', 'TCDD/BDŽ/CFR 461/12504', 'TCDD 22001', 'TCDD 12002', 'TCDD 22006', 'TCDD 32005', 'TCDD 22010', 'TCDD 42009', 'TCDD 22012', 'TCDD 52011', 'TCDD 22014', 'TCDD 52013', 'TCDD 22018', 'TCDD 52019', 'TCDD 32007', 'TCDD 72008', 'UEX 320/324', 'UEX 321/325', 'UEX 302/322', 'UEX 303/323', 'UEX 1856', 'UEX 1857', 'UEX 1858', 'UEX 1859', 'UEX 332/1372', 'UEX 333/1373', 'UEX 334/1374', 'UEX 335/1375', 'UZ 001 D', 'UZ 001 L', 'UZ 003', 'UZ 004', 'UZ 006 L', 'UZ 006 P', 'UZ 007 K', 'UZ 008 L', 'UZ 007 O/059 O', 'UZ 008 Š/060 Š', 'UZ 009', 'UZ 010', 'UZ 012 L', 'UZ 012 Š', 'UZ 013 K', 'UZ 013 L', 'UZ 015', 'UZ 016', 'UZ 017 O/045 D', 'UZ 017 L/045 L', 'UZ 019', 'UZ 020', 'UZ 021', 'UZ 022', 'UZ 023', 'UZ 024', 'UZ 029 K', 'UZ 029 L', 'UZ 032 D', 'UZ 032 P', 'UZ 036 Š', 'UZ 036 L', 'UZ 037', 'UZ 038 O/Š', 'UZ 038 K', 'UZ 038 P', 'UZ 041', 'UZ 042', 'UZ 043 L', 'UZ 043 Š', 'UZ 049', 'UZ 050', 'UZ 051', 'UZ 052 K', 'UZ 052 P/053', 'UZ 052 Š/054', 'UZ 055', 'UZ 056', 'UZ 059 K', 'UZ 060 L', 'UZ 063', 'UZ 064', 'UZ 065 K', 'UZ 065 Š', 'UZ 067', 'UZ 068', 'UZ 069', 'UZ 070', 'UZ 073', 'UZ 074', 'UZ 075', 'UZ 076', 'UZ 078 L', 'UZ 078 Š', 'UZ 079', 'UZ 080', 'UZ 081 K', 'UZ 081 L', 'UZ 086 L', 'UZ 086 P', 'UZ 088 L', 'UZ 088 P', 'UZ 091', 'UZ 092', 'UZ 093', 'UZ 094', 'UZ 095', 'UZ 096', 'UZ 097', 'UZ 098', 'UZ 099', 'UZ 100', 'UZ 105', 'UZ 106', 'UZ 109', 'UZ 110', 'UZ 112 L', 'UZ 112 P', 'UZ 113', 'UZ 114', 'UZ 121', 'UZ 122', 'UZ 128 L', 'UZ 128 P', 'UZ 136 L', 'UZ 136 Š', 'UZ 139', 'UZ 140', 'UZ 141', 'UZ 142', 'UZ 143', 'UZ 144', 'UZ 149', 'UZ 150', 'UZ 181 L', 'UZ 181 P', 'UZ 192 P', 'UZ 192 Š', 'UZ 194 L', 'UZ 194 P', 'UZ 357', 'UZ 358', 'UZ/CFM 351 K', 'UZ/CFM 351 L', 'UZ/ÖBB 40149', 'UZ/ÖBB 40749', 'VR IC 265', 'VR IC 274', 'VR IC 266 (H)', 'VR IC 273', 'VR IC 266 (T)', 'VR IC 933', 'VR P 269', 'VR P 276', 'VY 605', 'VY 606', 'ŽS/ŽPCG 433', 'ŽS/ŽPCG 1130 / 432', 'ZSSK R 680', 'ZSSK R 681', 'ZSSK EN 442', 'ZSSK EN 443', 'ZSSK EN 1152', 'ZSSK EN 1153']

,ATC IR 11501,ATC IR 11500,BDŽ 2626,BDŽ 2627,BDŽ 2636,BDŽ 2637,BDŽ 3636,BDŽ 3637,BDŽ 3686,BDŽ 3687,...,VY 605,VY 606,ŽS/ŽPCG 433,ŽS/ŽPCG 1130 / 432,ZSSK R 680,ZSSK R 681,ZSSK EN 442,ZSSK EN 443,ZSSK EN 1152,ZSSK EN 1153
0,24,24,133,133,142,142,132,132,139,139,...,69,69,130,130,123,123,6,6,115,115
1,ATC,ATC,BDŽ,BDŽ,BDŽ,BDŽ,BDŽ,BDŽ,BDŽ,BDŽ,...,VY,VY,ŽS/ŽPCG,ŽS/ŽPCG,ZSSK,ZSSK,ZSSK,ZSSK,ZSSK,ZSSK
2,ATC IR 11501,ATC IR 11500,BDŽ 2626,BDŽ 2627,BDŽ 2636,BDŽ 2637,BDŽ 3636,BDŽ 3637,BDŽ 3686,BDŽ 3687,...,VY 605,VY 606,ŽS/ŽPCG 433,ŽS/ŽPCG 1130 / 432,ZSSK R 680,ZSSK R 681,ZSSK EN 442,ZSSK EN 443,ZSSK EN 1152,ZSSK EN 1153

============================================================
view_ontd_cities.csv → table 'view_ontd_cities' | 727 colonnes
Colonnes : ['Aachen Hbf', 'Aberdeen', 'Adjud', 'Afyon A Çetinkaya', 'Alba Iulia', 'Albi Ville', 'Alfatar', 'Alvesta', 'Amersfoort Centraal', 'Amsterdam Centraal', 'Amstetten (NÖ)', 'Ankara', 'Antwerpen Centraal / Anvers Central', 'Arad', 'Åre', 'Arlanda', 'Arnhem Centraal', 'Arth-Goldau', 'Aschaffenburg Hbf', 'Asker', 'Asparuhovo', 'Attnang-Puchheim', 'Augsburg Hbf', 'Aurillac', 'Aviemore', 'Aytos', 'Azuga', 'Bacău', 'Bad Schandau', 'Baden-Baden', 'Baia Mare', 'Balıkesir', 'Bălți Oras', 'Bánovce nad Ondavou', 'Baqël', 'Bar', 'Barcellona Castroreale', 'Bari Centrale', 'Bârlad', 'Basel Bad Bf', 'Basel SBB', 'Batman', 'Bayonne', 'Beclean pe Somes', 'Békéscsaba', 'Bellinzona', 'Beloslav', 'Belovo', 'Beograd Centar', 'Bergen', 'Berlin Hbf', 'Berlin Ostbahnhof', 'Berlin Südkreuz', 'Bern', 'Béziers', 'Bezimenna', 'Bielsko-Biała Gł.', 'Bielsko-Biała Główna', 'Bijelo Polje', 'Birmingham International ', 'Bischofshofen', 'Bistrița Nord', 'Bitterfeld', 'Bjala', 'Bjelovar', 'Bludenz', 'Boden C', 'Bodø', 'Bogdantsi', 'Bohumín', 'Bologna Centrale', 'Bolzano / Bozen', 'Bonn Hbf', 'Bonn-Beuel', 'Borovo', 'Botevo', 'Bov', 'Brașov', 'Bratislava hl.st.', 'Bratislava Nové Mesto', 'Bratislava Petržalka', 'Bratislava-Vinohrady', 'Břeclav', 'Bregenz', 'Bremen Hbf', 'Bretenoux Biars', 'Briançon', 'Brig', 'Brindisi', 'Brno hl.n.', 'Bruck an der Mur', 'Bruxelles Midi / Brussel Zuid', 'Bruxelles Noord / Brussel Nord', 'Buchs (SG)', 'Bucuresti Baneasa', 'București Nord', 'Budapest Déli', 'Budapest Ferencváros', 'Budapest Kelenföld', 'Budapest Keleti', 'Budapest Nyugati', 'Budapest-Keleti', 'Budapest-Nyugati', 'Burgas', 'Bușteni', 'Buzău', 'Byala', 'Bydgoszcz Gł.', 'Calalzo-Pieve Di Cadore (Cortina)', 'Câmpina', 'Câmpulung Moldovenesc', 'Cannes', 'Caracal', 'Caransebeș', 'Carei', 'Carlisle', 'Catania Centrale', 'Cegléd', 'Cerbère', 'Cerovo', 'Česká Třebová', 'Chelm', 'Cherkasy', 'Chernevo', 'Chernihiv', 'Chernivtsi', 'Cherven Bryag', 'Chervonohrad', 'Cheshnegirovo', 'Chiasso', 'Chişinău', 'Chișineu-Criș', 'Chop', 'Ciechanow', 'Civitavecchia', 'Cluj-Napoca', 'Codlea', 'Como San Giovanni', 'Constanța', 'Craiova', 'Crest', 'Crewe', 'Crianlarich', 'Csárdaszállás', 'Curtici', 'Częstochowa', 'Dale', 'Dalgopol', 'Dax', 'Dębica', 'Debrecen', 'Děčín hl.n.', 'Deda', 'Dej', 'Den Haag', 'Deva', 'Deventer', 'Devnya', 'Dimitrovgrad', 'Diyarbakır', 'Dnipro Holovny', 'Dobrich', 'Dobrina', 'Dolni Dabnik', 'Donchevo', 'Dornbirn', 'Drammen', 'Dresden Hbf', 'Dresden Neustadt', 'Duisburg Hbf', 'Dulovo', 'Dundee', 'Düsseldorf Hbf', 'Duved', 'Dve Mogili', 'Edinburgh Waverley', 'Edirne', 'Eindhoven Centraal', 'Elazığ', 'Elin Pelin', 'Erfurt Hbf', 'Erzincan', 'Erzurum', 'Eskişehir', 'Făgăraș', 'Fastiv', 'Feldkirch', 'Fetești', 'Figeac', 'Firenze Campo di Marte', 'Firenze S. M. N.', 'Fleury-les-Aubrais (Orléans)', 'Focșani', 'Foggia', 'Fort William / An Gearasdan', 'Frankfurt (Main) Süd', 'Freiburg (Breisgau) Hbf', 'Fulda', 'Gällivare C', 'Gap', 'Gävle C', 'Gdańsk Gł.', 'Gdynia Gł.', 'Gdynia Główna', 'Gelen', 'General Kiselovo', 'Genova Piazza Principe', 'Gheorgheni', 'Gießen', 'Giurgiu Nord', 'Glasgow Central', 'Gliwice', 'Golubovci', 'Gorna Oryahovitsa', 'Göschenen', 'Göteborg C', 'Göttingen', 'Götzis', 'Graz Hbf', 'Grosseto', 'Gyoma', 'Győr', 'Halle (Saale) Hbf', 'Hamar', 'Hamburg Altona', 'Hamburg Dammtor', 'Hamburg Harburg', 'Hamburg Hbf', 'Hamm (Westf) Hbf', 'Hannover Hbf', 'Härnösand', 'Harsovo', 'Hässleholm C', 'Hegyeshalom', 'Hel', 'Helsingborg C', 'Helsinki / Helsingfors', 'Hohenems', 'Høje Taastrup', 'Hokksund', 'Humenné', 'Iași', 'Ihtiman', 'Ilia', 'Imst-Pitztal', 'Innsbruck Hbf', 'Inverness / Inbhir Nis', 'Iskar', 'Isperih', 'İstanbul Halkalı', 'İstanbul Pendik', 'İstanbul Sögütlücesme', 'Ivano-Frankivsk', 'Ivanovo', 'İzmir Basmane', 'İzmir Çiğli', 'İzmit', 'Izyum', 'Jabalkovo', 'Jambol', 'Jarosław', 'Jaworzno Szczakowa', 'Jelenia Góra', 'Jenbach', 'Kadievo', 'Kalush', 'Kamianets-Podilskyi', 'Kapıkule', 'Karlovac', 'Karlovo', 'Karlsruhe Hbf', 'Karnobat', 'Kars', 'Kaspichan', 'Kassel-Wilhelmshöhe', 'Kastrup Lufthavn', 'Katowice', 'Katunitsa', 'Kayseri', 'Kazichene', 'Kemi', 'Kemijärvi', 'Kétegyháza', 'Kharkiv', 'Kherson', 'Khmelnytskyi', 'Kielce', 'Kipra', 'Kiruna / Giron', 'Kitanchevo', 'Kitzbühel', 'Kivertsi', 'Kırıkkale', 'Klagenfurt Hbf', 'Klisura', 'Kłodzko Miasto', 'Knin', 'København Ørestad', 'Koblenz Hbf', 'Kokkola', 'Kolari', 'Kolašin', 'Kolding', 'Kolín', 'Köln Ehrenfeld', 'Köln Hbf', 'Köln Messe/Deutz', 'Köln Süd', 'Kołobrzeg', 'Komunari', 'Kongsberg', 'Konotop', 'Konya', 'Koper', 'Korosten', 'Košice', 'Kosjerić', 'Kostenets', 'Kostrzyn', 'Koszalin', 'Kovel', 'Kozyatyn', 'Kraków Gł.', 'Kraľovany', 'Kramatorsk', 'Kremenchuk', 'Kropyvnytskyi', 'Krumovo', 'Kryvyi Rih', 'Krzeszowice', 'Krzyz', 'Kufstein', 'Kumarica', 'Kurilo', 'Kurtalan', 'Kúty', 'Kyiv Pasazhyrskyi', 'Kyiv Sviatoshyn', 'Kysak', 'La Spezia Centrale', 'Lajkovac', 'Lakatnik', 'Lamezia Terme Centrale', 'Landeck-Zams', 'Langen am Arlberg', 'Laroquebrou / Laròcabrau', 'Latour-de-Carol / La Tor de Querol', 'Lazarevac', 'Łeba', 'Lecce', 'Leipzig Hbf', 'Leoben Hbf', 'Leopoldov', 'Leszno', 'Levanger', 'Levanto', 'Levski', 'Librazhd', 'Lichkov', 'Liège Guillemins / Luik Guillemins', 'Liège-Guillemins', 'Liezen', 'Lillehammer', 'Linköping C', 'Linz Hbf', 'Liptovský Mikuláš', 'Livorno Centrale', 'Ljubljana', 'Łódź Kaliska', 'Łódź Widzew', 'Lőkösháza', 'London Euston', 'London Paddington', 'Lörrach Hbf', 'Lourdes', 'Lublin', 'Lubny', 'Lugano', 'Lugoj', 'Lukovo', 'Luleå C', 'Lund C', 'Lüneburg', 'Lutherstadt Wittenberg Hbf', 'Lutsk', 'Lviv', 'Lviv Pidzamche', 'Mainz Hbf', 'Malatya', 'Malmö C', 'Mangalia', 'Manisa', 'Mannheim Hbf', 'Mărășești', 'Margecany', 'Maribor', 'Marseille Saint-Charles', 'Medgidia', 'Messina Centrale', 'Mezdra', 'Mezhden', 'Mezőberény', 'Mezőtúr', 'Michalovce', 'Międzylesie', 'Miercurea Ciuc', 'Milano Centrale', 'Milano Porta Garibaldi', 'Mizil', 'Mo i Rana', 'Mojkovac', 'Montauban Ville Bourbon', 'Montpellier Saint-Roch', 'Motherwell', 'Mukacheve', 'München Hbf', 'München Ost', 'Münster (Westf) Hbf', 'Murony', 'Mürzzuschlag', 'Mûş', 'Mykolaiv', 'Myrdal', 'Myrhorod', 'Mysłowice', 'Nagykanizsa', 'Napoli Centrale', 'Narbonne', 'Narvik', 'Nässjö C', 'Nice Ville', 'Nicolina', 'Nîmes', 'Norrköping C', 'Nova Zagora', 'Nové Mesto nad Váhom', 'Nové Zámky', 'Nürnberg Hbf', 'Nyíregyháza', 'Oborishte', 'Odense', 'Odesa Holovna', 'Offenburg', 'Oleksandriia', 'Olomouc hl.n.', 'Opatija Matulji', 'Opoczno Południe', 'Opole Gł.', 'Opole Główne', 'Oradea', 'Örebro C', 'Örnsköldsvik C', 'Orte', 'Orvieto', 'Osijek', 'Oslo S', 'Östersund C', 'Ostrava hl.n.', 'Ötztal', 'Oulu', 'Padborg', 'Palermo Centrale', 'Pamiers', 'Pardubice hl.n.', 'Paris Austerlitz', 'Paris Est', 'Paris Gare du Nord', 'Parvomai', 'Passau Hbf', 'Pau', 'Pavlikeni', 'Pazardzhik', 'Penzance', 'Perpignan', 'Perth / Peairt', 'Petko Karavelovo', 'Petroșani', 'Piešťany', 'Pirdop', 'Pisa Centrale', 'Pleven', 'Ploiești Sud', 'Ploiești Vest', 'Plovdiv', 'Plymouth', 'Podgorica', 'Podilsk', 'Poduiane', 'Poduiane Patnicheska', 'Polski Trambesh', 'Poltava', 'Popovitsa', 'Popovo', 'Poprad Tatry', 'Poveljanovo', 'Požega', 'Poznań Gł.', 'Praha hl.n.', 'Praha-Holešovice', 'Predeal', 'Preston', 'Priboj', 'Prijepolje', 'Prijepolje teretna', 'Proslav', 'Provadiya', 'Przemyśl Gł.', 'Przeworsk', 'Púchov', 'Radom', 'Rakhiv', 'Rakovica', 'Râmnicu Sărat', 'Rankweil', 'Razgrad', 'Reading', 'Rebrovo', 'Regensburg Hbf', 'Reggio Calabria Centrale', 'Riesa', 'Riihimäki', 'Rijeka', 'Rivne', 'Rodez', 'Roma Ostiense', 'Roma Termini', 'Roma Tiburtina', 'Roman', 'Romcha', 'Rosenheim', 'Roșiori Nord', 'Rotterdam Centraal', 'Rovaniemi', "Rozdil'na", 'Ruijno', 'Ruse', 'Ruse Razpredelitel', 'Ruse Tovarna', 'Ružomberok', 'Rybnik', 'Rzeszow Gł.', 'Sadov', 'Salerno', 'Salzburg Hbf', 'Sambir', 'Samuil', 'Sandnes', 'Sandvika', 'Sărățel', 'Sargans', 'Satu Mare', 'Schipol Airport', 'Schladming', 'Schwarzach-St.Veit', 'Sebeș Alba', 'Seinäjoki', 'Selzthal', 'Senovo', 'Septemvri', 'Shumen', 'Sibiu', 'Siegburg (Bonn)', 'Siegburg/Bonn', 'Siegen', 'Siegen Hbf', 'Sighetu Marmației', 'Sighișoara', 'Silistra', 'Simeria', 'Sinaia', 'Sindel', 'Siófok', 'Siracusa', 'Sivas', 'Slavonski Brod', 'Sliven', 'Sloviansk', 'Słupsk', 'Sofia', 'Sofia Sever', 'Solotvyno', 'Sosnowiec Główny', 'Spišská Nová Ves', 'Split', 'St-Denis-lès-Martel', 'St. Anton am Arlberg', 'St. Michael (Obersteiermark)', 'St. Pölten Hbf', 'St. Valentin', 'St.Pölten Hbf', 'Stainach-Irdning', 'Stambolijski', 'Stara Zagora', 'Stavanger', 'Steinkjer', 'Stirling', 'Stockholm C', 'Storlien', 'Straldzha', 'Strasbourg', 'Strazhitsa', 'Strážske', 'Štrba', 'Stresa', 'Stryj', 'Štúrovo', 'Stuttgart Hbf', 'Subcetate', 'Suceava', 'Suceava Nord', 'Sumy', 'Sundsvall C', 'Sutomore', 'Suvorovo', 'Svilengrad', 'Svoge', 'Świnoujście', 'Szczecin Gł.', 'Székesfehérvár', 'Szklarska Poręba Górna', 'Szolnok', 'Tampere', 'Taormina Giardini', 'Taranto', 'Tarbes', 'Targovishte', 'Târgu Frumos', 'Târgu Jiu', 'Tarnow', 'Tatvan', 'Tczew', 'Telish', 'Termini Imerese', 'Ternopil', 'Timişoara Nord', 'Todor Kableshkov', 'Todorovo', 'Toijala', 'Tompsan', 'Torino Lingotto', 'Torino Porta Susa', 'Tornio-Itäinen', 'Toruń Gł.', 'Toulon', 'Toulouse Matabiau', 'Trebišov', 'Trenčianska Teplá', 'Trenčín', 'Treviso Centrale', 'Trieste Centrale', 'Trnava', 'Trondheim', 'Tropea', 'Truskavets', 'Trzebinia', 'Turku / Åbo', 'Turku satama / Åbo hamn', 'Udine', 'Ulm Hbf', 'Uman', 'Umeå C', 'Ungheni', 'Ungheni Prut', 'Uppsala C', 'Ústí nad Labem hl.n.', 'Utrecht Centraal', 'Uzhhorod', 'Užice', 'Vac', 'Vakarel', 'Valchi Dol', 'Vălcineț', 'Valjevo', 'Varna', 'Vaslui', 'Västerås C', 'Vatra Dornei', 'Vatra Dornei Băi', 'Veliko Tarnovo', 'Venezia Santa Lucia', 'Verden (Aller)', 'Verona Porta Nuova', 'Vesprem', 'Vetovo', 'Videle', 'Villach Hbf', 'Vinnytsia', 'Vișeu de Jos', 'Vladimir Pavlov', 'Vlado Trickov', 'Vöcklabruck', 'Vorokhta', "Voznesens'k", 'Vukovar', 'Warszawa Centralna', 'Warszawa Wschodnia', 'Warszawa Zachodnia', 'Watford Junction', 'Wels Hbf', 'Wien Hbf', 'Wien Hbf (Autoreisezuganlage)', 'Wien Meidling', 'Wien Westbf', 'Wiener Neustadt Hbf', 'Włoszczowa Północ', 'Wörgl Hbf', 'Wrocław Gł.', 'Würzburg Hbf', 'Yasinia', 'Yastrebovo', 'Ylivieska', 'Zabrze', 'Zagreb Gl. K.', 'Záhony', 'Zakopane', 'Zalaegerszeg', 'Zaporizhzhia 1', 'Zawiercie', 'Zemun', 'Zhmerynka', 'Zielona Góra Gł.', 'Zimnitsa', 'Zlatica', 'Żory', 'Zürich HB', 'Zverino', 'Unnamed: 726']

,Aachen Hbf,Aberdeen,Adjud,Afyon A Çetinkaya,Alba Iulia,Albi Ville,Alfatar,Alvesta,Amersfoort Centraal,Amsterdam Centraal,...,Zawiercie,Zemun,Zhmerynka,Zielona Góra Gł.,Zimnitsa,Zlatica,Żory,Zürich HB,Zverino,Unnamed: 726
0,Aachen Hbf,Aberdeen,Adjud,Afyon A Çetinkaya,Alba Iulia,Albi Ville,Alfatar,Alvesta,Amersfoort Centraal,Amsterdam Centraal,...,Zawiercie,Zemun,Zhmerynka,Zielona Góra Gł.,Zimnitsa,Zlatica,Żory,Zürich HB,Zverino,NaN
1,Aachen,Aberdeen,NaN,Afyonkarahisar,Alba Iulia,Albi,NaN,Alvesta,Amersfoort,Amsterdam,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DE,UK,RO,TR,RO,FR,BG,SE,NL,NL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

============================================================
view_ontd_details.csv → table 'view_ontd_details' | 12312 colonnes

Empty DataFrame
Columns: [{"1":{"route_id":1, agency_id:"ÖBB", trip_short_name_0:"NJ 40425", service_id_0:"2025: Mon,  Wed,  Fri", trip_short_name_1:"NJ 40468", service_id_1:"2025: Tue,  Thu,  Sun", route_long_name:"", distance:"", average_speed:"", emissions:"", emissions_km:"", classes:"seat,  couchette,  sleeper", countries:"BE,  DE,  AT", source:"https://www.nightjet.com/", picture:"https://back-on-track.eu/wp-content/uploads/2023/11/NJnG-Thumb_SB8.jpg", irregularities_0:"", irregularities_1:"", connection:"London", catering:"", plugs:"", wheelchair_accessible:"", bikes_allowed:"", car_transport:2, agency_id_1:"ÖBB", agency_name_1:"ÖBB-Personenverkehr AG", agency_url_1:"https://personenverkehr.oebb.at", agency_logo_url_1:"https://back-on-track.eu/wp-content/uploads/2025/03/logo_obb.jpg", agency_id_2:"", agency_name_2:"", agency_url_2:"", agency_logo_url_2:"", agency_id_3:"", agency_name_3:"", agency_url_3:"", agency_logo_url_3:"", monday_0:1, tuesday_0:0, wednesday_0:1, thursday_0:0, friday_0:1, saturday_0:0, sunday_0:0, start_date_0:"2024-12-15T00:00:00.000Z", end_date_0:"2025-12-13T00:00:00.000Z", monday_1:0, tuesday_1:1, wednesday_1:0, thursday_1:1, friday_1:0, saturday_1:0, sunday_1:1, start_date_1:"2024-12-15T00:00:00.000Z", end_date_1:"2025-12-13T00:00:00.000Z", trip_id_0:"ÖBB NJ 40425", trip_id_1:"ÖBB NJ 40468", duration_0:"1899-12-30T15:07:00.000Z", duration_1:"1899-12-30T15:48:00.000Z", origin_city:"Bruxelles / Brussel", destination_city:"Wien"}, 2:{"route_id":2, agency_id:"ÖBB".1, trip_short_name_0:"NJ 408", service_id_0:"2025: Daily", trip_short_name_1:"NJ 409", service_id_1:"2025: Daily", route_long_name:"".1, distance:"".1, average_speed:"".1, emissions:"".1, emissions_km:"".1, classes:"seat.1,  couchette.1,  sleeper".1, countries:"DE,  CH", source:"https://www.nightjet.com/".1, picture:"https://back-on-track.eu/wp-content/uploads/2023/11/NJnG-Thumb_SB8.jpg".1, irregularities_0:"".1, irregularities_1:"".1, connection:"", catering:"".1, plugs:"".1, wheelchair_accessible:"".1, bikes_allowed:"".1, car_transport:2.1, agency_id_1:"ÖBB".1, agency_name_1:"ÖBB-Personenverkehr AG".1, agency_url_1:"https://personenverkehr.oebb.at".1, agency_logo_url_1:"https://back-on-track.eu/wp-content/uploads/2025/03/logo_obb.jpg".1, agency_id_2:"".1, agency_name_2:"".1, agency_url_2:"".1, ...]
Index: []

[0 rows x 12312 columns]

============================================================
view_ontd_list.csv → table 'view_ontd_list' | 200 colonnes
Colonnes : ['1', '2', '3', '4', '5', '6', '7', '9', '10', '11', '12', '13', '14', '15', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '30', '31', '37', '38', '39', '40', '41', '42', '44', '45', '46', '47', '48', '49', '50', '51', '53', '54', '57', '58', '59', '60', '61', '62', '63', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '76', '77', '78', '79', '80', '81', '83', '84', '85', '86', '88', '90', '91', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '114', '115', '116', '117', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '147', '149', '150', '151', '152', '153', '154', '155', '156', '157', '158', '161', '162', '164', '166', '167', '168', '170', '172', '173', '175', '177', '178', '180', '181', '182', '183', '185', '186', '189', '190', '191', '195', '196', '197', '198', '199', '200', '201', '203', '207', '208', '209', '210', '211', '212', '213', '218', '219', '220', '221', '222', '224', '225', '227', '229', '231', '232', '233', '235', '237', '238', '243', '245', '246', '247', '248', '249', '250', '251', '252', '253', '254', '255', '256', '257', '260', '261', '262', '264', '#REF!']

,1,2,3,4,5,6,7,9,10,11,...,253,254,255,256,257,260,261,262,264,#REF!
0,1,2,3,4,5,6,7,9,10,11,...,253,254,255,256,257,260,261,262,264,#REF!
1,ÖBB NJ 40425 + NJ 40468,ÖBB NJ 408 + NJ 409,HŽPP 1820 + 1821,ČD EN 40476 + EN 40457,ÖBB NJ 470 + NJ 471,ZSSK EN 442 + EN 443,RJ 1020 + 1021,PKP/ČD EN 443 / IC 406 + IC 407 / EN 442,PKP TLK 35190/50191 + TLK 55190/53190,CFR 1837 + 1838,...,UEX 302/322 + 303/323,UEX 1856 + 1857,UEX 1858 + 1859,UEX 332/1372 + 333/1373,UEX 334/1374 + 335/1375,ÖBB NJ 40424 + NJ 40469,RJ 1038 + 1039,SNCF IC Nuit 3789 + IC Nuit 3790,SNCF IC Nuit 3750 + IC Nuit 3751,#REF!
2,NaN,NaN,NaN,Metropol,NaN,Slovakia,NaN,Chopin,Rozewie,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#REF!

============================================================
view_ontd_map.csv → table 'view_ontd_map' | 199 colonnes
Colonnes : ['1', '2', '3', '4', '5', '6', '7', '9', '10', '11', '12', '13', '14', '15', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '30', '31', '37', '38', '39', '40', '41', '42', '44', '45', '46', '47', '48', '49', '50', '51', '53', '54', '57', '58', '59', '60', '61', '62', '63', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '76', '77', '78', '79', '80', '81', '83', '84', '85', '86', '88', '90', '91', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '114', '115', '116', '117', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '147', '149', '150', '151', '152', '153', '154', '155', '156', '157', '158', '161', '162', '164', '166', '167', '168', '170', '172', '173', '175', '177', '178', '180', '181', '182', '183', '185', '186', '189', '190', '191', '195', '196', '197', '198', '199', '200', '201', '203', '207', '208', '209', '210', '211', '212', '213', '218', '219', '220', '221', '222', '224', '225', '227', '229', '231', '232', '233', '235', '237', '238', '243', '245', '246', '247', '248', '249', '250', '251', '252', '253', '254', '255', '256', '257', '260', '261', '262', '264']

,1,2,3,4,5,6,7,9,10,11,...,252,253,254,255,256,257,260,261,262,264
0,1,2,3,4,5,6,7,9,10,11,...,252,253,254,255,256,257,260,261,262,264
1,ÖBB,ÖBB,HŽPP,ČD,ÖBB,ZSSK,RJ,PKP/ČD,PKP,CFR,...,UEX,UEX,UEX,UEX,UEX,UEX,ÖBB,RJ,SNCF,SNCF
2,NJ 40425,NJ 408,1820,EN 40476,NJ 470,EN 442,1020,EN 443 / IC 406,TLK 35190/50191,1837,...,320/324,302/322,1856,1858,332/1372,334/1374,NJ 40424,1038,IC Nuit 3789,IC Nuit 3750

In [26]:
conn = sqlite3.connect(DB_PATH)
resultats = []

for fichier, nom_table in FICHIERS_CSV.items():
    chemin = os.path.join(DOSSIER, fichier)
    
    if not os.path.exists(chemin):
        print(f"  ⚠ ABSENT : {fichier}")
        resultats.append({"fichier": fichier, "table": nom_table, "statut": "ABSENT", "lignes": 0})
        continue
    
    try:
        # Lecture du CSV
        df = pd.read_csv(chemin, encoding="utf-8", low_memory=False)
        df.columns = df.columns.str.strip()
        
        # Chargement dans SQLite (remplace la table si elle existe)
        df.to_sql(nom_table, conn, if_exists="replace", index=False)
        
        # Vérification
        count = pd.read_sql(f'SELECT COUNT(*) as n FROM "{nom_table}"', conn).iloc[0, 0]
        
        print(f"  ✓ {fichier:30s} → {nom_table:25s} | {count:>7,} lignes | {len(df.columns)} col")
        resultats.append({
            "fichier": fichier, "table": nom_table,
            "statut": "OK", "lignes": count, "colonnes": len(df.columns)
        })
    except Exception as e:
        print(f"  ✗ ERREUR sur {fichier}: {e}")
        resultats.append({"fichier": fichier, "table": nom_table, "statut": f"ERREUR", "lignes": 0})

conn.commit()
print(f"\n{'='*60}")
print(f"Import terminé : {sum(1 for r in resultats if r['statut']=='OK')}/{len(FICHIERS_CSV)} fichiers OK")
print(f"Total : {sum(r['lignes'] for r in resultats):,} lignes importées")

  ✓ agencies.csv                   → agencies                  |      15 lignes | 30 col
  ✓ calendrier.csv                 → calendrier                |      10 lignes | 110 col
  ✓ calendrier_dates.csv           → calendrier_dates          |       7 lignes | 59 col
  ✓ classes.csv                    → classes                   |       2 lignes | 12 col
  ✓ routes.csv                     → routes                    |      21 lignes | 207 col
  ✗ ERREUR sur stops.csv: too many columns on stops
  ✓ translations.csv               → translations              |       6 lignes | 2 col
  ✗ ERREUR sur trip_stop.csv: too many columns on trip_stop
  ✓ trips.csv                      → trips                     |      31 lignes | 410 col
  ✓ view_ontd_cities.csv           → view_ontd_cities          |       5 lignes | 727 col
  ✗ ERREUR sur view_ontd_details.csv: too many columns on view_ontd_details
  ✓ view_ontd_list.csv             → view_ontd_list            |       8 lignes | 200 col
  ✓ view_ontd_map.csv              → view_ontd_map             |      20 lignes | 199 col

============================================================
Import terminé : 10/13 fichiers OK
Total : 125 lignes importées

In [27]:
# Index pour optimiser les requêtes fréquentes
INDEX_SQL = [
    # Tables GTFS principales
    'CREATE INDEX IF NOT EXISTS idx_routes_agency ON routes(agency_id);',
    'CREATE INDEX IF NOT EXISTS idx_trips_route ON trips(route_id);',
    'CREATE INDEX IF NOT EXISTS idx_trip_stop_trip ON trip_stop(trip_id);',
    'CREATE INDEX IF NOT EXISTS idx_trip_stop_stop ON trip_stop(stop_id);',
    'CREATE INDEX IF NOT EXISTS idx_stops_name ON stops(stop_name);',
    'CREATE INDEX IF NOT EXISTS idx_calendrier_service ON calendrier(service_id);',
    'CREATE INDEX IF NOT EXISTS idx_calendrier_dates_service ON calendrier_dates(service_id);',
    'CREATE INDEX IF NOT EXISTS idx_translations_table ON translations(table_name);',
]

cursor = conn.cursor()
for sql in INDEX_SQL:
    try:
        cursor.execute(sql)
        nom_index = sql.split('idx_')[1].split(' ')[0]
        print(f"  ✓ Index créé : idx_{nom_index}")
    except Exception as e:
        print(f"  ⚠ {sql[:50]}... → {e}")

conn.commit()
print("\nIndex créés avec succès.")

  ⚠ CREATE INDEX IF NOT EXISTS idx_routes_agency ON ro... → no such column: agency_id
  ⚠ CREATE INDEX IF NOT EXISTS idx_trips_route ON trip... → no such column: route_id
  ⚠ CREATE INDEX IF NOT EXISTS idx_trip_stop_trip ON t... → no such table: main.trip_stop
  ⚠ CREATE INDEX IF NOT EXISTS idx_trip_stop_stop ON t... → no such table: main.trip_stop
  ⚠ CREATE INDEX IF NOT EXISTS idx_stops_name ON stops... → no such table: main.stops
  ⚠ CREATE INDEX IF NOT EXISTS idx_calendrier_service ... → no such column: service_id
  ⚠ CREATE INDEX IF NOT EXISTS idx_calendrier_dates_se... → no such column: service_id
  ⚠ CREATE INDEX IF NOT EXISTS idx_translations_table ... → no such column: table_name

Index créés avec succès.

In [28]:
# Liste de toutes les tables et leur contenu
tables_info = pd.read_sql("""
    SELECT name as table_name 
    FROM sqlite_master 
    WHERE type='table' 
    ORDER BY name
""", conn)

print(f"{'Table':30s} | {'Lignes':>10s} | {'Colonnes':>10s}")
print("-" * 60)

for table in tables_info['table_name']:
    count = pd.read_sql(f'SELECT COUNT(*) as n FROM "{table}"', conn).iloc[0, 0]
    cols = pd.read_sql(f'PRAGMA table_info("{table}")', conn)
    print(f"{table:30s} | {count:>10,} | {len(cols):>10}")

print(f"\nTotal : {len(tables_info)} tables dans la base de données")

Table                          |     Lignes |   Colonnes
------------------------------------------------------------
agencies                       |         15 |         30
calendrier                     |         10 |        110
calendrier_dates               |          7 |         59
classes                        |          2 |         12
co2_clean                      |          5 |          7
od_aggregated                  |         72 |          7
od_flows_enriched              |      2,680 |         17
routes                         |         21 |        207
sqlite_sequence                |          0 |          2
translations                   |          6 |          2
trips                          |         31 |        410
view_ontd_cities               |          5 |        727
view_ontd_list                 |          8 |        200
view_ontd_map                  |         20 |        199

Total : 14 tables dans la base de données

In [29]:
# Schéma détaillé de chaque table (colonnes + types)
for table in tables_info['table_name']:
    schema = pd.read_sql(f'PRAGMA table_info("{table}")', conn)
    print(f"\n--- {table} ---")
    for _, row in schema.iterrows():
        print(f"  {row['name']:30s} {row['type']}")

--- agencies ---
  ATC                            TEXT
  BDŽ                            TEXT
  ČD                             TEXT
  CFM                            TEXT
  CFR                            TEXT
  CS                             TEXT
  ES                             TEXT
  FS                             TEXT
  GA                             TEXT
  GWR                            TEXT
  HŽPP                           TEXT
  MÁV                            TEXT
  MT                             TEXT
  ÖBB                            TEXT
  OTE                            TEXT
  PKP                            TEXT
  RDC                            TEXT
  RJ                             TEXT
  SJ                             TEXT
  SJN                            TEXT
  SNCF                           TEXT
  ST                             TEXT
  TCDD                           TEXT
  UEX                            TEXT
  UZ                             TEXT
  VR                             TEXT
  VY                             TEXT
  ŽPCG                           TEXT
  ŽS                             TEXT
  ZSSK                           TEXT

--- calendrier ---
  -- 2024 --                     TEXT
  Daily                          TEXT
  0-2 days/week (May-Oct)        TEXT
  2024/03/31-2024/11/03: Mon, Tue, Wed, Thu, Fri, Sun TEXT
  2024: Mon, Tue, Wed, Thu, Fri  TEXT
  2024: Mon, Tue, Wed, Thu, Sun  TEXT
  2024: Daily except Sat         TEXT
  2024: 1-5,7                    TEXT
  Mon, Wed, Fri                  TEXT
  2024/07/08-2024/09/22: Mon, Wed, Sat TEXT
  2024: Tue, Thu                 TEXT
  2024: Tue, Sun                 TEXT
  Tue, Wed, Fri                  TEXT
  Tue, Thu, Sat                  TEXT
  Tue, Thu, Sun                  TEXT
  2024/07/07-2024/09/21: Tue, Fri, Sun TEXT
  Thu, Sat                       TEXT
  2023/12/22-2024/03/28: Fri     TEXT
  Fri, Sat                       TEXT
  2023/12/30- 2024/03/30: Sat    TEXT
  2024: Tue, Thu, Sat, Sun       TEXT
  2024: 3-4 times per week       TEXT
  2024: every 2nd day            TEXT
  Sat, Sun                       TEXT
  Fri, Sun (daily in holidays in région C) TEXT
  Sun (Oct-Jun)                  TEXT
  Fri (May-Oct)                  TEXT
  Fri (Sep-Jun)                  TEXT
  Daily (Jul-Aug)                TEXT
  Daily (May-Sep)                TEXT
  2023/12/16-2024/04/27: Wed, Sat TEXT
  Wed, Fri, Sat                  TEXT
  Thu, Sat, Sun                  TEXT
  2023/12/17-2024/04/27: Thu, Sun TEXT
  Wed, Sat                       TEXT
  Mon, Thu, Sat                  TEXT
  Wed, Fri, Sun                  TEXT
  2024: Wed, Sat, Sun (every 2nd week) TEXT
  2024: Mon, Wed, Thu (every 2nd week) TEXT
  Fri                            TEXT
  Fri, Sun                       TEXT
  2023/12/23-2024/03/29: Sat     TEXT
  Sun                            TEXT
  2024/06/05-2024/10/05: Daily   TEXT
  2024/06/14-2024/09/07: Daily   TEXT
  2024/06/15-2024/09/08: Daily   TEXT
  2024/06/22-2024/09/01: Daily   TEXT
  2024/06/29-2024/09/07: Daily   TEXT
  2024/05/03-2024/10/02: Wed, Fri, Sun TEXT
  2024/05/04-2024/10/03: Mon, Thu, Sat TEXT
  -- 2025 --                     TEXT
  2025: Daily                    TEXT
  2025: Mon, Wed, Thu            TEXT
  2025: Mon, Wed, Fri            TEXT
  2025: Mon, Thu, Sat            TEXT
  2025: Tue, Thu, Sat            TEXT
  2025: Tue, Thu, Sun            TEXT
  2025: Wed, Fri, Sat            TEXT
  2025: Wed, Fri, Sun            TEXT
  2025: Wed, Sat                 TEXT
  2025: Wed, Sat, Sun            TEXT
  2025: Thu, Sat, Sun            TEXT
  2025: Thu, Sun                 TEXT
  2025: Fri                      TEXT
  2025: Fri, Sat                 TEXT
  2025: Fri, Sun                 TEXT
  2025: Sat, Sun                 TEXT
  2025: Sun                      TEXT
  2025/05-09: Daily              TEXT
  2024/10-2025/06: Fri           TEXT
  2024/10-2025/06: Sun           TEXT
  2025/06/25-09/27: Wed, Sat     TEXT
  2025/06/26-09/28: Thu, Sun     TEXT
  2025/05/05-2025/10/04: Mon, Thu, Sat TEXT
  2025/05/07-2025/10/05: Wed, Fri, Sun TEXT
  -- 2026 --                     TEXT
  2026: Daily                    TEXT
  2026: Daily, except Saturday   TEXT
  2026: Mon, Wed, Thu            TEXT
  2026: Mon, Wed, Fri            TEXT
  2026: Mon, Thu, Sat            TEXT
  2026: Tue, Thu, Sat            TEXT
  2026: Tue, Thu, Sun            TEXT
  2026: Wed, Fri, Sat            TEXT
  2026: Wed, Fri, Sun            TEXT
  2026: Wed, Sat                 TEXT
  2026: Wed, Sat, Sun            TEXT
  2026: Thu, Sat, Sun            TEXT
  2026: Thu, Sun                 TEXT
  2026: Fri                      TEXT
  2026: Fri, Sat                 TEXT
  2026: Fri, Sun                 TEXT
  2026: Sat, Sun                 TEXT
  2026: Sun                      TEXT
  2026: Every 2nd day            TEXT
  2026/05-09: Daily              TEXT
  2026/06-2026/10: Fri           TEXT
  2026/06-2026/10: Sun           TEXT
  2026/06/25-09/27: Wed, Sat     TEXT
  2026/06/26-09/28: Thu, Sun     TEXT
  2026/06/11-09/06: Daily        TEXT
  Unknown                        TEXT
  2026/06/27-2026/08/31: Daily   TEXT
  2026/06/26-2026/08/30: Daily   TEXT
  2026: Tue, Thu                 TEXT
  2026: Mon, Wed, Thu, Fri, Sat  TEXT
  2026: Mon, Wed, Fri, Sat, Son  TEXT
  2026: Thu, Sat                 TEXT
  2026: Sat                      TEXT
  2026: Tue                      TEXT

--- calendrier_dates ---
  1                              TEXT
  2                              TEXT
  3                              TEXT
  4                              TEXT
  5                              TEXT
  6                              TEXT
  7                              TEXT
  8                              TEXT
  9                              TEXT
  10                             TEXT
  11                             TEXT
  12                             TEXT
  13                             TEXT
  14                             TEXT
  15                             TEXT
  16                             TEXT
  17                             TEXT
  18                             TEXT
  19                             TEXT
  20                             TEXT
  21                             TEXT
  22                             TEXT
  23                             TEXT
  24                             TEXT
  25                             TEXT
  26                             TEXT
  27                             TEXT
  28                             TEXT
  29                             TEXT
  30                             TEXT
  31                             TEXT
  32                             TEXT
  33                             TEXT
  34                             TEXT
  35                             TEXT
  36                             TEXT
  37                             TEXT
  38                             TEXT
  39                             TEXT
  40                             TEXT
  41                             TEXT
  42                             TEXT
  43                             TEXT
  44                             TEXT
  45                             TEXT
  46                             TEXT
  47                             TEXT
  48                             TEXT
  49                             TEXT
  50                             TEXT
  51                             TEXT
  52                             TEXT
  53                             TEXT
  54                             TEXT
  55                             TEXT
  56                             TEXT
  57                             TEXT
  58                             TEXT
  59                             TEXT

--- classes ---
  seat (reclinig)                TEXT
  seat (compartment)             TEXT
  seat                           TEXT
  couchette (4-berth)            TEXT
  couchette (6-berth)            TEXT
  capsule (seat/bed)             TEXT
  capsule (bed)                  TEXT
  Sleeper (2-berth) with shower & WC TEXT
  Sleeper (double) with shower & WC TEXT
  Sleeper (3-berth) with shower & WC TEXT
  Sleeper (2-berth)              TEXT
  Sleeper (3-berth)              TEXT

--- co2_clean ---
  country                        TEXT
  emissions_train_g_km           REAL
  emissions_car_g_km             INTEGER
  emissions_plane_g_km           INTEGER
  co2_saved_vs_car_g_km          REAL
  co2_saved_vs_plane_g_km        REAL
  reduction_vs_car_pct           REAL

--- od_aggregated ---
  year                           INTEGER
  origin_country_iso             TEXT
  flow_type                      TEXT
  nb_routes                      INTEGER
  total_passengers_M             REAL
  avg_passengers_M               REAL
  max_route_M                    REAL

--- od_flows_enriched ---
  year                           INTEGER
  origin_station                 TEXT
  destination_station            TEXT
  origin_city                    TEXT
  destination_city               TEXT
  origin_region                  TEXT
  destination_region             TEXT
  passengers_millions            REAL
  service_type                   TEXT
  flow_type                      TEXT
  source                         TEXT
  origin_country_iso             TEXT
  destination_country_iso        TEXT
  emissions_train_g_km           REAL
  emissions_car_g_km             REAL
  co2_saved_vs_car_g_km          REAL
  reduction_vs_car_pct           REAL

--- routes ---
  1970-01-01 00:00:01            TEXT
  1970-01-01 00:00:02            TEXT
  1970-01-01 00:00:03            TEXT
  1970-01-01 00:00:04            TEXT
  1970-01-01 00:00:05            TEXT
  1970-01-01 00:00:06            TEXT
  1970-01-01 00:00:07            TEXT
  1970-01-01 00:00:08            TEXT
  1970-01-01 00:00:09            TEXT
  1970-01-01 00:00:10            TEXT
  1970-01-01 00:00:11            TEXT
  1970-01-01 00:00:12            TEXT
  1970-01-01 00:00:13            TEXT
  1970-01-01 00:00:14            TEXT
  1970-01-01 00:00:15            TEXT
  1970-01-01 00:00:17            TEXT
  1970-01-01 00:00:18            TEXT
  1970-01-01 00:00:19            TEXT
  1970-01-01 00:00:20            TEXT
  1970-01-01 00:00:21            TEXT
  1970-01-01 00:00:22            TEXT
  1970-01-01 00:00:23            TEXT
  1970-01-01 00:00:24            TEXT
  1970-01-01 00:00:25            TEXT
  1970-01-01 00:00:26            TEXT
  1970-01-01 00:00:27            TEXT
  1970-01-01 00:00:28            TEXT
  1970-01-01 00:00:30            TEXT
  1970-01-01 00:00:31            TEXT
  1970-01-01 00:00:37            TEXT
  1970-01-01 00:00:38            TEXT
  1970-01-01 00:00:39            TEXT
  1970-01-01 00:00:40            TEXT
  1970-01-01 00:00:41            TEXT
  1970-01-01 00:00:42            TEXT
  1970-01-01 00:00:44            TEXT
  1970-01-01 00:00:45            TEXT
  1970-01-01 00:00:46            TEXT
  1970-01-01 00:00:47            TEXT
  1970-01-01 00:00:48            TEXT
  1970-01-01 00:00:49            TEXT
  1970-01-01 00:00:50            TEXT
  1970-01-01 00:00:53            TEXT
  1970-01-01 00:00:54            TEXT
  1970-01-01 00:00:57            TEXT
  1970-01-01 00:00:58            TEXT
  1970-01-01 00:00:59            TEXT
  1970-01-01 00:01:00            TEXT
  1970-01-01 00:01:01            TEXT
  1970-01-01 00:01:02            TEXT
  1970-01-01 00:01:03            TEXT
  1970-01-01 00:01:05            TEXT
  1970-01-01 00:01:06            TEXT
  1970-01-01 00:01:07            TEXT
  1970-01-01 00:01:08            TEXT
  1970-01-01 00:01:09            TEXT
  1970-01-01 00:01:10            TEXT
  1970-01-01 00:01:11            TEXT
  1970-01-01 00:01:12            TEXT
  1970-01-01 00:01:13            TEXT
  1970-01-01 00:01:14            TEXT
  1970-01-01 00:01:16            TEXT
  1970-01-01 00:01:17            TEXT
  1970-01-01 00:01:18            TEXT
  1970-01-01 00:01:19            TEXT
  1970-01-01 00:01:20            TEXT
  1970-01-01 00:01:21            TEXT
  1970-01-01 00:01:23            TEXT
  1970-01-01 00:01:24            TEXT
  1970-01-01 00:01:25            TEXT
  1970-01-01 00:01:26            TEXT
  1970-01-01 00:01:28            TEXT
  1970-01-01 00:01:30            TEXT
  1970-01-01 00:01:31            TEXT
  1970-01-01 00:01:36            TEXT
  1970-01-01 00:01:37            TEXT
  1970-01-01 00:01:38            TEXT
  1970-01-01 00:01:39            TEXT
  1970-01-01 00:01:40            TEXT
  1970-01-01 00:01:41            TEXT
  1970-01-01 00:01:42            TEXT
  1970-01-01 00:01:43            TEXT
  1970-01-01 00:01:44            TEXT
  1970-01-01 00:01:45            TEXT
  1970-01-01 00:01:46            TEXT
  1970-01-01 00:01:47            TEXT
  1970-01-01 00:01:48            TEXT
  1970-01-01 00:01:49            TEXT
  1970-01-01 00:01:50            TEXT
  1970-01-01 00:01:51            TEXT
  1970-01-01 00:01:52            TEXT
  1970-01-01 00:01:54            TEXT
  1970-01-01 00:01:55            TEXT
  1970-01-01 00:01:56            TEXT
  1970-01-01 00:01:57            TEXT
  1970-01-01 00:01:58            TEXT
  1970-01-01 00:01:59            TEXT
  1970-01-01 00:02:00            TEXT
  1970-01-01 00:02:01            TEXT
  1970-01-01 00:02:02            TEXT
  1970-01-01 00:02:03            TEXT
  1970-01-01 00:02:04            TEXT
  1970-01-01 00:02:05            TEXT
  1970-01-01 00:02:06            TEXT
  1970-01-01 00:02:07            TEXT
  1970-01-01 00:02:08            TEXT
  1970-01-01 00:02:09            TEXT
  1970-01-01 00:02:10            TEXT
  1970-01-01 00:02:11            TEXT
  1970-01-01 00:02:12            TEXT
  1970-01-01 00:02:13            TEXT
  1970-01-01 00:02:14            TEXT
  1970-01-01 00:02:15            TEXT
  1970-01-01 00:02:16            TEXT
  1970-01-01 00:02:17            TEXT
  1970-01-01 00:02:18            TEXT
  1970-01-01 00:02:19            TEXT
  1970-01-01 00:02:20            TEXT
  1970-01-01 00:02:21            TEXT
  1970-01-01 00:02:22            TEXT
  1970-01-01 00:02:27            TEXT
  1970-01-01 00:02:29            TEXT
  1970-01-01 00:02:30            TEXT
  1970-01-01 00:02:31            TEXT
  1970-01-01 00:02:32            TEXT
  1970-01-01 00:02:33            TEXT
  1970-01-01 00:02:34            TEXT
  1970-01-01 00:02:35            TEXT
  1970-01-01 00:02:36            TEXT
  1970-01-01 00:02:37            TEXT
  1970-01-01 00:02:38            TEXT
  1970-01-01 00:02:41            TEXT
  1970-01-01 00:02:42            TEXT
  1970-01-01 00:02:44            TEXT
  1970-01-01 00:02:46            TEXT
  1970-01-01 00:02:47            TEXT
  1970-01-01 00:02:48            TEXT
  1970-01-01 00:02:50            TEXT
  1970-01-01 00:02:52            TEXT
  1970-01-01 00:02:53            TEXT
  1970-01-01 00:02:54            TEXT
  1970-01-01 00:02:55            TEXT
  1970-01-01 00:02:57            TEXT
  1970-01-01 00:02:58            TEXT
  1970-01-01 00:03:00            TEXT
  1970-01-01 00:03:01            TEXT
  1970-01-01 00:03:02            TEXT
  1970-01-01 00:03:03            TEXT
  1970-01-01 00:03:05            TEXT
  1970-01-01 00:03:06            TEXT
  1970-01-01 00:03:09            TEXT
  1970-01-01 00:03:10            TEXT
  1970-01-01 00:03:11            TEXT
  1970-01-01 00:03:15            TEXT
  1970-01-01 00:03:16            TEXT
  1970-01-01 00:03:17            TEXT
  1970-01-01 00:03:18            TEXT
  1970-01-01 00:03:19            TEXT
  1970-01-01 00:03:20            TEXT
  1970-01-01 00:03:21            TEXT
  1970-01-01 00:03:23            TEXT
  1970-01-01 00:03:27            TEXT
  1970-01-01 00:03:28            TEXT
  1970-01-01 00:03:29            TEXT
  1970-01-01 00:03:30            TEXT
  1970-01-01 00:03:31            TEXT
  1970-01-01 00:03:32            TEXT
  1970-01-01 00:03:33            TEXT
  1970-01-01 00:03:38            TEXT
  1970-01-01 00:03:39            TEXT
  1970-01-01 00:03:40            TEXT
  1970-01-01 00:03:41            TEXT
  1970-01-01 00:03:42            TEXT
  1970-01-01 00:03:43            TEXT
  1970-01-01 00:03:44            TEXT
  1970-01-01 00:03:45            TEXT
  1970-01-01 00:03:47            TEXT
  1970-01-01 00:03:49            TEXT
  1970-01-01 00:03:52            TEXT
  1970-01-01 00:03:53            TEXT
  1970-01-01 00:03:55            TEXT
  1970-01-01 00:03:57            TEXT
  1970-01-01 00:03:58            TEXT
  1970-01-01 00:03:59            TEXT
  1970-01-01 00:04:00            TEXT
  1970-01-01 00:04:03            TEXT
  1970-01-01 00:04:05            TEXT
  1970-01-01 00:04:06            TEXT
  1970-01-01 00:04:07            TEXT
  1970-01-01 00:04:08            TEXT
  1970-01-01 00:04:09            TEXT
  1970-01-01 00:04:10            TEXT
  1970-01-01 00:04:11            TEXT
  1970-01-01 00:04:12            TEXT
  1970-01-01 00:04:13            TEXT
  1970-01-01 00:04:14            TEXT
  1970-01-01 00:04:15            TEXT
  1970-01-01 00:04:16            TEXT
  1970-01-01 00:04:17            TEXT
  1970-01-01 00:04:18            TEXT
  1970-01-01 00:04:20            TEXT
  1970-01-01 00:04:21            TEXT
  1970-01-01 00:04:22            TEXT
  1970-01-01 00:04:24            TEXT
  1970-01-01 00:04:25            TEXT
  1970-01-01 00:04:26            TEXT
  Unnamed: 206                   REAL

--- sqlite_sequence ---
  name
  seq

--- translations ---
  agency                         TEXT
  stops                          TEXT

--- trips ---
  ATC IR 11501                   TEXT
  ATC IR 11500                   TEXT
  BDŽ 2626                       TEXT
  BDŽ 2627                       TEXT
  BDŽ 2636                       TEXT
  BDŽ 2637                       TEXT
  BDŽ 3636                       TEXT
  BDŽ 3637                       TEXT
  BDŽ 3686                       TEXT
  BDŽ 3687                       TEXT
  BDŽ 8626                       TEXT
  BDŽ 8627                       TEXT
  BDŽ 8656                       TEXT
  BDŽ 8657                       TEXT
  BDŽ 9646                       TEXT
  BDŽ 9647                       TEXT
  ČD EC 458                      TEXT
  ČD EN 40459                    TEXT
  ČD EN 40476                    TEXT
  ČD EN 40457                    TEXT
  CFR/MÁV IRN / IC 78            TEXT
  CFR/MÁV IRN / IC 79            TEXT
  CFR/MÁV IC 406                 TEXT
  CFR/MÁV IC 407                 TEXT
  CFR/MÁV/ÖBB D 346              TEXT
  CFR/MÁV/ÖBB D 347              TEXT
  CFR IC 472                     TEXT
  CFR IC 473                     TEXT
  CFR R 4116                     TEXT
  CFR 1641/R 4112                TEXT
  CFR R-E 4007/1642              TEXT
  CFR 1641/R-E 4008              TEXT
  CFR 1641 (CN)                  TEXT
  CFR 1642 (CN)                  TEXT
  CFR 1641 (SM)                  TEXT
  CFR 1642 (SM)                  TEXT
  CFR 1653                       TEXT
  CFR 1654                       TEXT
  CFR 1667                       TEXT
  CFR 1668                       TEXT
  CFR 78/1743                    TEXT
  CFR 1744/79                    TEXT
  CFR 1763                       TEXT
  CFR 1765                       TEXT
  CFR 1821                       TEXT
  CFR 1822                       TEXT
  CFR 1837                       TEXT
  CFR 1838                       TEXT
  CFR 1920                       TEXT
  CFR 1922                       TEXT
  CFR 1941                       TEXT
  CFR 1942/R 8810                TEXT
  CFR 1952                       TEXT
  CFR 1954                       TEXT
  CFM/CFR 401                    TEXT
  CFM/CFR 402                    TEXT
  CS 1001 (A)                    TEXT
  CS 1002 (A)                    TEXT
  CS 1001 (FW)                   TEXT
  CS 1002 (FW)                   TEXT
  CS 1001 (I)                    TEXT
  CS 1002 (I)                    TEXT
  CS 1003 (G)                    TEXT
  CS 1004 (G)                    TEXT
  CS 1003 (E)                    TEXT
  CS 1004 (E)                    TEXT

In [30]:
# Test : requête exemple
print("Exemple de requête : premières lignes de chaque table\n")

for table in tables_info['table_name']:
    print(f"\n{'='*60}")
    print(f"Table : {table}")
    display(pd.read_sql(f'SELECT * FROM "{table}" LIMIT 3', conn))

Exemple de requête : premières lignes de chaque table


============================================================
Table : agencies

,ATC,BDŽ,ČD,CFM,CFR,CS,ES,FS,GA,GWR,...,SNCF,ST,TCDD,UEX,UZ,VR,VY,ŽPCG,ŽS,ZSSK
0,ATC,BDŽ,ČD,CFM,CFR,CS,ES,FS,GA,GWR,...,SNCF,ST,TCDD,UEX,UZ,VR,VY,ŽPCG,ŽS,ZSSK
1,Astra Trans Carpatic SRL,БДЖ - Пътнически превози ЕООД,České dráhy a.s.,Calea Ferată din Moldova,C.F.R. Călători S.A.,Caledonian Sleeper Ltd.,European Sleeper Cooperatïe,Trenitalia S.p.A,Go-Ahead Norge AS,First Greater Western Ltd.,...,SNCF Voyageurs SA,Merresor AB,TCDD Taşımacılık A.Ş.,Train4you Vertriebs GmbH,Укрзалізниця,VR-Yhtymä Oy,Vygruppen AS,Željeznički prevoz Crne Gore AD,Железнице Србије ад,Železničná spoločnosť Slovensko a.s.
2,https://astratranscarpatic.ro,https://www.bdz.bg,https://www.cd.cz,http://railway.md,https://www.cfrcalatori.ro,https://www.sleeper.scot,https://www.europeansleeper.eu,https://www.trenitalia.com,https://go-aheadnordic.com,https://www.gwr.com,...,https://www.sncf.com,https://www.snalltaget.se,https://www.tcddtasimacilik.gov.tr/,https://buchung.urlaubs-express.de/,https://www.uz.gov.ua/,https://www.vr.fi,https://www.vy.no,https://www.zcg-prevoz.me,https://srbijavoz.rs,https://www.zssk.sk

============================================================
Table : calendrier

,-- 2024 --,Daily,0-2 days/week (May-Oct),"2024/03/31-2024/11/03: Mon, Tue, Wed, Thu, Fri, Sun","2024: Mon, Tue, Wed, Thu, Fri","2024: Mon, Tue, Wed, Thu, Sun",2024: Daily except Sat,"2024: 1-5,7","Mon, Wed, Fri","2024/07/08-2024/09/22: Mon, Wed, Sat",...,2026/06/11-09/06: Daily,Unknown,2026/06/27-2026/08/31: Daily,2026/06/26-2026/08/30: Daily,"2026: Tue, Thu","2026: Mon, Wed, Thu, Fri, Sat","2026: Mon, Wed, Fri, Sat, Son","2026: Thu, Sat",2026: Sat,2026: Tue
0,-- 2024 --,Daily,0-2 days/week (May-Oct),"2024/03/31-2024/11/03: Mon, Tue, Wed, Thu, Fri...","2024: Mon, Tue, Wed, Thu, Fri","2024: Mon, Tue, Wed, Thu, Sun",2024: Daily except Sat,"2024: 1-5,7","Mon, Wed, Fri","2024/07/08-2024/09/22: Mon, Wed, Sat",...,2026/06/11-09/06: Daily,Unknown,2026/06/27-2026/08/31: Daily,2026/06/26-2026/08/30: Daily,"2026: Tue, Thu","2026: Mon, Wed, Thu, Fri, Sat","2026: Mon, Wed, Fri, Sat, Son","2026: Thu, Sat",2026: Sat,2026: Tue
1,None,1,0,1,1,1,1,1,1,0,...,1,None,1,1,0,1,1,0,0,0
2,None,1,0,1,1,1,1,1,0,1,...,1,None,1,1,1,0,0,0,0,1

============================================================
Table : calendrier_dates

,1,2,3,4,5,6,7,8,9,10,...,50,51,52,53,54,55,56,57,58,59
0,1,2,3,4,5,6,7,8,9,10,...,50,51,52,53,54,55,56,57,58,59
1,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,ÖBB NJ 233,...,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,ZSSK EN 1153,PKP/ČD EN 40416,PKP/ČD EN 40417,PKP/ČD EN 406,PKP/ČD EN 407
2,None,None,None,None,None,None,None,None,None,None,...,"2024/05/03-2024/10/02: Wed, Fri, Sun","2024/05/03-2024/10/02: Wed, Fri, Sun","2024/05/03-2024/10/02: Wed, Fri, Sun","2024/05/03-2024/10/02: Wed, Fri, Sun","2024/05/03-2024/10/02: Wed, Fri, Sun","2024/05/03-2024/10/02: Wed, Fri, Sun",2026: Daily,2026: Daily,2026: Daily,2026: Daily

============================================================
Table : classes

,seat (reclinig),seat (compartment),seat,couchette (4-berth),couchette (6-berth),capsule (seat/bed),capsule (bed),Sleeper (2-berth) with shower & WC,Sleeper (double) with shower & WC,Sleeper (3-berth) with shower & WC,Sleeper (2-berth),Sleeper (3-berth)
0,seat (reclinig),seat (compartment),seat,couchette (4-berth),couchette (6-berth),capsule (seat/bed),capsule (bed),Sleeper (2-berth) with shower & WC,Sleeper (double) with shower & WC,Sleeper (3-berth) with shower & WC,Sleeper (2-berth),Sleeper (3-berth)
1,Seat,Seat,Seat,Couchette,Couchette,Capsule,Capsule,Sleeper,Sleeper,Sleeper,Sleeper,Sleeper

============================================================
Table : co2_clean

,country,emissions_train_g_km,emissions_car_g_km,emissions_plane_g_km,co2_saved_vs_car_g_km,co2_saved_vs_plane_g_km,reduction_vs_car_pct
0,France,3.0,192,255,189.0,252.0,98.44
1,Suisse,1.5,180,255,178.5,253.5,99.17
2,Portugal,30.0,190,250,160.0,220.0,84.21

============================================================
Table : od_aggregated

,year,origin_country_iso,flow_type,nb_routes,total_passengers_M,avg_passengers_M,max_route_M
0,2016,CH,cross_border,2,1.649,0.824,1.140
1,2016,CH,domestic,9,19.869,2.208,4.017
2,2016,DE,cross_border,6,11.039,1.840,2.763

============================================================
Table : od_flows_enriched

,year,origin_station,destination_station,origin_city,destination_city,origin_region,destination_region,passengers_millions,service_type,flow_type,source,origin_country_iso,destination_country_iso,emissions_train_g_km,emissions_car_g_km,co2_saved_vs_car_g_km,reduction_vs_car_pct
0,2016,Paris Gare du Nord,Paris Gare de Lyon,Paris,Paris,Île-de-France,Île-de-France,1.05,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF ...",FR,FR,3.0,192.0,189.0,98.44
1,2016,Paris Gare du Nord,Paris Saint-Lazare,Paris,Paris,Île-de-France,Île-de-France,1.13,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF ...",FR,FR,3.0,192.0,189.0,98.44
2,2016,Paris Gare du Nord,Paris Montparnasse,Paris,Paris,Île-de-France,Île-de-France,0.88,TGV/Intercités,domestic,"SNCF Open Data - Fréquentation en gares, SNCF ...",FR,FR,3.0,192.0,189.0,98.44

============================================================
Table : routes

,1970-01-01 00:00:01,1970-01-01 00:00:02,1970-01-01 00:00:03,1970-01-01 00:00:04,1970-01-01 00:00:05,1970-01-01 00:00:06,1970-01-01 00:00:07,1970-01-01 00:00:08,1970-01-01 00:00:09,1970-01-01 00:00:10,...,1970-01-01 00:04:16,1970-01-01 00:04:17,1970-01-01 00:04:18,1970-01-01 00:04:20,1970-01-01 00:04:21,1970-01-01 00:04:22,1970-01-01 00:04:24,1970-01-01 00:04:25,1970-01-01 00:04:26,Unnamed: 206
0,1,2,3,4,5,6,7,8,9,10,...,256,257,258,260,261,262,264,265,266,None
1,ÖBB,ÖBB,HŽPP,ČD,ÖBB,ZSSK,RJ,PKP/ČD,PKP/ČD,PKP,...,UEX,UEX,UZ,ÖBB,RJ,SNCF,SNCF,PKP/ČD,PKP/ČD,None
2,ÖBB,ÖBB,HŽPP,ČD,ÖBB,ZSSK,RJ,PKP,PKP,PKP,...,UEX,UEX,UZ,ÖBB,RJ,SNCF,SNCF,PKP,PKP,None

============================================================
Table : sqlite_sequence

Empty DataFrame
Columns: [name, seq]
Index: []

============================================================
Table : translations

        agency          stops
0       agency          stops
1  agency_name  stop_cityname
2           en             fr

============================================================
Table : trips

,ATC IR 11501,ATC IR 11500,BDŽ 2626,BDŽ 2627,BDŽ 2636,BDŽ 2637,BDŽ 3636,BDŽ 3637,BDŽ 3686,BDŽ 3687,...,VY 605,VY 606,ŽS/ŽPCG 433,ŽS/ŽPCG 1130 / 432,ZSSK R 680,ZSSK R 681,ZSSK EN 442,ZSSK EN 443,ZSSK EN 1152,ZSSK EN 1153
0,24,24,133,133,142,142,132,132,139,139,...,69,69,130,130,123,123,6,6,115,115
1,ATC,ATC,BDŽ,BDŽ,BDŽ,BDŽ,BDŽ,BDŽ,BDŽ,BDŽ,...,VY,VY,ŽS/ŽPCG,ŽS/ŽPCG,ZSSK,ZSSK,ZSSK,ZSSK,ZSSK,ZSSK
2,ATC IR 11501,ATC IR 11500,BDŽ 2626,BDŽ 2627,BDŽ 2636,BDŽ 2637,BDŽ 3636,BDŽ 3637,BDŽ 3686,BDŽ 3687,...,VY 605,VY 606,ŽS/ŽPCG 433,ŽS/ŽPCG 1130 / 432,ZSSK R 680,ZSSK R 681,ZSSK EN 442,ZSSK EN 443,ZSSK EN 1152,ZSSK EN 1153

============================================================
Table : view_ontd_cities

,Aachen Hbf,Aberdeen,Adjud,Afyon A Çetinkaya,Alba Iulia,Albi Ville,Alfatar,Alvesta,Amersfoort Centraal,Amsterdam Centraal,...,Zawiercie,Zemun,Zhmerynka,Zielona Góra Gł.,Zimnitsa,Zlatica,Żory,Zürich HB,Zverino,Unnamed: 726
0,Aachen Hbf,Aberdeen,Adjud,Afyon A Çetinkaya,Alba Iulia,Albi Ville,Alfatar,Alvesta,Amersfoort Centraal,Amsterdam Centraal,...,Zawiercie,Zemun,Zhmerynka,Zielona Góra Gł.,Zimnitsa,Zlatica,Żory,Zürich HB,Zverino,None
1,Aachen,Aberdeen,None,Afyonkarahisar,Alba Iulia,Albi,None,Alvesta,Amersfoort,Amsterdam,...,None,None,None,None,None,None,None,None,None,None
2,DE,UK,RO,TR,RO,FR,BG,SE,NL,NL,...,None,None,None,None,None,None,None,None,None,None

============================================================
Table : view_ontd_list

,1,2,3,4,5,6,7,9,10,11,...,253,254,255,256,257,260,261,262,264,#REF!
0,1,2,3,4,5,6,7,9,10,11,...,253,254,255,256,257,260,261,262,264,#REF!
1,ÖBB NJ 40425 + NJ 40468,ÖBB NJ 408 + NJ 409,HŽPP 1820 + 1821,ČD EN 40476 + EN 40457,ÖBB NJ 470 + NJ 471,ZSSK EN 442 + EN 443,RJ 1020 + 1021,PKP/ČD EN 443 / IC 406 + IC 407 / EN 442,PKP TLK 35190/50191 + TLK 55190/53190,CFR 1837 + 1838,...,UEX 302/322 + 303/323,UEX 1856 + 1857,UEX 1858 + 1859,UEX 332/1372 + 333/1373,UEX 334/1374 + 335/1375,ÖBB NJ 40424 + NJ 40469,RJ 1038 + 1039,SNCF IC Nuit 3789 + IC Nuit 3790,SNCF IC Nuit 3750 + IC Nuit 3751,#REF!
2,None,None,None,Metropol,None,Slovakia,None,Chopin,Rozewie,None,...,None,None,None,None,None,None,None,None,None,#REF!

============================================================
Table : view_ontd_map

,1,2,3,4,5,6,7,9,10,11,...,252,253,254,255,256,257,260,261,262,264
0,1,2,3,4,5,6,7,9,10,11,...,252,253,254,255,256,257,260,261,262,264
1,ÖBB,ÖBB,HŽPP,ČD,ÖBB,ZSSK,RJ,PKP/ČD,PKP,CFR,...,UEX,UEX,UEX,UEX,UEX,UEX,ÖBB,RJ,SNCF,SNCF
2,NJ 40425,NJ 408,1820,EN 40476,NJ 470,EN 442,1020,EN 443 / IC 406,TLK 35190/50191,1837,...,320/324,302/322,1856,1858,332/1372,334/1374,NJ 40424,1038,IC Nuit 3789,IC Nuit 3750

In [31]:
import sqlite3

DB_PATH = "rail_europe.db"  # Modifier si nécessaire

TABLES = [
    "agencies",
    "calendrier",
    "calendrier_dates",
    "classes",
    "routes",
    "stops",
    "translations",
    "trip_stop",
    "trips",
    "view_ontd_cities",
    "view_ontd_details",
    "view_ontd_list",
    "view_ontd_map",
]

conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

for table in TABLES:
    nouveau_nom = f"{table}_nuit"
    try:
        cursor.execute(f'ALTER TABLE "{table}" RENAME TO "{nouveau_nom}";')
        print(f"  ✓ {table} → {nouveau_nom}")
    except Exception as e:
        print(f"  ✗ {table} → {e}")

conn.commit()
conn.close()
print("\nRenommage terminé.")

  ✓ agencies → agencies_nuit
  ✓ calendrier → calendrier_nuit
  ✓ calendrier_dates → calendrier_dates_nuit
  ✓ classes → classes_nuit
  ✓ routes → routes_nuit
  ✗ stops → no such table: stops
  ✓ translations → translations_nuit
  ✗ trip_stop → no such table: trip_stop
  ✓ trips → trips_nuit
  ✓ view_ontd_cities → view_ontd_cities_nuit
  ✗ view_ontd_details → no such table: view_ontd_details
  ✓ view_ontd_list → view_ontd_list_nuit
  ✓ view_ontd_map → view_ontd_map_nuit

Renommage terminé.

In [32]:
# Fermeture de la connexion
conn.close()
print("Connexion fermée. Base de données prête !")

Connexion fermée. Base de données prête !

In [4]:
import sqlite3
import pandas as pd
import os

# Modifier ces chemins selon votre environnement
DB_PATH = "rail_europe.db"
CSV_PATH = "empreinte_carbone_trajets.csv"
NOM_TABLE = "empreinte_carbone_trajets"

print(f"Base de données : {os.path.abspath(DB_PATH)}")
print(f"Fichier CSV     : {os.path.abspath(CSV_PATH)}")
print(f"Table cible     : {NOM_TABLE}")

Base de données : c:\Users\scott\Desktop\epsi\github\MsprDS\csv\rail_europe.db
Fichier CSV     : c:\Users\scott\Desktop\epsi\github\MsprDS\csv\empreinte_carbone_trajets.csv
Table cible     : empreinte_carbone_trajets

In [6]:
df = pd.read_csv(CSV_PATH, encoding="utf-8")
df.columns = df.columns.str.strip()

print(f"{len(df)} lignes | {len(df.columns)} colonnes")
print(f"\nColonnes : {list(df.columns)}")
df.head(5)

100 lignes | 13 colonnes

Colonnes : ['transporteur', 'origine', 'origine_uic', 'destination', 'destination_uic', 'distance_entre_les_gares', 'train_empreinte_carbone_kgco2e', 'distance_routiere', 'autocar_longue_distance_empreinte_carbone_kgco2e', 'voiture_electrique_2_2_pers_empreinte_carbone_kgco2e', 'voiture_thermique_2_2_pers_empreinte_carbone_kgco2e', 'distance_aerienne', 'avion_empreinte_carbone_kgco2e']

,transporteur,origine,origine_uic,destination,destination_uic,distance_entre_les_gares,train_empreinte_carbone_kgco2e,distance_routiere,autocar_longue_distance_empreinte_carbone_kgco2e,voiture_electrique_2_2_pers_empreinte_carbone_kgco2e,voiture_thermique_2_2_pers_empreinte_carbone_kgco2e,distance_aerienne,avion_empreinte_carbone_kgco2e
0,TGV,Paris Nord,87271007,Calais Ville,87317263,335.000,1.172500,297.0,11.286,27.918,26.433,NaN,NaN
1,TGV,Paris Gare de Lyon,87686006,Montpellier Saint-Roch,87773002,738.861,2.586013,749.0,28.462,70.406,66.661,596.0,74.500
2,TGV,Paris Montparnasse,87391003,Arcachon,87582668,595.000,2.082500,650.0,24.700,61.100,57.850,NaN,NaN
3,TGV,Aéroport Charles de Gaulle 2 TGV,87271494,Bruxelles Midi Brussel Zuid,88140010,291.000,1.018500,289.0,10.982,27.166,25.721,241.0,30.125
4,TGV,Paris Gare de Lyon,87686006,Chambéry - Challes-les-Eaux,87741009,531.951,1.861829,571.0,21.698,53.674,50.819,NaN,NaN

In [7]:
conn = sqlite3.connect(DB_PATH)

# Import dans la BD (remplace la table si elle existe déjà)
df.to_sql(NOM_TABLE, conn, if_exists="replace", index=False)

# Vérification
count = pd.read_sql(f'SELECT COUNT(*) as n FROM "{NOM_TABLE}"', conn).iloc[0, 0]
print(f"✓ Table '{NOM_TABLE}' créée : {count} lignes")

✓ Table 'empreinte_carbone_trajets' créée : 100 lignes

In [8]:
cursor = conn.cursor()

INDEX = [
    f'CREATE INDEX IF NOT EXISTS idx_ect_transporteur ON "{NOM_TABLE}"(transporteur);',
    f'CREATE INDEX IF NOT EXISTS idx_ect_origine ON "{NOM_TABLE}"(origine);',
    f'CREATE INDEX IF NOT EXISTS idx_ect_destination ON "{NOM_TABLE}"(destination);',
    f'CREATE INDEX IF NOT EXISTS idx_ect_origine_uic ON "{NOM_TABLE}"(origine_uic);',
    f'CREATE INDEX IF NOT EXISTS idx_ect_destination_uic ON "{NOM_TABLE}"(destination_uic);',
]

for sql in INDEX:
    cursor.execute(sql)
    nom = sql.split('idx_')[1].split(' ')[0]
    print(f"  ✓ Index créé : idx_{nom}")

conn.commit()
print("\nIndex créés avec succès.")

  ✓ Index créé : idx_ect_transporteur
  ✓ Index créé : idx_ect_origine
  ✓ Index créé : idx_ect_destination
  ✓ Index créé : idx_ect_origine_uic
  ✓ Index créé : idx_ect_destination_uic

Index créés avec succès.

In [9]:
schema = pd.read_sql(f'PRAGMA table_info("{NOM_TABLE}")', conn)
print(f"Schéma de la table '{NOM_TABLE}' :\n")
for _, row in schema.iterrows():
    print(f"  {row['name']:55s} {row['type']}")

Schéma de la table 'empreinte_carbone_trajets' :

  transporteur                                            TEXT
  origine                                                 TEXT
  origine_uic                                             INTEGER
  destination                                             TEXT
  destination_uic                                         INTEGER
  distance_entre_les_gares                                REAL
  train_empreinte_carbone_kgco2e                          REAL
  distance_routiere                                       REAL
  autocar_longue_distance_empreinte_carbone_kgco2e        REAL
  voiture_electrique_2_2_pers_empreinte_carbone_kgco2e    REAL
  voiture_thermique_2_2_pers_empreinte_carbone_kgco2e     REAL
  distance_aerienne                                       REAL
  avion_empreinte_carbone_kgco2e                          REAL

In [10]:
pd.read_sql(f'SELECT * FROM "{NOM_TABLE}" LIMIT 5', conn)

,transporteur,origine,origine_uic,destination,destination_uic,distance_entre_les_gares,train_empreinte_carbone_kgco2e,distance_routiere,autocar_longue_distance_empreinte_carbone_kgco2e,voiture_electrique_2_2_pers_empreinte_carbone_kgco2e,voiture_thermique_2_2_pers_empreinte_carbone_kgco2e,distance_aerienne,avion_empreinte_carbone_kgco2e
0,TGV,Paris Nord,87271007,Calais Ville,87317263,335.000,1.172500,297.0,11.286,27.918,26.433,NaN,NaN
1,TGV,Paris Gare de Lyon,87686006,Montpellier Saint-Roch,87773002,738.861,2.586013,749.0,28.462,70.406,66.661,596.0,74.500
2,TGV,Paris Montparnasse,87391003,Arcachon,87582668,595.000,2.082500,650.0,24.700,61.100,57.850,NaN,NaN
3,TGV,Aéroport Charles de Gaulle 2 TGV,87271494,Bruxelles Midi Brussel Zuid,88140010,291.000,1.018500,289.0,10.982,27.166,25.721,241.0,30.125
4,TGV,Paris Gare de Lyon,87686006,Chambéry - Challes-les-Eaux,87741009,531.951,1.861829,571.0,21.698,53.674,50.819,NaN,NaN

In [11]:
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name", conn)

print(f"{'Table':40s} | {'Lignes':>10s}")
print("-" * 55)
for table in tables['name']:
    c = pd.read_sql(f'SELECT COUNT(*) as n FROM "{table}"', conn).iloc[0, 0]
    print(f"{table:40s} | {c:>10,}")

print(f"\nTotal : {len(tables)} tables")

Table                                    |     Lignes
-------------------------------------------------------
agencies_nuit                            |         15
calendrier_dates_nuit                    |          7
calendrier_nuit                          |         10
classes_nuit                             |          2
co2_clean                                |          5
empreinte_carbone_trajets                |        100
od_aggregated                            |         72
od_flows_enriched                        |      2,680
routes_nuit                              |         21
sqlite_sequence                          |          0
translations_nuit                        |          6
trips_nuit                               |         31
view_ontd_cities_nuit                    |          5
view_ontd_list_nuit                      |          8
view_ontd_map_nuit                       |         20

Total : 15 tables

In [12]:
conn.close()
print("Connexion fermée. Import terminé !")

Connexion fermée. Import terminé !

In [2]:
import pandas as pd
df=pd.read_csv("stops.csv", encoding="utf-8")

In [3]:
df

,Baqël,Bishqem,Budull,Durrës,Elbasan,Fushë-Krujë,Golem,Han i Hotit,Ishëm,Kashar,...,Shëngjergj,Siperant,Sllatinë e lbrit,Soqanicë,Stagonë,Ujmirë,Vallaq,Vërrin,Vushtrri,Xërxë
0,Baqël,Bishqem,Budull,Durrës,Elbasan,Fushë-Krujë,Golem,Han i Hotit,Ishëm,Kashar,...,Shëngjergj,Siperant,Sllatinë e lbrit,Soqanicë,Stagonë,Ujmirë,Vallaq,Vërrin,Vushtrri,Xërxë
1,Baqël,Bishqem,Budull,Durrës,Elbasan,Fushë-Krujë,Golem,Han i Hotit,Ishëm,Kashar,...,Shëngjergj,Siperant,Sllatinë e lbrit,Soqanicë,Stagonë,Ujmirë,Vallaq,Vërrin,Vushtrri,Xërxë
2,AL,AL,AL,AL,AL,AL,AL,AL,AL,AL,...,XK,XK,XK,XK,XK,XK,XK,XK,XK,XK
3,CET,CET,CET,CET,CET,CET,CET,CET,CET,CET,...,CET,CET,CET,CET,CET,CET,CET,CET,CET,CET
4,41.8946382,41.0618593,41.4533953,41.3178256,41.1113835,41.4775884,41.2570653,42.3372822,41.5332101,41.3583561,...,42.6026359,42.6026359,42.8476469,43.0576194,42.6026359,42.6145259,42.9460375,42.6026359,42.8267025,42.0791097
5,19.6475637,19.8661116,19.6669068,19.4546081,20.0822631,19.7204757,19.526782,19.4344633,19.6103673,19.7412052,...,20.902977,20.902977,20.9636174,20.8110973,20.902977,20.6949084,20.8318529,20.902977,20.9703489,20.6839374
6,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Station,Halt stat.,Station,Halt stat.,Halt stat.,Halt stat.,Station,Halt stat.,Station,Station
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df=pd.read_csv("routes.csv")

In [5]:
df

,1970-01-01 00:00:01,1970-01-01 00:00:02,1970-01-01 00:00:03,1970-01-01 00:00:04,1970-01-01 00:00:05,1970-01-01 00:00:06,1970-01-01 00:00:07,1970-01-01 00:00:08,1970-01-01 00:00:09,1970-01-01 00:00:10,...,1970-01-01 00:04:16,1970-01-01 00:04:17,1970-01-01 00:04:18,1970-01-01 00:04:20,1970-01-01 00:04:21,1970-01-01 00:04:22,1970-01-01 00:04:24,1970-01-01 00:04:25,1970-01-01 00:04:26,Unnamed: 206
0,1,2,3,4,5,6,7,8,9,10,...,256,257,258,260,261,262,264,265,266,NaN
1,ÖBB,ÖBB,HŽPP,ČD,ÖBB,ZSSK,RJ,PKP/ČD,PKP/ČD,PKP,...,UEX,UEX,UZ,ÖBB,RJ,SNCF,SNCF,PKP/ČD,PKP/ČD,NaN
2,ÖBB,ÖBB,HŽPP,ČD,ÖBB,ZSSK,RJ,PKP,PKP,PKP,...,UEX,UEX,UZ,ÖBB,RJ,SNCF,SNCF,PKP,PKP,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ČD,ČD,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ČD,ČD,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NJ 40425 = NJ 40468,NJ 408 = NJ 409,1820 = 1821,EN 40476 = EN 40457,NJ 470 = NJ 471,EN 442 = EN 443,1020 = 1021,=,EN 443 / IC 406 = IC 407 / EN 442,TLK 35190/50191 = TLK 55190/53190,...,332/1372 = 333/1373,334/1374 = 335/1375,069 = 070,NJ 40424 = NJ 40469,1038 = 1039,IC Nuit 3789 = IC Nuit 3790,IC Nuit 3750 = IC Nuit 3751,TLK 403/50171 = TLK 55170/402,TLK 403 = TLK 402,NaN
6,NaN,NaN,NaN,Metropol,NaN,Slovakia,NaN,Carpathia,Chopin,Rozewie,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wydmy,Wydmy,NaN
7,NJ 40425: Bruxelles Midi / Brussel Zuid - Brux...,NJ 408: Berlin Hbf - Berlin Südkreuz - Luthers...,1820: Split - Knin - Karlovac - Zagreb Gl. K. ...,EN 40476: Budapest-Nyugati - Vac - Štúrovo - N...,NJ 470: Zürich HB - Basel SBB - Basel Bad Bf -...,EN 442: Humenné - Strážske - Michalovce - Báno...,1020: Chop - Košice - Poprad Tatry - Pardubice...,: - - // : - -,EN 443 / IC 406: Praha hl.n. - Pardubice hl.n....,TLK 35190/50191: Kraków Gł. - Trzebinia - Gdań...,...,332/1372: Innsbruck Hbf - Jenbach - München Os...,334/1374: Villach Hbf - Salzburg Hbf - München...,069: Przemyśl Gł. - Lviv - Ternopil - Khmelnyt...,NJ 40424: Berlin Ostbahnhof - Berlin Hbf - Göt...,1038: Przemyśl Gł. - Kraków Gł. - Olomouc hl.n...,IC Nuit 3789: Paris Austerlitz - St-Denis-lès-...,IC Nuit 3750: Toulouse Matabiau - Montauban Vi...,TLK 403/50171: Bohumín - non-stop - Hel // TLK...,TLK 403: Bohumín - - Łeba // TLK 402: Łeba - ...,NaN
8,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2024,NaN,NaN,2024,NaN,NaN,NaN
10,Y,Y,Y,Y,Y,Y,Y,Y,Y,N,...,Y,Y,Y,N,Y,Y,Y,Y,Y,NaN
11,Bruxelles / Brussel,Berlin,Split,NaN,Zürich,Humenné,Chop,NaN,Praha,Kraków,...,Innsbruck,Villach,Przemyśl,Berlin,Przemyśl,Paris,Toulouse,Bohumín,Bohumín,NaN
12,Wien,Zürich,Zagreb,Berlin,Hamburg,Praha,Praha,NaN,Warszawa,Hel,...,Düsseldorf,Düsseldorf,Kremenchuk,Paris,Praha,Aurillac,Paris,Hel,Łeba,NaN
13,NaN,NaN,424,608,1011,745,672,NaN,NaN,NaN,...,NaN,NaN,935,1168,740,602,714,NaN,NaN,NaN
14,NaN,NaN,11.6,10.5,18,12.6,11.8,NaN,NaN,NaN,...,NaN,NaN,17.888059701492537,12.8,20.6,3.9,2.2,NaN,NaN,NaN
15,"seat, couchette, sleeper","seat, couchette, sleeper","seat, couchette, sleeper",sleeper,"seat, couchette, sleeper","seat, couchette, sleeper","seat, couchette, sleeper",NaN,"seat, couchette, sleeper","seat, couchette, sleeper",...,"couchette, sleeper","couchette, sleeper",sleeper,"seat, couchette, sleeper","seat, couchette, sleeper","seat, couchette","seat, couchette",NaN,NaN,NaN
16,"BE, DE, AT","DE, CH",HR,"HU, CZ","DE, CH","SK, CZ","SK, CZ","CZ, PL","CZ, PL",PL,...,DE,DE,"PL, UA","DE, FR","PL, CZ",FR,FR,"CZ, PL","CZ, PL",NaN
17,https://www.nightjet.com/,https://www.nightjet.com/,https://www.hzpp.hr/en/#,https://www.cd.cz/en/spojeni-a-jizdenka/,https://www.nightjet.com/,https://www.zssk.sk/en/night-trains/,https://regiojet.de/,https://www.intercity.pl/en/,https://www.intercity.pl/en/,https://www.intercity.pl/en/,...,https://buchung.urlaubs-express.de/,https://buchung.urlaubs-express.de/,https://booking.uz.gov.ua/en/,https://www.nightjet.com/,https://regiojet.de/,https://www.sncf-connect.com/en-en/,https://www.sncf-connect.com/en-en/,https://www.intercity.pl/en/,https://www.intercity.pl/en/,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,https://www.raileurope.com/,https://www.raileurope.com/,NaN,NaN,NaN
19,https://back-on-track.eu/wp-content/uploads/20...,https://back-on-track.eu/wp-content/uploads/20...,NaN,NaN,https://back-on-track.eu/wp-content/uploads/20...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,https://back-on-track.eu/wp-content/uploads/20...,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,1:23,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN